### ISSUE TITLE
Sending Emails doesn't work when user is not logged in

### ISSUE THREAD

**Issue by c-holtermann** [Admidio/admidio#1005]
I wrote a message in the frontend of the just setupped system. First the mail system did not work, now I have it working and can send emails when I am logged in. I was surprised to get an 500 internal server error when trying to send an email when I was not logged in.

It is an dockerized setting with current master

docker log file:

    [Thu Jan 28 14:00:21.290898 2021] [php7:notice] [pid 212] [client 192.168.203.1:36230] PHP Notice:  Undefined variable: gL10n in /opt/app-root/src/adm_program/system/classes/Email.php on line 510, referer: https://mail3.forum-am.net/admidio//adm_program/modules/messages/messages_write.php
    [Thu Jan 28 14:00:21.290959 2021] [php7:error] [pid 212] [client 192.168.203.1:36230] PHP Fatal error:  Uncaught Error: Call to a member function get() on null in /opt/app-root/src/adm_program/system/classes/Email.php:510\nStack trace:\n#0 /opt/app-root/src/adm_program/modules/messages/messages_send.php(505): Email->setTemplateText('TEST', 'Christoph Holte...', '', 'Administrator')\n#1 {main}\n  thrown in /opt/app-root/src/adm_program/system/classes/Email.php on line 510, referer: https://mail3.forum-am.net/admidio//adm_program/modules/messages/messages_write.php
    192.168.203.1 - - [28/Jan/2021:14:00:21 +0100] "POST /adm_program/modules/messages/messages_send.php HTTP/1.1" 500 - "https://mail3.forum-am.net/admidio//adm_program/modules/messages/messages_write.php" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36"

It seems as if `gL10n` has not been properly initialized.

**Comment by Fasse** [comment]
Could you reproduce this error at our demo page or do you think this is something docker specific?

**Comment by Fasse** [comment]
We fixed problem that through #1013 within version 4.0.5
