### ISSUE TITLE
Password Change not working - Version 4.04

### ISSUE THREAD

**Issue by bcbrookie** [Admidio/admidio#1012]
Hi Fasse

The password sent to a new member via system notification works, but if they try to change it through Profile/Change Password once logged in, a message that the password is not secure appears - we have the setting at "Middle" and still doesn't work at "Low" - same message - these are PW's that have worked before at the same settings - at least at 4.03 level.

Thanks ... Bryan

![PW Change](https://user-images.githubusercontent.com/77950158/106675736-82c7c100-656a-11eb-88b0-846fdbcfc545.jpg)

**Comment by Fasse** [comment]
Thats a problem of the libraries behind that. We have a javascript library that will check that for the indicator and we have a php library that will check that after you send the form. At some passwords they have a different check. 

You can set the password security to low so this error will not occur so often.

**Comment by Fasse** [comment]
view #487

**Comment by bcbrookie** [comment]
Many thanks for getting back to me

Cheers ... Bryan
