### ISSUE TITLE
Docker: No such container: Admidio-MariaDB.

### ISSUE THREAD

**Issue by aroslanov** [Admidio/admidio#1016]
Docker image won't start with the command line provided.
`docker: Error response from daemon: could not get container for Admidio-MariaDB: No such container: Admidio-MariaDB.`

Ubuntu 20.04.2 LTS

**Comment by schast** [comment]
@aroslanov: as described in the [README-Docker.md](https://github.com/Admidio/admidio/blob/master/README-Docker.md#start-a-mariadb-server-instance-optional) you must first start a database container before you can link it.

**Comment by aroslanov** [comment]
> @aroslanov: as described in the [README-Docker.md](https://github.com/Admidio/admidio/blob/master/README-Docker.md#start-a-mariadb-server-instance-optional) you must first start a database container before you can link it.

I suggest this should be mentioned on the main page or docker run command should be removed if it's useless without reading README-Docker.md.

**Comment by Fasse** [comment]
can we close this?
