### ISSUE TITLE
In List Configuration Roles are not being saved!

### ISSUE THREAD

**Issue by bcbrookie** [Admidio/admidio#1017]
When I create or edit a list configuration and specify a Role(s) and save the configuration, if you display the configuration again the Role(s) has disappeared
![Edit List Role Selection](https://user-images.githubusercontent.com/77950158/107471734-6efbfc00-6b22-11eb-9103-ed891c02750e.jpg)

**Comment by Fasse** [comment]
The roles are not part of the list configuration and are therefore not saved if you save the list configuration.

**Comment by bcbrookie** [comment]
Apologies! – In the configuration edit, the field is marked as required, so I assumed that it was saved for future edits

 

Cheers … Bryan
