### ISSUE TITLE
Pop Up Calendar hidden by Nav Bar when Filtering Events

### ISSUE THREAD

**Issue by bcbrookie** [Admidio/admidio#1020]
Hi Fasse - when in Events and filtering Events based on date selection, the pop up calendar is partially hidden behind the Nav Bar?

Cheers ... Bryan

![Calendar Display Issue](https://user-images.githubusercontent.com/77950158/107861388-65141a80-6dfa-11eb-8570-53673ec442ad.jpg)

**Comment by Fasse** [comment]
The popup is created dynamically. In my test it always appears below the date field. Have you tried it with different browsers and screen solutions?

**Comment by bcbrookie** [comment]
Thanks Fasse! – it appears to browser related as you recommend – Firefox appears to be the problem

 

Cheers … Bryan
