### ISSUE TITLE
Microsoft Export to Excel - list Separator Parameter

### ISSUE THREAD

**Issue by bcbrookie** [Admidio/admidio#1025]
The export to Excel capability is set to have a semicolon as the “delimiter” (Lists_show.php), which I believe is common in Europe? Whereas a comma is common in North America as the separator. Can this be changed to be a parameter which can be specified in the Regional Preferences?

Cheers ... Bryan

**Comment by Fasse** [comment]
This problem is fixed in version 4.3 because we used there a native excel export.
