### ISSUE TITLE
PHP Fatal error when trying to show a list

### ISSUE THREAD

**Issue by jochen-ac** [Admidio/admidio#1029]
v.4.0.latest
PHP Fatal error:  Uncaught Error: Call to a member function fetchAll() on bool in /admidio/adm_program/modules/groups-roles/lists_show.php:290
Stack trace:
#0 {main}
  thrown in /adm_program/modules/groups-roles/lists_show.php on line 290

**Comment by jochen-ac** [comment]
The reason seems to be a extra comma at the end of the column selection in $mainSql.

**Comment by jochen-ac** [comment]
Workaround: You have to go once the settings for groups and roles and click saves. Then the default list configuration will be save again. Of course it would be better if this would already happen during the update.

**Comment by Fasse** [comment]
could you have a look at the preference `groups_roles_default_configuration` before you do your workaround.

Does the preference exists and which value did it have?

**Comment by Fasse** [comment]
Could not be reproduced.
