### ISSUE TITLE
Menu item Documents & Files is displayed although module is deactivated

### ISSUE THREAD

**Issue by jochen-ac** [Admidio/admidio#1030]
The menu item Documents and Files behaves differently from the entries of the other modules. Although the module is deactivated, the menu item is still displayed.

**Comment by Fasse** [comment]
May this be a problem of the cache?
At https://www.admidio.org/playground I have deactivated the module and it won't be shown in the menu.

**Comment by Fasse** [comment]
Could you reproduce that problem?

**Comment by Fasse** [comment]
Could not be reproduced.
