### ISSUE TITLE
Improve forgotten password functionality

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#1031]
We should add the following improvements to the forgotten password functionality:
- don't send new password, only send a link with an unique hash to change the password with a formular at the webpage.
- hash should only be valid for a small time period e.g. 30 minutes.
- at some points in the process we send the new password (e.g. registration of an existing user). we should only send a mail with a link to the forgotten password formular. therefore we need a new system mail.

**Comment by ximex** [comment]
I think each link should only valid once to open

**Comment by Fasse** [comment]
Yes that should also be considered. The timer should be there that it's not possible to use old email links that were send and not used by a user.
