### ISSUE TITLE
Export Relations

### ISSUE THREAD

**Issue by karibuTW** [Admidio/admidio#1042]
Hello,

We are planning to use Admidio for a parents association and we need to register each family with 1 account, that could add their children to the platform.
We are not so sure how to let 1 account create their profile + their 2nd parent + their X children. 
And then we should be able to download this.

Is it something possible at the moment?

Thanks

**Comment by Fasse** [comment]
No, it's not possible to export relations.

Please use for support questions our [forum](https://www.admidio.org/forum)
