### ISSUE TITLE
User sees his own group memberships only if all group memebers are visible

### ISSUE THREAD

**Issue by kainhofer** [Admidio/admidio#1045]
**Describe the bug**
I have a group ("Vereinsmitglieder"), which has "Display role memberships" set to "Nobody" for data protection reasons (we cannot have all association members see all other members and their data!). Unfortunately, this also means that no user can see his/her OWN membership of that group!

**To Reproduce**
1. Create a group with "Display role memberships" set to "Nobody"
2. Assign an ordinary user to the new group
3. Log in as the ordinary user, go to "My Profile"
4. The user does not see his own membership of the group

**Expected behavior**
The user should see all his own memberships, just not see all other members of that group.

**Comment by kainhofer** [comment]
I think this "fix" blew a big hole into the group membership data: Now, even though a group is set to "Nobody", any member can see his membership (which is what I wanted), but when clicking on the group in his own profile, all members of the group (including all their contact data) will be visible to the member, too.

So, effectively this means that "Nobody" has the same effect as "Role members"... Come to think of it, it might even make sense to have 5 levels of visibility:

- Nobody (members cannot even see their own membership, e.g. for internal roles/groups used to control access or some other internal structure etc.)
- See only own membership (no other users will be shown, but the group membership is visible to the user)
- "Role Members (only names)" (only names but not further data of group members are visible to all group members)
- Role Members (each member can see all data of all other group members
- Logged-in Users (all logged-in users, even non-members of the group can see all data of group members).

**Comment by Fasse** [comment]
Ok you are right. 

So I will revert my changes. But I must think about the solution because your suggestion is not a quick fix, it's an enhancement to the current role visibility structure.

**Comment by Fasse** [comment]
Next try to fix this problem. 
Within the own profile all roles will be listed if you have or had a membership.
