### ISSUE TITLE
Show only names or other group members, but not contact data

### ISSUE THREAD

**Issue by kainhofer** [Admidio/admidio#1046]
**Is your feature request related to a problem? Please describe.**
We have several working groups in our association, where the members of the working group should see who else is a member of the working group, but they should never, ever see the private contact data of all the other members. The current visibility settings mean that either a group member does not see any information about the other group members at all, or he sees all private contact details of the other members.

**Describe the solution you'd like**
Add another "Display role memberships" option "Role members (names only)". If this is selected, role members will be allowed to see the list of all other members, but not their profiles or private contact data.

**Comment by Fasse** [comment]
Why don't you configure the visibility of profile fields through the categories? 
There you can set all categories invisible to the "default" member.
