### ISSUE TITLE
Drop Support PHP 5.3 & 5.4 & 5.5

### ISSUE THREAD

**Issue by ximex** [Admidio/admidio#105]
There are no more security updates for PHP 5.3 and PHP 5.4. PHP 5.5 now only got security updates until 10.07.2016.

http://www.heise.de/security/meldung/Zwoelf-Sicherheitsluecken-in-PHP-geschlossen-Support-fuer-Version-5-5-ausgelaufen-2774343.html
https://secure.php.net/supported-versions.php

**Comment by Fasse** [comment]
This is the same discussion as with browsers. I want Admidio to support old software as long as possible. I think that there is no need to cancel support for 5.3 or 5.4. Also if there are no security updates, a lot of servers use these versions. 

Only if we want/must use PHP features that requires newer versions than this is an option.

**Comment by ximex** [comment]
## Changes:
- **5.3 -> 5.4:** http://it2.php.net/manual/en/migration54.php
- **5.3 -> 5.5:** http://it2.php.net/manual/en/migration55.php

## Highlights:
### 5.3 -> 5.4
- array_combine() now returns array() instead of FALSE when two empty arrays are provided as parameters.
- Short array syntax has been added, e.g. $a = [1, 2, 3, 4]; or $a = ['one' => 1, 'two' => 2, 'three' => 3, 'four' => 4];.
- <?= is now always available, regardless of the short_open_tag php.ini option.
- Class member access on instantiation has been added, e.g. (new Foo)->bar().
- It's now possible to enforce the class' __construct arguments in an abstract constructor in the base class.
- The default character set for htmlspecialchars() and htmlentities() is now UTF-8, instead of ISO-8859-1. Note that changing your output charset via the default_charset configuration setting does not affect htmlspecialchars/htmlentities unless you are passing "" (an empty string) as the encoding parameter to your htmlspecialchars()/htmlentities() calls. Generally we do not recommend doing this because you should be able to change your output charset without affecting the runtime charset used by these functions. The safest approach is to explicitly set the charset on each call to htmlspecialchars() and htmlentities().

### 5.4 -> 5.5
- Support for Windows XP and 2003 has been dropped. Windows builds of PHP now require Windows Vista or newer.
- Prior to PHP 5.5, cases existed where the self, parent, and static keywords were treated in a case sensitive fashion. These have now been resolved, and these keywords are always handled case insensitively: SELF::CONSTANT is now treated identically to self::CONSTANT.
- try-catch blocks now support a finally block for code that should be run regardless of whether an exception has been thrown or not.
- A new password hashing API that makes it easier to securely hash and manage passwords using the same underlying library as crypt() in PHP has been added. See the documentation for password_hash() for more detail.
- The foreach control structure now supports unpacking nested arrays into separate variables via the list() construct.
- Passing an arbitrary expression instead of a variable to empty() is now supported.
- The original MySQL extension is now deprecated, and will generate E_DEPRECATED errors when connecting to a database. Instead, use the MySQLi or PDO_MySQL extensions.
- new Functions: array_column(), boolval(), password_get_info(), password_hash(), password_needs_rehash(), password_verify()
- Flipping support using the new imageflip() function.
- Advanced cropping support using the imagecrop() & imagecropauto() functions.
- WebP read and write support using imagecreatefromwebp() & imagewebp() respectively.

**Comment by ximex** [comment]
would be done if we move to a REST API
152

**Comment by ximex** [comment]
PHP 5.6 News
> As it is the final PHP 5 release, support for PHP 5.6 has been extended: active support will run for an additional four months, and the security fix period has been doubled from one to two years. Other releases are unaffected.

Admidio 4.0 release would be about Start 2017. There the support of PHP 5.5 is completely dropped for about half a year. So we could drop it. Maybe we should make Admidio 3.2 to a LTS release.

**Comment by ximex** [comment]
PHP 5.5 has reached EOL!
https://secure.php.net/supported-versions.php

**Comment by ximex** [comment]
I have dropped PHP 5.3, 5.4, 5.5 for Admidio v4.0 now.

**Comment by Fasse** [comment]
which feature of PHP 5.6 do we use so that we couldn't support PHP 5.5?

**Comment by ximex** [comment]
in use from us is only `hash_equals` now.
I plan to use the `...` operator and array constants for new features.

The biggest thing is that some libs that i want to use don't support old versions of PHP any more. Eg: PhpUnit

**Comment by Fasse** [comment]
Ok
