### ISSUE TITLE
Allow open-ended events

### ISSUE THREAD

**Issue by j0hax** [Admidio/admidio#1055]
**Is your feature request related to a problem? Please describe.**
Not a problem, just a suggestion 😄 

**Describe the solution you'd like**
A simple checkbox/boolean would allow an event editor to mark the event as open-ended. Events could, for example, then be displayed with *"Open End"* inside Admidio. For some uses, such as on the calendar overview or in an iCal export, ending the event at 23:59 of the same day would suffice, in my opinion.

**Describe alternatives you've considered**
Currently, we end these events at 23:59 manually.

**Additional context**
Most events that my association hosts have a determined beginning date and time but no clear ending time, such as public talks or parties.

**Comment by Fasse** [comment]
Hmm, I understand your intention behind that request, but it would break some logik within the events because we don't have an end date to filter.

So therefore I think we could not integrate that feature :(
