### ISSUE TITLE
Admidio sendet E-Mails an Jabber/XMPP-Konten

### ISSUE THREAD

**Issue by ChristophFranzen** [Admidio/admidio#1061]
Ich fand gerade folgendes im Posteingang:
--8<----------------------------
Unzustellbarkeitsbericht

Ihre E-Mail an chf@jabber.ccc.de konnte nicht zugestellt werden. Der
Zielserver des Empfängers sagt: <chf@jabber.ccc.de>: host
mail.ccc.de[212.12.55.66] said: 550 5.7.1 <chf@jabber.ccc.de>:
Recipient address rejected: something@jabber.ccc.de are jabber/xmpp
accounts, not email addresses (in reply to RCPT TO command)
--8<----------------------------

Admidio sollte nicht an alles, was ein @ enthält, eine Mail senden, sondern NUR an Kontakt-Adressen, die im E-Mail-Feld des Profils stehen.

Ich nehme mal an, das ist bislang nicht weiter aufgefallen, weil ich einer der wenigen sein dürfte, der XMPP an Stelle dieses Gruselkrams wie Facebook benutzt – oder es wurde schon behoben:
Admidio-Version: wahrscheilich 3.2.9 von 2017, im Zweifel bitte Roland Meuthen fragen, der hat's installiert.

Schöne Grüße

**Comment by Fasse** [comment]
Admidio sendet nur emails an Felder, die auch als EMAIL-Feld konfiguriert sind. Wenn dies kein Email-Feld ist, dann sollte dahin auch keine Email versendet werden. In der aktuellen Version ist dies auf jeden Fall so.

**Comment by ChristophFranzen** [comment]
Danke für den Hinweis, mir war gar nicht klar, daß das eingestellt werden kann, also daß die Profil-Felder recht frei konfigurierbar sind. Für den Fall, daß das auch anderen passiert, hier die Auflösung: als „Datentyp“ war „E-Mail“ eingestellt, vermutlich, weil die Eingabe-Plausibilitätsprüfung da paßt. Admidio sendet aber an alle Felfer mit diesem Datentypen E-Mails, nicht nur an das „eigentliche“ E-Mail-Feld. Gehe ich recht in der Annahme, daß dieses, welches intern SYS_EMAIL heißt, immer existiert (man kann es nicht aus dem Profil rauslöschen)? Vielleicht sollten E-Mails an die Benutzer dann _nur_ an dieses Feld gehen, wäre mein Verbesserungsvorschlag – im Feld selber dann (falls das nicht schon so ist) die Eingabe einer kommagetrennten Liste zulassen, wie das bei allen gängigen Mail-Programmen auch der Fall ist, um so trotzdem mehrere Adressen zu ernöglichen. Alternativen: 2 Datentypen oder „Datentyp“ und „Funktion“ unterscheiden (letzteres kommt mir am „saubersten“ vor). Ich habe unser Feld nun auf Text(100) umgestellt.

**Comment by Fasse** [comment]
Unter `Einstellungen > Nachrichten` gibt es die Option `Sende E-Mails an alle E-Mail Adressen des Benutzers`. Mit dieser wird gesteuert, ob die Email nur an das Profilfeld "E-Mail" geht oder an alle Email-Felder.
