### ISSUE TITLE
Refactor dates.php

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#109]
The following improvements should be done:

- the different print preview modes should be choosen in a new menu form combobox. There should also be the different html (normal and list) modes listed.
- print and html layout should be generated in the same code list, only with different output cases, just like the list module
- print table should use the bootstrap table look and feel, just like the lists print mode
- print preview should use the default layout with headline and table

**Comment by ximex** [comment]
> print table should use the bootstrap table look and feel, just like the lists print mode

should fix partial #59 that more tables got the zebra style
