### ISSUE TITLE
Open and modify documents online

### ISSUE THREAD

**Issue by afaandujar** [Admidio/admidio#1096]
Good Morning. Is there a way to be able to open and edit documents such as Microsoft Word through admido?
Currently, once I add a document, if I want to edit it, I must download it, modify it, and upload it again.
It would be very comfortable for me and surely for many more people if they could be viewed and edited without having to download those documents.
Thank you.

**Comment by Fasse** [comment]
No that is not possible.

Therefore you must go the way you describe.
