### ISSUE TITLE
Copied and updated event not displaying properly

### ISSUE THREAD

**Issue by bcbrookie** [Admidio/admidio#1103]
**Describe the bug**
The users have created a template event that contains certain information that is updated with further information for each specific event. However when the "master" Event is copied to create Event, if Registration Deadline information is not entered/left blank, the event does not display correctly when showing the Participant list - specifically, if one goes to the Event and chooses the Show Participants option, only the Template's event title and template information in the Description/Info box display- not the updated info - the data entry screen for registration deadline indicate if left blank it should default to the Event Start date?

This behaviour also occurs if a prior Event is copied, as opposed to the use of the Event master template - the problem also appears to arise in some cases, even when Registration Deadline information is entered - it appears that it might have something to do with not blanking out the event dates before entering the desired ones, or the way in which the event dates are entered.

We are using Version 4.04 - problem does not appear to be device/OS/Browser specific
Thanks

**Comment by Fasse** [comment]
@bcbrookie Ich wechsel mal zu deutsch. Ich kann das Problem nicht nachvollziehen bzw. scheine es nicht so richtig zu verstehen. Du hast einen Termin, welchen du kopierst und anschließend gibt es mit dem kopierten Termin Probleme.

Welche Probleme hat der kopierte Termin, welche Infos gehen da verloren bzw. werden falsch kopiert?

**Comment by Fasse** [comment]
Close this bug, because there is no reaction to my question.
