### ISSUE TITLE
Problem Allowing Registrations for an Event

### ISSUE THREAD

**Issue by rlknott** [Admidio/admidio#1109]
I recently installed Admidio v. 4.0.9 and am really liking everything I am seeing. I have been doing some testing to figure out the most efficient way for me to utilize it.

The one problem I have run into so far is that I have a problem allowing me to Enable Registrations for an Event.

I can create an event and save it without any problems. However if I attempt to Enable Registrations for Event, no matter group/role I choose to enter into the Registration Possible For field, as soon as I select to save, I get an HTTP 500 error.

Can someone give me some troubleshooting ideas on what I should be looking for to assist me in resolving this?

I noticed that this only seems to be happening with organizations that I added after the initial one.  When I use the organization that I set up on install, it works fine, but if I add any other organization, I have this problem, regardless of whether I make it a child organization or not.

Wanted to add, here is the error I am getting in my log, but I am logged in as admin, and as far as I can tell I should have access listed:
Got error 'PHP message: PHP Fatal error: Uncaught AdmException: Category of the role could not be set\n because the category is not visible to the current user and current organization. in /home/UserXXXXX/domains/MyDomainXXX.com/public_html/admidio/adm_program/system/classes/TableRoles.php:496\nStack trace:\n#0 /home/UserXXXXX/domains/MyDomainXXX.com/public_html/admidio/adm_program/modules/dates/dates_function.php(485): TableRoles->setValue('rol_cat_id', 8)\n#1 {main}\n thrown in /home/UserXXXXX/domains/MyDomainXXX.com/public_html/admidio/adm_program/system/classes/TableRoles.php on line 496', referer: https://MyDomainXXX.com/admidio/adm_pro ... ine=Events

Thanks so very much!!
Becky

**Comment by Fasse** [comment]
Thanks for the detailed bug description. With this I could fix the problem.

**Comment by rlknott** [comment]
Glad you were able to get it resolved.  Do you have a target date for v4.0.10 release?
