### ISSUE TITLE
Send notification to role

### ISSUE THREAD

**Issue by taker218** [Admidio/admidio#1118]
**Is your feature request related to a problem? Please describe.**
I just installed the 4.1 beta from the github repo and tried the new notification when a new user is created/changed.
This works just fine, but I would like to send the mail not to the same address as the sender mail (which you can configure in the system notification settings).

**Describe the solution you'd like**
It would be nice to either configure a seperate mail-address where notificiations will be sent to or have the ability to send it to a role.

**Describe alternatives you've considered**

**Additional context**
We would be several people with the right to add/change something in the user profile so it would be nice to have a notification sent to the others that there was a change.

**Comment by sielnet** [comment]
I would like to send these notifications to a specific role instead of the administrator.
The administrator is not responsible for new members, guest book entries ....

Allow us to set up a role or an email address directly.
