### ISSUE TITLE
User could send mail to other users although he has no right

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#113]
see forum http://forum.admidio.org/viewtopic.php?f=3&t=6584&sid=18de790f3a1b4eecc8979e040d054469

**Comment by Fasse** [comment]
from forum thread
> Hallo,
>
> also es ist tatsächlich so wie ich es geschildert habe.
Egal ob man Rechte für die Rolle hat oder nicht werden immer alle Benutzer in der Liste zur Verfügung gestellt.
> 
> Das lässt sich auch im Quelltext der message_write.php nachvollziehen.
> 
> Für die Anzeige von Rollen wird in Zeile 344 mit der Funktion "hasRightSendMailToRole()" geprüft, ob die Rolle für den Benutzer angezeigt werden soll.
> 
> In der SQL-Abfrage für die einzelnen Nutzeradressen (Zeile 355 - 393) werden alle E-Mail Adressen und zugehörige Daten aus der Datenbank gelesen und aufgelistet ohne zu prüfen, ob die Adresse zu einer Rolle gehört an die der angemeldete Benutzer eine E-Mail senden darf.
> 
> Ich bin leider nicht so tief in den ganzen Funktionen und Möglichkeiten im Quelltext drin und kann daher gerade auch keinen Lösungsansatz finden.

**Comment by ximex** [comment]
We should not use the short array declaration [...]. It's a PHP 5.4 feature but we still support 5.3. So we should use array(...).
I found it in 3 lines
http://it2.php.net/manual/en/migration54.new-features.php

**Comment by sirnone** [comment]
done with next update... also the TAB/space in #115
