### ISSUE TITLE
Relations use the wrong gender in parent - child relationships

### ISSUE THREAD

**Issue by luebbe** [Admidio/admidio#1130]
Admidio 4.1

**To Reproduce**
1. Create a family with father, mother and boy, girl child
2. Add all possible relations
3. The relations shown for the parent-child always pick the gender of the child, so a father is shown as mother if the child is female

This is the view of a father's relations. The spouse is shown correctly, but the two female children are wrong:
![grafik](https://user-images.githubusercontent.com/3872576/141682256-5b40d348-b47b-4834-b6e6-00c6e7854420.png)

This is the view of one of the children of the same Family. She is incorrectly shown as the "Son" of the "Father"
![grafik](https://user-images.githubusercontent.com/3872576/141682340-9bac450f-e446-460a-9a43-33ac8ca1530e.png)

**Comment by luebbe** [comment]
OK, I think I have understood it now.

When I choose 
* "Person A" 
* "Is parent of" 
* "Person B"

I would expect that the resulting relationship is what I read top down in the list above. 
"Person A is parent of Person B"

The resulting relationship ist just the other way round.
"Person B is parent of Person A"

At least the documentation should be improved for this. I'm not the only one who fell into this trap.

**Comment by Fasse** [comment]
What do you think about something like this? (still need a name for the first box with the user...)
<img width="1035" alt="Bildschirmfoto 2021-11-19 um 23 56 49" src="https://user-images.githubusercontent.com/7038017/142701606-c6c39286-c4e7-4cfa-8d16-ee70d3ae6b48.png">

**Comment by luebbe** [comment]
looks good!
I guess "Relationship" would contain "is parent of, is child of, is spouse of, ..."?
The comboboxes have different styling :)

**Comment by Fasse** [comment]
Relationship contain the values "child, parent" as before ...

Yes I know the styling isn't perfect.  These are two types of comoboxes :(

Do you know a headline for the box around **User**?

**Comment by luebbe** [comment]
Here's a crude copy&paste mockup made from your screen. I think you don't need a header for the user box. Everything can be put into one box without losing anything.

![grafik](https://user-images.githubusercontent.com/3872576/142821559-49acb4fa-d5f5-4e65-8a48-1fecd3fe6613.png)

**Comment by Fasse** [comment]
With your screenshot and without the subheader, we have the same dialog as before. So the misunderstanding will still be there.

**Comment by luebbe** [comment]
The problem for me was not the UI. Intuitively you read the relationship top down, but it is created bottom up. 
As it is now I would see "Paul Schmidt", select "is father of" and "Emil Schmidt" and expect the relationship to be this way.
But the resulting relationship is "Emil Schmidt is father of Paul Schmidt"

If you can't change the algorithm to create the relationship top down, like in the screenshot above, the member and user rows should be swapped. So I select "Emil Schmidt" "son of" "Paul Schmidt" to get the relationship that I want.

**Comment by Fasse** [comment]
Now it looks like this:
![Bildschirmfoto 2021-11-25 um 06 47 10](https://user-images.githubusercontent.com/7038017/143386659-1d5faad6-99b6-404a-8179-47680a8e7350.png)

**Comment by luebbe** [comment]
Looks good!
And now as a proof that it works correctly, please show a screenshot of the resulting relationships from the father's and the child's point of view. :)

**Comment by Fasse** [comment]
![Bildschirmfoto 2021-11-25 um 19 56 09](https://user-images.githubusercontent.com/7038017/143490567-ff200fc0-badb-43cd-8630-cf002b75d743.png)

**Comment by luebbe** [comment]
Now I know that Dagobert is a boy :) which leads me to the following observation:

* The first combo box is "Last name/first name"
* The second combo box is "First name/last name"

Would it be possible to make this consistent? Like a global setting in Admidio which way you prefer?

Not a big deal, but in the "create relationship" UI you distinguish between "member" and "user". Aren't both people in a relationship members or users?

Wouldn't:
* Member
* Relation
* (Selected|Active|Current) member (instead of user)

be more consistent?

**Comment by Fasse** [comment]
Very good notes, I will change that.

**Comment by Fasse** [comment]
Now it looks like this:
![Bildschirmfoto 2021-11-26 um 13 41 28](https://user-images.githubusercontent.com/7038017/143582782-16244493-b7b1-458e-b83c-471bf06e1e2a.png)

**Comment by luebbe** [comment]
It's getting better by the minute :)

There's still the:
- Member: "last name first name"
- Current member: "first name last name"

issue.

Should I create a new ticket for it?

**Comment by Fasse** [comment]
No, I fixed this.
