### ISSUE TITLE
Url within menu entry could be used to execude javascript

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#1138]
This security issue could only be used if you have a valid administrator login. All other users and visitors don't have the right to add new menu entries.

1. Open the https://www.admidio.org/demo_en
2. Log in as administrator
3. Go to https://www.admidio.org/demo_en/adm_program/modules/menu/menu_new.php
4. Fill in the field and pass javascript:alert(document.domain) as the URL value.
5. Click Saved Menu

**Comment by wjddnjs33** [comment]
Thanks for the nice patch. So will a new version be released for this patch?
