### ISSUE TITLE
XSS possible within profile fields that contains urls

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#1144]
When editing your profile, you can create social media links. However, the stored XSS vulnerability using the autofocus and onfocus attributes occurs because the double-quote is not URL-encoded in the input value of the social media link.

1. Open the https://www.admidio.org/demo_en/adm_program/system/login.php and Login as to member
2. Go to "My Profile" -> "Edit Profile"
3. In the FaceBook URL field, type `asdf" autofocus onfocus="alert(document.domain)` and save.
4. Now, whenever an administrator or general user accesses my profile, XSS occurs.

**Comment by wjddnjs33** [comment]
- https://www.huntr.dev/bounties/d3f3ce78-4a30-457d-982e-70d74e68efeb/
- https://www.huntr.dev/bounties/357c5855-1f71-4881-993c-5a3b13da0dd3/

Hello Thank you for patch, And maintainer, can you assign 2 CVEs to the vulnerabilities for the above 2 URLs?

**Comment by wjddnjs33** [comment]
- https://www.huntr.dev/bounties/d3f3ce78-4a30-457d-982e-70d74e68efeb/
- https://www.huntr.dev/bounties/357c5855-1f71-4881-993c-5a3b13da0dd3/

Hello @Fasse . Thank you for patch, And maintainer, can you assign 2 CVEs to the vulnerabilities for the above 2 URLs?
