### ISSUE TITLE
Uncaught Error: Call to a member function error() on null | upgrade | 4.0.12 to 4.1.0

### ISSUE THREAD

**Issue by GaneshKandu** [Admidio/admidio#1145]
**Describe the bug**

I am trying to upgrade from 4.0.12 to 4.1.0 but getting below error when i click on ```update database``` button
```Uncaught Error: Call to a member function error() on null in adm_program/system/classes/ComponentUpdateSteps.php:108```

```
    [type] => 1
    [message] => Uncaught Error: Call to a member function error() on null in /home/soft/public_html/admid66/adm_program/system/classes/ComponentUpdateSteps.php:108
Stack trace:
#0 adm_program/system/classes/ComponentUpdate.php(123): ComponentUpdateSteps::updateStep41MoveEcardTemplates()
#1 adm_program/system/classes/ComponentUpdate.php(161): ComponentUpdate::executeUpdateMethod('ComponentUpdate...')
#2 adm_program/system/classes/ComponentUpdate.php(231): ComponentUpdate->executeStep(Object(SimpleXMLElement))
#3 adm_program/installation/update_functions.php(137): ComponentUpdate->update('4.1.0')
#4 adm_program/installation/update.php(353): doAdmidioUpdate('4.1.0')
#5 {main}
  thrown
    [file] => adm_program/system/classes/ComponentUpdateSteps.php
    [line] => 108
```

**To Reproduce**
[https://www.admidio.org/dokuwiki/doku.php?id=en:2.0:update](https://www.admidio.org/dokuwiki/doku.php?id=en:2.0:update) getting this error on step 8

**Desktop (please complete the following information):**
 - OS: Centos Linux
 - Browser Firefox 95.0.2 (64-bit)
 - Version 4.1.0

**Additional context**

[](https://github.com/Admidio/admidio/blob/737afc5268759f59f49ca5140c2b442bf12720f7/adm_program/system/classes/ComponentUpdateSteps.php#L107)

```global $gLogger;``` is not set in ```updateStep41MoveEcardTemplates()``` function

**Comment by Fasse** [comment]
Could you please replace the unzipped file **ComponentUpdateSteps.php** within `adm_program/system/classes` and try the update after that again.
[ComponentUpdateSteps.php.zip](https://github.com/Admidio/admidio/files/7800806/ComponentUpdateSteps.php.zip)

**Comment by GaneshKandu** [comment]
> Could you please replace the unzipped file **ComponentUpdateSteps.php** within `adm_program/system/classes` and try the update after that again.

still getting same issue

**Comment by Fasse** [comment]
Ok, the `global $gLogger` problem was still there, but this error occurs only if you don't have write access within adm_my_files. Could you check this if there is write access to this folder.

**Comment by GaneshKandu** [comment]
adm_my_files folder is given recursive writable.

**Comment by GaneshKandu** [comment]
I have tested master upgrade is working after refreshing the blank page that came after clicking on update button.
i found issue is 
[adm_program/system/classes/ComponentUpdateSteps.php](https://github.com/Admidio/admidio/blob/e53395eed45f88842687757dafa3efe62d57aebd/adm_program/system/classes/ComponentUpdateSteps.php#L109) is this file array is concatenate with string that causing issue

Uncaught TypeError: Argument 2 passed to Monolog\Logger::error() must be of the type array, string given, called in adm_program/system/classes/ComponentUpdateSteps.php on line 109

otherwise everything works fine
