### ISSUE TITLE
New option to hide former members/roles in email dialog

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#115]
We should add a new preference to the messages module that will handle how we show former members/roles in the email **to** field.

The new preference **Email to former members** should have 3 options:
- Don't show former members
- Only show roles with former members
- Show former members seperatly and within roles

This option must then be used in the module.

**Comment by sirnone** [comment]
Hello Fasse,

can you give me an reason, why we would need the last 2 options? I think we can just make an checkbox "Don't show former members" and it should be OK for 95% of all use-cases.

 I can't find a good reason, to just show roles with former members...

Show former members seperatly and within roles -> can you give me some more information to this?

**Comment by Fasse** [comment]
A checkbox is ok.

**Comment by Fasse** [comment]
I have a little annotation to this :)

Why not call it "Send email to former members" and the default is the flag is set. This is more positive than to prohibit something.
