### ISSUE TITLE
Admidio 4.1.4 throws Fatal error 

### ISSUE THREAD

**Issue by prbt2016** [Admidio/admidio#1189]
**Describe the bug**

Hello,

I was in the process of manual installation of Admidio 4.1.4 on Centos 7 with Apache 2.2.34, PHP 7.2.34, MYSQL 5.5.62.

However I encountered with an issue. After entering all the required database details and admin details . 
On the final step when I click 'Install Admidio' button a  blank page is shown.

However on checking Apache logs the following error is thrown : 

```
[Mon Jan 24 01:12:06 2022] [notice] [client {{IPADDR}}] PHP Notice:  Undefined index: gCurrentOrgId in /{{PATH}}/{{TO}}/{{ADMIDIO}}/adm_program/system/classes/User.php on line 87, referer: http://{{URL}}/{{TO}}{{ADMIDIO}}/adm_program/installation/installation.php?step=create_config

[Mon Jan 24 01:12:07 2022] [error] [client {{IPADDR}}] PHP Fatal error:  Uncaught Error: Call to undefined method TableAccess::getAllEditableCategories() in /{{PATH}}/{{TO}}/{{ADMIDIO}}/adm_program/system/classes/TableRoles.php:412\nStack trace:\n#0 /{{PATH}}/{{TO}}/{{ADMIDIO}}/adm_program/system/classes/Organization.php(243): TableRoles->save()\n#1 /{{PATH}}/{{TO}}/{{ADMIDIO}}/adm_program/installation/install_steps/start_installation.php(239): Organization->createBasicData(2)\n#2 /{{PATH}}/{{TO}}/{{ADMIDIO}}/adm_program/installation/installation.php(162): require_once('/{{PATH}}/{{TO}}/{{ADMIDIO}}...')\n#3 {main}\n  thrown in /{{PATH}}/{{TO}}/{{ADMIDIO}}/adm_program/system/classes/TableRoles.php on line 412, referer: http://{{URL}}/{{TO}}{{ADMIDIO}}/adm_program/installation/installation.php?step=create_config
```
What could be the cause of this issue ?.

**To Reproduce**
1. Hit installation URL
2. Enter database access details , organization details , admin details.
3. Click on 'Install Admidio' button
4. Blank page shown but fatal error is thrown under Apache logs.

**Expected behavior**

Admidio installation should be successful.

**Desktop (please complete the following information):**

 - OS: CentOS Linux release 7.6.1810 (Core)
 - Browser : Mozilla Firefox
 - Version : 96.0.2

Could you please try to replicate this issue at your end and fix this?.

**Comment by Fasse** [comment]
Thanks for the detailed report. 
Will be fixed in 4.1.5

**Comment by prbt2016** [comment]
Hello @Fasse,

Thanks a lot for checking into the issue. Kindly notify when you release 4.1.5.

Regards.

**Comment by Fasse** [comment]
@prbt2016 Admidio 4.1.5 is released :-)

**Comment by prbt2016** [comment]
Thanks . Checked . It's working fine.
