### ISSUE TITLE
Disable specific system notifications

### ISSUE THREAD

**Issue by rajanski** [Admidio/admidio#1196]
**Is your feature request related to a problem? Please describe.**
We need a way to toggle individual system emails, specifically those going out to non-admins. 
Specifically we need to disable the sending of emails to a user when his registration has been rejected.

As of now there is only the possibility to disable ALL system notifications, and not only individual ones.

**Describe the solution you'd like**
I want a checkbox on all of the individual  system notifications, which just enables or disables them.

**Describe alternatives you've considered**
A workaround would be able to just "drop" pending registrations, i.e. delete them without registering or refusing to register

**Comment by Fasse** [comment]
System notifications are only sent to the users who must be informed. Can you please describe which system notification is sent to a registration and should not be sent to that registration?

**Comment by rajanski** [comment]
well there is a thing called "Systembenachrichtigungen" as shown i below  screenshot, that also deals with notifications sent to non-admin users after sucessful registration:

**Comment by rajanski** [comment]
I would like a checkbox next to each of these boxes to enable/disable these messages

**Comment by idnovic** [comment]
I would like to second this. 
We use the "Online-Beitrittserklärung " and some users are confused. 
They set up the same registration a second time. 

If I delete the first registration and accept the second registration the user gets the following emails:

1. registration denied
2. 2. registration accepted

**Comment by rajanski** [comment]
> I would like to second this. We use the "Online-Beitrittserklärung " and some users are confused. They set up the same registration a second time.
> 
> If I delete the first registration and accept the second registration the user gets the following emails:
> 
> 1. registration denied
> 2. registration accepted

Exactly this behaviour is confusing to our users too

**Comment by Fasse** [comment]
Within version 4.3 it would be possible to leave the textbox for a system notification blank. In this case the notifification will not be sent.
