### ISSUE TITLE
New columns suddenly appears in list view

### ISSUE THREAD

**Issue by jroselarsen** [Admidio/admidio#1212]
**Describe the bug**
Member list problem, after uodate to version 4.1.7.
Normally there is a number and then the selected columns on the list of members.
Now, after the latest update, a new column has appeared as the first one "Groups".
Showing for each member, the NUMBER, not the group.
In the number field, which is now the second one, now contains the group name.

Example attached, columns are in Danish.

**To Reproduce**
List members in a group.

**Screenshots**
added

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser Chrome, Version 98.0.4758.82

**Smartphone (please complete the following information):**
n/a

Expected behavior is showing the nr and then the selected columns for the list.
![image](https://user-images.githubusercontent.com/17494022/153264276-b95bd833-dde8-4e65-9a93-b81c2c337a57.png)

I have another site just updated, and it does exactly the same.
BR Johnny

**Comment by Fasse** [comment]
The wrong column description for the number is fixed with my commits to this issue.

But that you will see also the group name is a problem with a missing update of the **adm_program/libs/client** folder.
Can you check if this is up to date.

**Comment by jroselarsen** [comment]
You are quite right. The update of adm_program was wrong. I've not updated to the correct version.
And the number column is named Groups (Grupper)
![image](https://user-images.githubusercontent.com/17494022/153362574-a8b692c1-effe-43fa-b662-cd40d98d2fa5.png)
Thanks for the prompt reply.

**Comment by Fasse** [comment]
Ok, than I can close that issue.
