### ISSUE TITLE
Guestbook hide email address

### ISSUE THREAD

**Issue by sielnet** [Admidio/admidio#1214]
**Is your feature request related to a problem? Please describe.**
The guestbook leaks the email address of the creator.

**Describe the solution you'd like**
Add an option in the guestbook setings to hide the email address from the public aka not loged in users.

**Describe alternatives you've considered**
No alternative.

**Additional context**
When a user or guest adds an entry to the guest book, they may add their email address in the form.
For logged in users, the email addres is automatically added.

This is unwise, let me hide the email addresses in the guestbook from the settings page.

**Comment by idnovic** [comment]
(private account)
Okay that makes sense. 
I will fir our use case fork the module and remove the email address from the form.
