### ISSUE TITLE
Photos have dotted line in the middle on hover

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#123]
If you go with the mouse over a photo than you will see a dotted line. This is because of the link. We should hide this line just for the photos in the photo module.
@ximex you made a patch for the lib but they won't accept it. So we can add the css to our **admidio.css*.

**Comment by ximex** [comment]
i think you mean this: https://github.com/ashleydw/lightbox/issues/121

**Comment by Fasse** [comment]
Yes :)

**Comment by ximex** [comment]
you mean that i should only put this in admidio.css:

```css
.ekko-lightbox-nav-overlay a {
  outline: none;
}
```

**Comment by Fasse** [comment]
If this is the fix than add it. I only remember that you had a fix for the problem and because of this I open this issue.

**Comment by ximex** [comment]
fixed https://github.com/Admidio/admidio/commit/d99fcd6da74514a860c193dda735597a4418c1db
