### ISSUE TITLE
Add new option for default list configuration of event participation lists

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#126]
We should add a new preference to the events preferences where you can select a list configuration. This list configuration will be the default configuration that will be shown if you click on a participation list.
##

**Comment by ximex** [comment]
http://forum.admidio.org/viewtopic.php?f=2&t=6611

**Comment by thomas-rcv** [comment]
Will catch this issue within the date module enhancements because I need a solution how to show up new member states feature in participation list. By the way I´ll create a new list configuration using as standard for participation
