### ISSUE TITLE
Search in Members module is flawed

### ISSUE THREAD

**Issue by jonathanbromley** [Admidio/admidio#1273]
**Describe the bug**
In the Members module, Search can give misleading results because the search string can match across column (field) boundaries. For example, if a member has surname "Thomas" and firstname "Howard", searching for "ash" will match that member.

This occurs because in file **members_data.php** the $searchCondition is constructed by concatenating column values, without any intervening separator.

**To Reproduce**
1. In Preferences for Members module, select the default **Members** list configuration which has surname and firstname as two consecutive columns.
2. Go to **Members** module. Enter a search string that is the last two letters of a surname and the first two letters of the corresponding firstname.
3. Note that the search yields an inappropriate hit, as indicated in the example in bug description above.

**Expected behavior**
Search hits should occur only within a single column.

**Admidio version:**
  - Admidio version 4.1.4
  - MySQL version 5.7.38

**Proposed fix**
 - In file **modules/members/members_data.php** line **108** change $searchCondition to include spaces between column values:
`$searchCondition .= ' AND CONCAT(' . implode(", ' ',", $searchColumns) . ') LIKE \'%'.$searchWord.'%\' ';`

**Comment by Fasse** [comment]
@jonathanbromley Thank you very much for this bug report with the posible solution.
