### ISSUE TITLE
In the Guestbook title, special HTML entities are displayed raw

### ISSUE THREAD

**Issue by olaxe** [Admidio/admidio#1278]
**Describe the bug**
In the translated French version of Guestbook, the HTML entity &rsquo; is displayed

**To Reproduce**
1. Switch in French
2. Click on (https://ceremonies.mansionis.com/adm_program/modules/guestbook/guestbook.php)
3. Look at the title

**Expected behavior**
make either a closed single quotation mark or an apostrophe in the title if needed

**Screenshots**
![Capture d’écran_2022-05-29_10-18-23](https://user-images.githubusercontent.com/25513656/170858937-6b94e88a-3484-40e1-99d6-9b3d1946f9f6.png)

**Desktop (please complete the following information):**
 - OS: Linux Twister
 - Browser Chromium
 - Version 92.0.4515.98

**Comment by Fasse** [comment]
Thanks for the bug report. This will be fixed within the next release.
