### ISSUE TITLE
Generic Login Error Message

### ISSUE THREAD

**Issue by ximex** [Admidio/admidio#128]
We should change the behavior of the printed error messages at the login process.

Today:
- **username found, password correct, activated:** do login
- **username found, password correct, not activated:** not activated message
- **username found, password false, activated:** false password message
- **username found, password false, not activated:** not activated message
- **username not found:** not found message

Should change to:
- **username found, password correct, activated:** do login
- **username found, password correct, not activated:** not activated message
- **username found, password false, activated:** Login incorrect (username OR password)
- **username found, password false, not activated:** Login incorrect (username OR password)
- **username not found:** Login incorrect (username OR password)

We shouldn't give an attacker infos about if a username exists e.g.
This way is the common secure way

**Comment by ximex** [comment]
it looks if this all has to be done in "login_check.php"

**Comment by Fasse** [comment]
+1 this should be done!

**Comment by ximex** [comment]
also change the case insensive username checking to a case sensitive check.
`WHERE UPPER(usr_login_name) LIKE UPPER(\''.$loginname.'\')`
to
`WHERE usr_login_name LIKE \''.$loginname.'\'`

**Comment by ximex** [comment]
And PLEASE use **Joins**!!!
the code looks like as it really needs a rewrite ;-)

**Comment by sistlind** [comment]
I think usernames should not case sensitive, there is not much security improvement, but it can be complicated, if there are several users differing only in case. Often people using their email and this is also not case-sensitive.

Perhaps the better way is to allow only lowercase usernames at all.

**Comment by Fasse** [comment]
The username should not be case sensitiv. This is easier for users to register.

**Comment by ximex** [comment]
> The username should not be case sensitiv.
ok

**Comment by Fasse** [comment]
@ximex do you implement this?

**Comment by ximex** [comment]
if i found time for this yes. shouldn't be that hard

**Comment by Fasse** [comment]
The release of 3.1 is "far" away ;)

**Comment by ximex** [comment]
first part done: 42dbd836773b33fb5aa3c0dd8811269cd333c1af

**Comment by ximex** [comment]
Flow should be:
1. check input (not empty)
2. find user
3. check password
4. check if activated

**Comment by ximex** [comment]
ok we have to look at other things too:
is the user currently a member of valid role?
What should we do if:
- username & password correct & activated, currently member of invalid role
- username & password correct & activated, was/will be (set for in future) member of a valid role
- username & password correct & activated, isn't a member of any role

I think "Login incorrect (username OR password)" is wrong in all 3 possibilities

**Comment by ximex** [comment]
I'm nearly finished with the code. Now i have to change the code for the update login. The other things work. I used "Anmeldedaten korrekt, jedoch ist dieser User aktuell kein gültiges Mitglied einer Organisation." for all 3 possibilities from the last message.

**Comment by ximex** [comment]
@Fasse please check

**Comment by Fasse** [comment]
looks good to me, some basic checks were ok.
