### ISSUE TITLE
File Upload for photos uploads only every second file

### ISSUE THREAD

**Issue by bembi64** [Admidio/admidio#1295]
Admidio 4.1.13
Browser: MS Edge (up to date)

Description
If you create a photo library and upload photos, only every second file is uploaded and shown in the photo gallery.

Reproduction:
I created a root photoalbum and a sub-photoalbum (start date 2021-12-04)
Inside the sub-fotoalbum I selected 69 file for upload.
The first time I selected 69 files for upload. (starting with 2177)
Every second file (2178m, 2180 ...)was uploaded.
35 files uploaded into the folder structure on the server (photos\2021-12-04_x)

The second time I selected the same 69 files  (starting with 2177) and then every second file (2177, 2179) is uploaded.
The folder now contain 69 files

As the picture name are uploaded with the original file name (/Upload), but then in the folderstructure with a subsequent numebering (1,2,3,4...), it is first not possible to find out, which files are missing and second the folder the sequence (sorting) is not as expected. 

Expected behaviour. 
- All selected files are uploaded as selected. 
- An advantage would be to keep the original file names. This makes it even possible to change the order or to easily find out the missing files. 
![PhotoUpload](https://user-images.githubusercontent.com/91702333/183299299-14d74b6a-b7a2-4028-960a-57d378a42885.PNG)

**Comment by Fasse** [comment]
I have tried to reproduce that problem but within my installation all photos were uploaded. I have no idea why you have this strange behavior that every second photo will not be uploaded. 

Do you have an upload limit set within PHP that will make this problems?

**Comment by bembi64** [comment]
Hello Fasse, 
let me provide what I have

![image](https://user-images.githubusercontent.com/91702333/183757189-4226d9f8-237c-4b08-995d-52a2203c346b.png)

Admidio is installed on my provider webspace and more or less with default php settings and extensions.
Nothing what I can see with the exception of the 32 MB upload limit. 
If your are interested in special segments of the phpini, please let me know, I will post them. 

The pictures are reduced to 1536 px max / 90% with a file size of around 300 KB each. 
I also tried to upload single files or smaller bunches, exacly the same effect. 
Sometimes the first file fails other times not, and dependent from the first file, I get an even or an od sequence. 
All files have a sequenced number IMG_2177.jpg, 78,79,80 etc.

I digged a bit in the code and have seen, that photos and documents are using the same library. So tried to upload the same fotos to a document folder and there all files are uploaded fine. 

The difference is, that fotos are rendered, documents not. So observed the upload folder via FTP but see there the same sequence there. 

Some more Admidio settings:
Scaling for upload 1536
Max picture size 1024 / 1024
Preview 240
Picture text: yes (but I dont see this text anywhere)
Picture text size 30
Save originals: yes

Also created now a new album, selected 6 of the larger original, and I get...
First file is skipped, and then file 2,4,6
![image](https://user-images.githubusercontent.com/91702333/183762484-6e0921a4-a623-49ea-8619-e56cf9df018c.png)

**Comment by Fasse** [comment]
This sounds more strange. Have you tested this behavior with different browsers? 
Could you try to reproduce this on our demo site? Only for testing. You could delete the photos immediately,

**Comment by bembi64** [comment]
I took some other fotos in a number sequence...
On the  Demo-Platform...
Nothing was uploaded...

![image](https://user-images.githubusercontent.com/91702333/184217823-9fee8d37-d376-4168-bbe2-578fb447388b.png)


On my platform (same fotos):
Every second 
![image](https://user-images.githubusercontent.com/91702333/184218008-83d409b2-a75b-410c-9b46-1c0b24267be4.png)

**Comment by bembi64** [comment]
Hi all,
I guess I found someting...
My provider offers different CGI Versions
CGI and  FPM/FASTCGI
7.4, 8.0, 8.1

With FPM/FASTCGI, Fotos doesn't work at all
With CGI 8.0, 8.1 I have the effect with every second picture'
With CGI 7.4 it look to work...

So the issue seems to be with the CGI Version, that the Foto Gallery doesn't fully comply with th CGI 8.x specs.

**Comment by Fasse** [comment]
Thank you for this Information. I will have a look at it.

**Comment by bembi64** [comment]
At least I can confirm that.
playground works (all photos uploaded)
demo_en (none of the photos uploaded)
I compared the php.info on both, can not see an essential difference...
Pathname is different, possibly permissions on the folders? Looks like two installations based on the same database?
As I cannot upload anything on the demo_en, it need not neccessarily the same issue. 
In my case, every sencond picture is uploaded, and it behaves different dependend from the php version.
If I select FastCGI on my server, no upload is possible (all php versions), but I will check this again as somethimes the caching may influences the results.

**Comment by bembi64** [comment]
I changed my php from CGI 7.4.30 to FPM/Fastcgi 7.4.30
Now I get the message "upload aborted" for every single photo.
Uploading the same photo into a Document folder works.

**Comment by Fasse** [comment]
The problem at our demo sites is now fixed. With the last update I forgot some files of the new version. Now the upload works for photos and documents. 

I still have no idea why it won't work within your installation :-(

**Comment by Fasse** [comment]
@bembi64 Do you still have these problems?

**Comment by bembi64** [comment]
Hello Fasse,
just upgraded fom 4.1.18 to 4.2.2
PHP is currently 8.1.15
GCI and FastCGI same behavior.

17 of 27 files are uploaded...
In the log file I see
[LOG_2023_03_01.txt](https://github.com/Admidio/admidio/files/10866194/LOG_2023_03_01.txt)

But these are the files which are uploaded. 
The first 6 and then every second is missing.

In the pictures root directory I see 17 files (1-17.jpg)
In the "original" folder 17 files (1-17.jpg)
In the "thumbnails" folder  17 files (1-17.jpg)

Deleted all files from the GUI
Deleted the complete folder for this album.
Uploaded all files again...
Now I have 13 Fotos visible on the GUI (every second)
In the photo folder I see 14 files (root, original) and 13 files (thumbnails)

Photos in the root folder and thumbnail folder are the same, but 14.jpg is only in the root folder
The original folder contains exactly the 13 missing photos plus the 14.jpg.
The 14.jpg is in the root folder ase well as in the original folder.
The 14.jpg is the last file in the upload sequence.


From my feeling, there is possibly an error in the renaming of the files (numbering)?
Why don't you not just keep the original file name? Simplifies to compare the content, if you just want to add additional files.

**Comment by Fasse** [comment]
Thanks for the detailed report. I have tried something within my installation and I could reproduce this behavior if I active "store original photos". Could you confirm that this only occurs if you store original photos?

**Comment by Fasse** [comment]
Could you please replace this file within your installation in folder `adm_program/system/classes`:
https://raw.githubusercontent.com/Admidio/admidio/7d15500c28331565bd8aa3b68aed8acf8d66d96b/adm_program/system/classes/Image.php

**Comment by Fasse** [comment]
For me this fix work. Please confirm this if we have released version 4.2.4 and you have updated.

**Comment by bembi64** [comment]
Hello Fasse,
this looks good...
27 files uploaded, all 27 files there and the file numbering is equal in all three folders: photo_root, originals and thumbnails.
