### ISSUE TITLE
Change Foreign Key from org_shortname to org_id

### ISSUE THREAD

**Issue by ximex** [Admidio/admidio#130]
Change the foreign key constraint from `adm_organization->ogr_shortname` to `adm_announcements->ann_org_shortname` and `adm_photos->pho_org_shortname` to a constraint with the `org_id` instead of the `org_shortname`

So the `org_shortname` could get changed in the future.

**Comment by ximex** [comment]
http://admidio.org/forum/viewtopic.php?f=3&t=5595&p=22168#p22168
So it isn't possible to change the shortname without a new installation or many some sql statements

**Comment by Fasse** [comment]
Yep, this is still a relict from Former times.

**Comment by Fasse** [comment]
Please only add next milestone if you have a developer add who do this in the timeframe of this Release.

**Comment by ximex** [comment]
merged
