### ISSUE TITLE
After installation, unable to login with administrator credentials, "Your login data were correct but you are not an active member of this organization"

### ISSUE THREAD

**Issue by kylebial0** [Admidio/admidio#1302]
After the initial installation of Admidio, I am unable to login to the organization that was created. When I attempt logging in with the credentials created during installation, I receive the error "Your login data were correct but you are not an active member of this organization."

I have made sure the credentials are correct, reinstalling the software, and re-creating the mysql database.

I can confirm there have been tables made in the database, so it appears the installation completed successfully.

Anyone have any ideas on how to correct this issue?

**Comment by kylebial0** [comment]
Update: After downgrading to 4.1.1.3, I am no longer having this issue.

**Comment by Fasse** [comment]
Hmm that is strange. I tested it with 4.1.14 and I could login with the user I created during installation.

**Comment by kylebial0** [comment]
After further playing around, I found this was only an issue while cloning the master repo.

I could have been doing something wrong, but I had no issue when downloading the tarball for releases 4.1.13 and 4.1.14.

For research purposes, I am running Ubuntu 22.04 and hosting using Apache2.

**Comment by vmindru** [comment]
Same here deployed from `admidio/admidio:latest `

**Comment by vmindru** [comment]
using PSQL

**Comment by Fasse** [comment]
The reason is the same as the bug report from @vmindru  and will be fixed with the some commit of #1305

**Comment by zharfanw** [comment]
For solving it, i just bypass the requirements of isMemberOfOrganization() function by remove mem_begin/mem_end. 
![image](https://github.com/Admidio/admidio/assets/12560478/9258950d-a848-4b40-969d-e12dc4280ad0)

idk, why? 
maybe it required like quotation mark("") on query syntax(on Mysql database) 
![image](https://github.com/Admidio/admidio/assets/12560478/3e898993-9ae7-4765-8581-47d4126eb23e)
without it, it will return nothing.

but when i add quotation mark("") in php file, there's no respond on website.

My DB engine:
Server type: MariaDB
Server version: 10.6.14-MariaDB-cll-lve - MariaDB Server
Protocol version: 10
Database client version: libmysql - mysqlnd 8.1.16
PHP extension: mysqli Documentation curl Documentation mbstring Documentation
PHP version: 8.1.16
