### ISSUE TITLE
Understandment Questions to Smarty integration

### ISSUE THREAD

**Issue by Galileon-venta** [Admidio/admidio#1304]
Admidio utilizes Smarty but only for parts of the Views... thereby theme customization provides only restricted possibilies to change the display of the different Module views.

Why is the design like that?

Question also applies for the language files... shouldnt it be possible to tweak them via a theme and not by changing the "core" Code?

**Comment by Fasse** [comment]
That is because of the history of Admidio. First we don't had any theme customizition. Later we added it and implement it, were it was easy. If I would start new with Admidio I would implement a better more integrated way of Smarty. 

But if there is time or someone who want's to push the integration of Smarty, it would be very nice.

**Comment by Galileon-venta** [comment]
I did not do PHP for a longer time now and yet I have problems to find my way thru the Sourcecode but ill keep this in Mind and may encouple parts into the theme.

**Comment by Fasse** [comment]
Please start with small parts so we can have a view how this could be best implemented. Later we can than add more parts.

**Comment by marchorst** [comment]
Hey all, I have started to do this as well.
My idea is to extend the "HtmlElement extends \Smarty" and add a Render Method in it:
```
public function render($templateName, $asigns) {
        global $gL10n;
        foreach($asigns as $key => $asign) {
            $this->assign($key, $asign);
        }

        $this->assign("ADMIDIO_URL", ADMIDIO_URL);
        $this->assign("FOLDER_LIBS_SERVER", FOLDER_LIBS_SERVER);
        $this->assign("data", $asigns);
       
        $this->assign('l10n', $gL10n);
        return $this->fetch("sys-template-parts/".$templateName.'.tpl');
    }
```

I have started with a HTMLForm part for testing which would look like this:
```
public function addInput($id, $label, $value, array $options = array())
    {
...
  $optionsAll["attributes"] = $attributes;
        $this->addHtml($this->render("form.input", $optionsAll));
    }
```

So at the end we are just calling all the "add*" Methods as they are for now, but we will render all that stuff in a Smarty template.

What do you think about that idea?
I have committed this to my fork:
https://github.com/marchorst/admidio/commit/989b5f228f01c80edadb85e9ed51f3dfdc5949d4

**Comment by Galileon-venta** [comment]
For me that looks like an implementation of my basic theoretical idea to aproach this; it does not change that much of the logic while uncoupling the template parts

**Comment by marchorst** [comment]
Would be great if you could also check which parts I have missed so far @Galileon-venta 
Thanks,
Marc

**Comment by Fasse** [comment]
@marchorst Thank you very much for the implementation of the form templates. I have done some further fixes to the implementation.

Do you plan further smarty integration? Maybe we should try that the HtmlForm class will be directly from the Smarty class. Now its from the deprecated HtmlFormBasis class, which we want to eleminate.

**Comment by marchorst** [comment]
I can definitely take a look on this and start further development, but I will not have the time in the next one or two month

**Comment by Fasse** [comment]
Another step was done. #1378 
Within Admidio 4.3 you can customize the menus even better with Smarty templates.

**Comment by marchorst** [comment]
> @marchorst Thank you very much for the implementation of the form templates. I have done some further fixes to the implementation.
> 
> Do you plan further smarty integration? Maybe we should try that the HtmlForm class will be directly from the Smarty class. Now its from the deprecated HtmlFormBasis class, which we want to eleminate.

I think HtmlForm extends HtmlFormBasic, which is in fact not not used by any other core component as far as I can see this.
I would suggest that I migrate these to classes. We would then end up with HtmlForm which extends HtmlElement (And this is extending smarty) + mark the HtmlElementBasic as deprecated (I am pretty sure there are some Plugins which use this class)
Any other thoughts on this?

**Comment by Fasse** [comment]
Why not ignore HtmlElement and extend Smarty to HtmlForm. 

The structure of HtmlElemnt, HtmlTable, HtmlList ... is old and I want not generate the Html structure in PHP. Therefore we have now Smarty. So we should directly genereate Smarty templates out of the HtmlForm class. Maybe we can remove the other classes in future if there are more things migrated to Smarty templates.

**Comment by marchorst** [comment]
Understand! Yes makes sense - I will take a deeper look on this.

**Comment by Fasse** [comment]
@marchorst What do you think, is it better to separate the menu parts in separate files and include that files within the index.tpl or should it still be part of the index.tpl ?

**Comment by marchorst** [comment]
Makes definitly sense to split up the UI components a bit :)

**Comment by Fasse** [comment]
I implemented the last missing form objects (select and static) and removed the HtmlFormBasic class.

**Comment by Fasse** [comment]
I will close this issue because the question was answered and main parts are now customizable via Smarty.
