### ISSUE TITLE
Messages Modul - Answer to group + original sender

### ISSUE THREAD

**Issue by idnovic** [Admidio/admidio#1315]
**Is your feature request related to a problem? Please describe.**
We have set up multiple groups/roles.
User1 sends a message to groupA. 
User2 (member of groupA) opens the message in admidio.
User2 is not directly able to answer the original sender and the other members of groupA. 

**Describe the solution you'd like**
Add a button "answer to group and sender". 
This button prefills the To form field with the group/role and the original sender. 

**Describe alternatives you've considered**
Add an option to add all members of groupA and the original sender to the answer-to field in the send email. The option is activated by group/role settings. If enabled the answer-to field is prefilled as described. This would allow group members to answer with their email client but this would not solve the problem in admidio itself. 

**Additional context**
The Problem is that members of a group would like to be able to answer messages to the original sender AND the other members of the same group should also receive the answer. 

User1 ask a question per message to groupA. 
User2 (member of groupA) answers the message to the group and the original sender. 
User1 receives the answer and is happy. 
User3 (member of groupA) sees the answer from User2 to User1 because the message was also send back to groupA. 

Plus: Thread view for messages. User3 should be able to view the original message from user1 and the answer from user2 to user1. 

I think the last part would only be possible if messages are grouped by subject/message-id.

**Comment by Fasse** [comment]
I did not understand your feature request. Until now it's not possible to send a PM to a group. You can only send an email to a group. But an email could not be open in Admidio by the recipient, so there is no need to answer to this email within Admidio.
