### ISSUE TITLE
Call to undefined function disk_total_space

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#1324]
On some webspaces the function disk_total_space is deactivated. We should check this and don't call that function.

`Fatal error: Uncaught Error: Call to undefined function disk_total_space() in /admidio/adm_program/system/classes/FileSystemUtils.php:702](http://admidio/adm_program/system/classes/FileSystemUtils.php:702) Stack trace: #0 /customers/8/0/1/[/admidio/adm_program/modules/preferences/preferences.php](http://admidio/adm_program/modules/preferences/preferences.php)(944): FileSystemUtils::getDiskSpace() #1 {main} thrown in /customers/8/0/1/[admidio/adm_program/system/classes/FileSystemUtils.php](http://admidio/adm_program/system/classes/FileSystemUtils.php) on line 702`

**Comment by priyamsantoki** [comment]
Fatal error: Uncaught Error: Call to undefined function mysql_select_from() in C:\xampp\htdocs\menual star .php:30 Stack trace: #0 {main} thrown in C:\xampp\htdocs\menual\star .php on line 30

**Comment by priyamsantoki** [comment]
![github](https://user-images.githubusercontent.com/112793921/201469394-2d15b091-3247-4a04-b21c-1383cd6fe9bc.png)

**Comment by Fasse** [comment]
@priyamsantoki you have posted in the wrong project!
