### ISSUE TITLE
Docker startup.sh Changing Database Settings in config.php Unexpectedly

### ISSUE THREAD

**Issue by andshrew** [Admidio/admidio#1347]
**Describe the bug**

If you deploy via Docker [following the basic instructions](https://github.com/Admidio/admidio/blob/master/README-Docker.md) of creating 1 MariaDB container and 1 admidio container then `startup.sh` appears to overwrite your database settings in `config.php` each time you start the admidio container - unless you supply your database settings as environment variables to that container.
https://github.com/Admidio/admidio/blob/master/dockerscripts/startup.sh

**Additional context**
The documentation suggests that the environment variables are an optional way to configure the container.

https://github.com/Admidio/admidio/blob/3ce77678c1b9cb318c4a26edabcd29ae38290d06/dockerscripts/startup.sh#L96
This line and the ones which follow use a logic such that if the environment variable does not exist then it will replace your database, username and password with default values.

https://github.com/Admidio/admidio/blob/3ce77678c1b9cb318c4a26edabcd29ae38290d06/dockerscripts/startup.sh#L81
With the hostname a slightly different logic is being applied, but ultimately it is replaced with localhost if you do not supply the environment variable.

Is it intended that you should always pass these environment variables into the admidio container? If it is then the bug is that the documentation should be updated to indicate that this is the case.

If it's not intended then I think the `startup.sh` requires a review to make sure that it is only updating these values if they've been passed as an environment variable into the container.

**To Reproduce**
1. Create a new installation [following the basic instructions](https://github.com/Admidio/admidio/blob/master/README-Docker.md) for deploying the application via Docker:
Creating MariaDB container with:
```
docker run --detach -it --name "Admidio-MariaDB" \
  -p 3306:3306 \
  --restart="unless-stopped" \
  -v "Admidio-MariaDB-confd:/etc/mysql/conf.d" \
  -v "Admidio-MariaDB-data:/var/lib/mysql" \
  -e MYSQL_DATABASE="admidio" \
  -e MYSQL_ROOT_PASSWORD="my_VerySecureRootPassword.01" \
  -e MYSQL_USER="admidio" \
  -e MYSQL_PASSWORD="my_VerySecureAdmidioUserPassword.01" \
  mariadb:latest
```

Creating admidio container with:
```
docker run --detach -it --name "Admidio" \
  -p 8080:8080 \
  --restart="unless-stopped" \
  -v "Admidio-files:/opt/app-root/src/adm_my_files" \
  -v "Admidio-themes:/opt/app-root/src/adm_themes" \
  -v "Admidio-plugins:/opt/app-root/src/adm_plugins" \
  --link "Admidio-MariaDB:mysql" \
  admidio/admidio:latest
```
3. Complete initial application setup.
4. Stop the admidio container.
5. Start the admidio container.
6. Accessing the site via a browser will display:
```
SQLSTATE[HY000] [2002] No such file or directory
```
The log files within the container shows:
```
[2023-01-24 13:24:16.429635] Admidio.ALERT: DATABASE: Could not connect to Database! EXCEPTION MSG: SQLSTATE[HY000] [2002] No such file or directory {"engine":"mysql","host":"localhost","port":null,"dbName":"admidio","username":"admidio","password":"******","options":[]} {"file":"/opt/app-root/src/adm_program/system/classes/Database.php","line":232,"class":"Database","function":"connect"}
```
The database settings in `/opt/app-root/src/adm_my_files/config.php` have been reset to:

```
$g_adm_srv = 'localhost';
$g_adm_port = null;
$g_adm_db = 'admidio';
$g_adm_usr = 'admidio';
$g_adm_pw = 'admidio';
```

**Expected behavior**
Server settings should be retained between restarts of the container.

**Additional Info**
Using admidio/admidio:latest
Digest: sha256:6fcd129e12d1eb21351cc12bdb4a8eb773de3433adfb77699c722d4b30a04f3a

**Comment by schast** [comment]
the documentation has been updated.
see https://github.com/Admidio/admidio/blob/v4.2/README-Docker.md
