### ISSUE TITLE
Message can´t be sent: Argument 2 passed to Email::addRecipient() must be of the type string

### ISSUE THREAD

**Issue by benhartwich** [Admidio/admidio#1369]
**Describe the bug**
It seems that an announcement mail can´t be sent to a specific user group if there are some entries with missing mail addresses. 

**Expected behavior**
A missing mail address should be skipped. An error should be shown, which describes incorrect mail addresses / entries. 

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome

**Additional context**
This php error occurs, when we hit send at the message module by using a specific user list:
`"PHP message: PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Email::addRecipient() must be of the type string, null given, called in /var/www/verwaltung/htdocs/admidio/adm_program/system/classes/Email.php on line 268 and defined in /var/www/verwaltung/htdocs/admidio/adm_program/system/classes/Email.php:165
Stack trace:
#0 /var/www/verwaltung/htdocs/admidio/adm_program/system/classes/Email.php(268): Email->addRecipient()
#1 /var/www/verwaltung/htdocs/admidio/adm_program/modules/messages/messages_send.php(202): Email->addRecipientsByRole()
#2 {main}
  thrown in /var/www/verwaltung/htdocs/admidio/adm_program/system/classes/Email.php on line 165" while reading response header from upstream, server: verwaltung.xy.at, request: "POST /adm_program/modules/messages/messages_send.php HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm-verwaltung.sock:", host: "verwaltung.xy.at", referrer: "https://verwaltung.xy.at/adm_program/modules/messages/messages_write.php?role_uuid=2dcfeb6d-b707-4b3f-b50c-8c321cc3f793"
`

**Comment by Fasse** [comment]
@benhartwich The error message from you is not about the email address, it's about the firstname. Do you have members without firstname?

**Comment by benhartwich** [comment]
Yes, some members are organisation entries.

**Comment by Fasse** [comment]
Ok, that's an unexpected dataset because firstname is a required field. But I will have a look if the function could be more tolerant.

**Comment by Fasse** [comment]
Could you implement my changes to your installation and try it again?

**Comment by benhartwich** [comment]
Yes, sure.
