### ISSUE TITLE
Apostrophe in Category Report showing HTML code, should use an actual apostrophe

### ISSUE THREAD

**Issue by Rvice** [Admidio/admidio#1373]
**Describe the bug**
In my export I have last name like "O'Brien" and in the export I'm seeing "`O&apos;Brien`", I expect to see it in the CSV correctly. Given the CSV export is using quote (") wrapped parameters, a single apostrophe can be in the export.

**To Reproduce**
1. Create a member with the last name O'Brien
2. Go to Category Report and export with last names
    1. https://www.admidio.org/demo_en/adm_program/modules/category-report/category_report.php 
4. Download CVS
5. Observe `"O&apos;"Brien"` in the export

**Expected behavior**
I expect to see "O'Brien" in the example above. I expect to see it as I do in this member record
https://www.admidio.org/demo_en/adm_program/modules/profile/profile.php?user_uuid=c956b833-55ec-428d-9152-a5c35db1276e

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 110.0.5481.178 (Official Build) (64-bit)

**Additional context**
N/A

**Comment by Fasse** [comment]
Which version of Admidio are you using?

**Comment by Rvice** [comment]
4.2.2, apologies.

**Comment by Fasse** [comment]
Hmm, I could not reproduce that behavior. Could you please try to reproduce this at our demo page?

**Comment by Rvice** [comment]
Sure, example is here
https://www.admidio.org/demo_en/adm_program/modules/category-report/category_report.php

Look for Jason and you'll see the html code, and it also exports to CSV.

I manually typed the name when I created the member. So I guess it's not CSV related, but instead the Category report issue.

**Comment by Fasse** [comment]
Ah, I have overlooked that it was the export of the category export. I looked in the export of groups and roles.

**Comment by Rvice** [comment]
ya, changed the description to better align with the actual issue. I thought it was the CSV, but it's not as you see now.

**Comment by Rvice** [comment]
Interesting, I just saw this on a Profile field of a user. I created a test user and typed in "Testing Apostrphe's" and it has the same display issue
https://www.admidio.org/demo_en/adm_program/modules/profile/profile.php?user_uuid=00412271-46a7-413a-af1f-570c50475907

**Comment by Fasse** [comment]
The second problem should also be fixed within version 4.2.4

**Comment by Fasse** [comment]
> Maybe this is a new issue, but when looking at the "Members" link, I try to search for this member [O'Tester](https://www.admidio.org/demo_en/adm_program/modules/profile/profile.php?user_uuid=c353f080-0e01-461f-8420-ceb72f013c19)
> 
> It is not found. It appears the apostrophe in the search does not match.

That should be a separate issue.

**Comment by Rvice** [comment]
Thanks, logged the search issue here
https://github.com/Admidio/admidio/issues/1376

The second issue you said was also fixed is in the Membership profile showing &apos;?
