### ISSUE TITLE
Header/admMenuItemAdd, in module dates

### ISSUE THREAD

**Issue by Silicon1602** [Admidio/admidio#138]
Why does Admidio requests the name of the <h1> header title and the "admMuniItemAdd" link from the URL? You have to open a connection to the database anyway for [dat_begin] - [dat_end] [dat_headeline]

For example:
modules/dates/dates.php?id=6&view_mode=html&headline=Another test"' event

Btw, if you do so, please escape strings, because in both cases you don't escape strings. I love complaining about not escaping strings :smile: 
##

**Comment by Fasse** [comment]
This request is optional. With this parameter you can change the module name if you want within your installation. But it's not necessary to use this.
Btw, we escape every parameter. See common.php line 51ff

**Comment by Silicon1602** [comment]
Sorry I didn't mean escape strings, i meant stripping slashes. My fault.

So it's possible to turn of this request and request the title out of the database?

**Comment by Fasse** [comment]
Do you have problems with this request?
If you not set it explicit than Admidio might set it with the default value.
