### ISSUE TITLE
Preference mail_bcc_count is not used anymore

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#14]
The preference mail_bcc_count should be used to create custom count of email recipients. Some servers dont allow many email recipients, so we need the option again. This was lost within the migration to the new message module.

**Comment by sirnone** [comment]
Can you give me some more information? The preference mail_bcc_count is used in 3.0 and in all earlier versions that i checked... see it in email.php on line 355

**Comment by Fasse** [comment]
You're right. I overlook this part :(
