### ISSUE TITLE
Make Tables responsive

### ISSUE THREAD

**Issue by ximex** [Admidio/admidio#145]
http://admidio.org/forum/viewtopic.php?f=2&t=6642

maybe could be only fixed if this issue get fixed: https://github.com/Admidio/admidio/issues/101

**Comment by Fasse** [comment]
Therefore we should use the implementation as in mylist.php. This should be the default for all tables and could be implemented with Datatables.

**Comment by Fasse** [comment]
We should update to new Datatables version und try table-responsive again.

https://github.com/DataTables/DataTables/commit/b03863fae772a787aa022ee645c412a82e76f484

**Comment by ximex** [comment]
DataTables v1.10.10 released
https://github.com/DataTables/DataTables/releases/tag/1.10.10
i will update the lib today

**Comment by Fasse** [comment]
No, first have a look in the master.

**Comment by ximex** [comment]
done. please test if responsive tables works.
https://github.com/Admidio/admidio/commit/b0865a9c22b9528575bd4c79689f56d64040f4fe

**Comment by Fasse** [comment]
With this additional line of code it works for all tables. Not only DataTables.

**Comment by Fasse** [comment]
Also interesting for future integrations could be this extension for datatables
https://www.datatables.net/blog/2014-07-16
