### ISSUE TITLE
Apostrophe showing as &apos; when creating new members

### ISSUE THREAD

**Issue by Rvice** [Admidio/admidio#1458]
**Describe the bug**
Demo of 4.2.10 is showing the apostrophe again and also impacting the search
https://www.admidio.org/demo_en/adm_program/modules/profile/profile.php?user_uuid=b1c3d563-05d1-4378-9ccc-e87fab3e27e4

These two issues are present again:
https://github.com/Admidio/admidio/issues/1376
https://github.com/Admidio/admidio/issues/1373

**Comment by Fasse** [comment]
It looks like our security relevant changes have break this:(

**Comment by Fasse** [comment]
I want to look into this issue now, but couldn't reproduce the problem. Unfortunally your example is deleted because we rebuild the demo system every night.

Could you please create a new example at https://www.admidio.org/playground

thanks

**Comment by Rvice** [comment]
Very easy to create, just add a new member "Testy O'Testerson" Might be beneficial to add a name like this to the database for the nightly rebuild and support the folks in the UK

https://www.admidio.org/playground/adm_program/modules/profile/profile.php?user_uuid=1d19e8d6-aba9-4864-b7e3-353519d85066

**Comment by Fasse** [comment]
Ah, it only appears if you create a new user. If you edit a user it works. 

I only edit users until now ...
