### ISSUE TITLE
Former Member showing in Category Report only because of being a past-participant in an event

### ISSUE THREAD

**Issue by Rvice** [Admidio/admidio#1459]
**Describe the bug**
A member that has no Active membership categories (only showing Former) still shows up in the Category Report. Adding in all of the roles shows no checkmarks, yet they still show in the list.

Upon deeper investigation, I observed the "former members' in the category report with "Role memberships" set as the configuration showing Events the former member attended. These events were all in the past (2021 and 2022).

**To Reproduce**
1. Take an existing member "Testy O'Testerson" and add them to an event in the future
3. Set the date for the members active role to a date prior to today.
4. Edit the event and set the date to the past (but during the term of the member)
5. Go to the Category Report and observe "Testy" is still there

**Expected behavior**
I expect not to see Testy there, even though they were a member of an event in the past. Ideally, there would be a search for events to determine who went to things, but for historical purposes, not for creating a category report (that we use to generate printed membership rosters)
Feature: On a members profile, add a section for "events" to list the events the member attended.

**Screenshots**
[Event in Demo](https://www.admidio.org/demo_en/adm_program/modules/dates/dates_new.php?dat_uuid=3991ca70-f03e-400b-94c8-f5e96fdc9e7d&headline=Events)
[Former Member in Demo](https://www.admidio.org/demo_en/adm_program/modules/profile/profile.php?user_uuid=b1c3d563-05d1-4378-9ccc-e87fab3e27e4)

**System (please complete the following information):**
 - Admidio-Version: 4.2.10 and 4.2.9

**Additional context**
Forum discussion https://www.admidio.org/forum/viewtopic.php?p=34283#p34283

**Work around**
"Delete -> Former" the member instead of looking at the Roles in the profile. Not sure if this also removes them from events, which is not a desired affect. Can test this with another user or with this one after the investigation.

**Comment by Fasse** [comment]
In my opinion the category report should ignore event roles at all. Also of they are in the Future.

**Comment by Rvice** [comment]
@Fasse I'm still seeing this in 4.2.12
