### ISSUE TITLE
Use ajax in users list and only load visible data

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#148]
Now we load all users in the users management list. This could lead to long load times if you have > 1000 members. 
We should only load the users who where shown in html and the others should be loaded on paging. This feature is supported from Datatables and should be implemented. If you use the search field then all users should be searched.
Also the assign users to roles dialog must be changed. Maybe this is an option for your HtmlTables.

**Comment by pphlwmarcel** [comment]
I've got an Admidio-Installation with more than 1000 members - If you need someone to test new code in a "live"-System just let me know.

**Comment by Fasse** [comment]
@pphlwmarcel please have a look at [this post](http://forum.admidio.org/viewtopic.php?f=7&t=7082&start=15#p24575). There I have posted a link to a test version with a fix for the member mangement.
