### ISSUE TITLE
Missing menu's (left pane) on fresh install

### ISSUE THREAD

**Issue by NunoHiggs** [Admidio/admidio#1490]
**Describe the bug**

When i install the software, either .zip based or docker container, i am left with a non fully functional application.
I can login into the app without any issues, but on the left pane of the screen, where there should be some menu, there is not.
I created several users other than admin, even can use the modules if i type them by hand in the url but they are missing.
Also tried to add a menu, and when i go to "menu level" the tab is mandatory, but the dropdown is empty.

**To Reproduce**
Fresh install software. Either zip deployment of docker

**Expected behavior**
It should show at least for the admin user, some form of menu for administration.

**Screenshots**

User with full assigned permissions:

![image](https://github.com/Admidio/admidio/assets/16701703/af64aa20-b413-4ea3-b205-9e6c06379ba0)

However there is an empty menu on the left:

![image](https://github.com/Admidio/admidio/assets/16701703/98a2c5c5-d200-401b-bdef-a49c720bac3c)

Also it's missing dropdown content on "menu" module:

![image](https://github.com/Admidio/admidio/assets/16701703/a68b1ba7-c376-466b-9972-9977bbdfdf2b)

**System (please complete the following information):**
 - Admidio - 4.2.12
 - PHP 7.4.33
 - Database MySQL
 - Browser Chrome - 117.0.5938.92
 - Browser Firefox

**Comment by Fasse** [comment]
I have problems to reproduce this behavior. I also have done a successful installation with language portuguese.

Could you please try to do a fresh installation with language english. Do you then have the same problems?

**Comment by NunoHiggs** [comment]
Hi @Fasse 

I did and the issue is the same. However i now think i might have to be something related to my mysql settings, because if i do a mysql fresh local install, it loads perfectly.
I compared the tables and there are some missing, however there is no error reported either on apache, mysql or the application itself.
It appears that something in my my.cnf settings is breaking stuff. 

For disclosure, i have a mysql active/active cluster, and i even tried to install the DB onto one of the nodes (setting it as active --> passive) and the issue would still ocurr.
Please be aware that on all the cases, the installation would end successfully. 

This is my current my.cnf configuration that *does not* work:
```

# cat /etc/my.cnf
[client]
socket=/var/lib/mysql/mysql.sock

[mysqld]
server-id=2
datadir=/var/lib/mysql
socket=/var/lib/mysql/mysql.sock
log-error=/var/log/mysqld.log
pid-file=/var/run/mysqld/mysqld.pid
max_allowed_packet=2G
default-authentication-plugin=mysql_native_password

binlog_expire_logs_seconds=604800

innodb_adaptive_hash_index=0
thread_cache_size = 100
innodb_log_buffer_size = 48M
innodb_log_file_size = 178M
event-scheduler = ON
flush_time=0
innodb_thread_concurrency=0
flush_time=0
innodb_adaptive_hash_index=0
innodb_adaptive_hash_index_parts=1
innodb_purge_threads=1

collation_server = utf8mb4_unicode_ci
character-set-server=utf8mb4
max_heap_table_size=123M
tmp_table_size=256M
join_buffer_size=512M
innodb_buffer_pool_size=1400M
innodb_flush_log_at_timeout=3
innodb_buffer_pool_instances=1

wsrep_cluster_name=msyql-cluster
wsrep_cluster_address=gcomm://172.16.0.56,172.16.0.28

wsrep_node_name=lxcVpar56
wsrep_node_address=172.16.0.55
pxc-encrypt-cluster-traffic=OFF

pxc_strict_mode=DISABLED

binlog_format=ROW
default_storage_engine=InnoDB
innodb_autoinc_lock_mode=2
relay_log_info_repository = TABLE 
relay_log_recovery = ON
max_connections = 3000
wsrep_replicate_myisam=ON
expire-logs-days = 3

# backups

wsrep_provider_options="gcache.size=2G;"

# timezone

#default-time-zone='+01:00'
default-time-zone = Europe/Lisbon

######## wsrep ###############
# Path to Galera library
wsrep_provider=/usr/lib64/galera4/libgalera_smm.so

# In order for Galera to work correctly binlog format should be ROW
binlog_format=ROW

# mysqltuner

wsrep_slave_threads = 4
wsrep_provider_options="gcs.fc_limit=120;gcs.fc_factor=0.8"
wsrep_log_conflicts

# This changes how InnoDB autoincrement locks are managed and is a requirement for Galera
innodb_autoinc_lock_mode=2

# SST method
wsrep_sst_method=xtrabackup-v2

# mysqltuner.pl

table_open_cache = 10000
table_definition_cache = -1
thread_pool_size = 24
innodb_flush_log_at_trx_commit = 0
```

However, this db configuration is running ok for at lease 20 mysql dependent applications with a lot of load.
What could be the issue?

**Comment by Fasse** [comment]
Could you please have a look if the table `adm_components` contain rows?
Could you also please have a look if the table `adm_menu` contain rows?

**Comment by NunoHiggs** [comment]
adm_components:

![image](https://github.com/Admidio/admidio/assets/16701703/1bbc3b2a-031e-4eaa-856a-a7278d60fb7b)

adm_menu:

![image](https://github.com/Admidio/admidio/assets/16701703/122b15ad-532c-4f79-a5c4-293adf583171)

This last table is empty.

**Comment by Fasse** [comment]
Could you please try to execute this sql in your database:
`INSERT INTO adm_menu
(men_com_id, men_men_id_parent, men_uuid, men_node, men_order, men_standard, men_name_intern, men_url, men_icon, men_name, men_description)
VALUES (NULL, NULL, '4711', true, 1, true, 'modules', NULL, '', 'SYS_MODULES', '')
, (NULL, NULL, '4712', true, 2, true, 'administration', NULL, '', 'SYS_ADMINISTRATION', '')
, (NULL, NULL, '4713', true, 3, true, 'plugins', NULL, '', 'SYS_PLUGINS', '')
, (NULL, 1, '4714', false, 1, true, 'overview', '/adm_program/overview.php', 'fa-home', 'SYS_OVERVIEW', '')
, ((SELECT com_id FROM adm_components WHERE com_name_intern = 'DOCUMENTS-FILES'), 1, '4715', false, 3, true, 'documents-files', '/documents-files/documents_files.php', 'fa-file-download', 'SYS_DOCUMENTS_FILES', 'SYS_DOCUMENTS_FILES_DESC')
, ((SELECT com_id FROM adm_components WHERE com_name_intern = 'GROUPS-ROLES'), 1, '4716', false, 7, true, 'groups-roles', '/groups-roles/groups_roles.php', 'fa-users', 'SYS_GROUPS_ROLES', 'SYS_GROUPS_ROLES_DESC')
, ((SELECT com_id FROM adm_components WHERE com_name_intern = 'ANNOUNCEMENTS'), 1, '4718', false, 2, true, 'announcements', '/announcements/announcements.php', 'fa-newspaper', 'SYS_ANNOUNCEMENTS', 'SYS_ANNOUNCEMENTS_DESC')
, ((SELECT com_id FROM adm_components WHERE com_name_intern = 'PHOTOS'), 1, '4719', false, 5, true, 'photo', '/photos/photos.php', 'fa-image', 'SYS_PHOTOS', 'PHO_PHOTOS_DESC')
, ((SELECT com_id FROM adm_components WHERE com_name_intern = 'GUESTBOOK'), 1, '4720', false, 6, true, 'guestbook', '/guestbook/guestbook.php', 'fa-book', 'GBO_GUESTBOOK', 'GBO_GUESTBOOK_DESC')
, ((SELECT com_id FROM adm_components WHERE com_name_intern = 'DATES'), 1, '4721', false, 8, true, 'dates', '/dates/dates.php', 'fa-calendar-alt', 'DAT_DATES', 'SYS_EVENTS_DESC')
, ((SELECT com_id FROM adm_components WHERE com_name_intern = 'CATEGORY-REPORT'), 1, '4722', false, 9, true, 'category-report', '/category-report/category_report.php', 'fa-list-ul', 'SYS_CATEGORY_REPORT', 'SYS_CATEGORY_REPORT_DESC')
, ((SELECT com_id FROM adm_components WHERE com_name_intern = 'LINKS'), 1, '4723', false, 9, true, 'weblinks', '/links/links.php', 'fa-link', 'SYS_WEBLINKS', 'SYS_WEBLINKS_DESC')
, ((SELECT com_id FROM adm_components WHERE com_name_intern = 'BACKUP'), 2, '4724', false, 4, true, 'dbback', '/backup/backup.php', 'fa-database', 'SYS_DATABASE_BACKUP', 'SYS_DATABASE_BACKUP_DESC')
, ((SELECT com_id FROM adm_components WHERE com_name_intern = 'PREFERENCES'), 2, '4725', false, 6, true, 'orgprop', '/preferences/preferences.php', 'fa-cog', 'SYS_SETTINGS', 'ORG_ORGANIZATION_PROPERTIES_DESC')
, ((SELECT com_id FROM adm_components WHERE com_name_intern = 'MESSAGES'), 1, '4726', false, 4, true, 'mail', '/messages/messages_write.php', 'fa-envelope', 'SYS_EMAIL', 'SYS_EMAIL_DESC')
, ((SELECT com_id FROM adm_components WHERE com_name_intern = 'REGISTRATION'), 2, '4727', false, 1, true, 'newreg', '/registration/registration.php', 'fa-address-card', 'SYS_NEW_REGISTRATIONS', 'SYS_MANAGE_NEW_REGISTRATIONS_DESC')
, ((SELECT com_id FROM adm_components WHERE com_name_intern = 'MEMBERS'), 2, '4728', false, 2, true, 'usrmgt', '/members/members.php', 'fa-users-cog', 'SYS_MEMBERS', 'SYS_MEMBERS_DESC')
, ((SELECT com_id FROM adm_components WHERE com_name_intern = 'MENU'), 2, '4729', false, 5, true, 'menu', '/menu/menu.php', 'fa-stream', 'SYS_MENU', 'SYS_MENU_DESC')`
Does with works successfully? Do you now have entries in `adm_menu`?

**Comment by Fasse** [comment]
Is this bug still there?
