### ISSUE TITLE
Passwords longer than 30 chars could not be saved

### ISSUE THREAD

**Issue by silverches** [Admidio/admidio#150]
Hello,

I was trying some stuff out. When i change my password to like: test', usr_text=test, usr_act.

In the database it will store the plaintext, not the encrypted version. Nor can i login with that.

**Comment by ximex** [comment]
v3.0 or v3.1?
Where do you change it? Directly in the database vor with the change password dialog?

**Comment by silverches** [comment]
Via password dialog. Using v3.0.2

**Comment by ximex** [comment]
I can't find any usage of usr_text in the whole project. Maybe it is from a old value from a 2.x version?
The password ist stored in the field "usr_password"

**Comment by Fasse** [comment]
@ximix His new password is **test', usr_text=test, usr_act**
I could confirm this.

**Comment by ximex** [comment]
oh i understand. like a SQL injection.

**Comment by Fasse** [comment]
Problem solved.
The cause was the length of the password. We had an unnecessary check for passwords < 30.
