### ISSUE TITLE
Importing members makes duplicate entries when it should replace them

### ISSUE THREAD

**Issue by phillihoch** [Admidio/admidio#1500]
**Describe the bug**
I Imported a CSV File with 160 members. I set the unique ID when matching the csv columns to the member fields.
When I import the same file again and select it should replace existing members every member is now there two times.

**To Reproduce**
1. Import members with CSV File and set the unique ID
2. Import the same file again and set the unique ID too
3. Now every member is there twice

**Expected behavior**
I expect that the replace functionality replaces existing members even if I set the unique ID.

**System (please complete the following information):**
 - Admidio-Version 4.2.12
 - PHP 7.4.33
 - Database MySQL
 - Browser chrome
 - Browser-Version 118.0.5993.70

**Additional context**
I analyzed the problem myself. It is because setting the unique ID when importing the members. If I leave the ID blank the members are replaced as expected.

PS: I now have to delete 160 members by hand...

**Comment by Fasse** [comment]
I could not reproduce the problem. Could it be that you have created the unique ID by your own and don't use the unique ID from an export of Admidio?

**Comment by phillihoch** [comment]
Yes I exported my CSV from an external data source. There every member hast a membershipID (e.g. 71293772, 8 characters).

I set this id for the unique id and did so when importing for the second time. Why doesn’t this work?

**Comment by Fasse** [comment]
There is a missunderstanding. With unique ID we mean the unique UUID of Admidio. I have renamed it for the next version and now call it `Unique Admidio-ID` to prevent this missunderstanding. 

Until now we could not identify the user by an external unique ID.
