### ISSUE TITLE
Twitter Icon not updated to X

### ISSUE THREAD

**Issue by Atharv0003** [Admidio/admidio#1509]
**Describe the bug**
The twitter Icon on footer is not updated.

**To Reproduce**

**Expected behavior**
Twitter Icon should be X

**Screenshots**
![image](https://github.com/Admidio/admidio/assets/110466931/6567ee88-7dd5-4aea-8e55-a196a65fe9db)

**System (please complete the following information):**
 - Admidio-Version [e.g. Admidio 4.2.3]
 - PHP [e.g. PHP 8.1]
 - Database [e.g. MySQL, PostgreSQL]
 - Browser-Version [e.g. 22]

**Additional context**

**Comment by Atharv0003** [comment]
I am working on this issue please assign this to me

**Comment by Fasse** [comment]
@Atharv0003 How will you work on this issue? It's the screenshot of the website and not the Admidio app.
