### ISSUE TITLE
Support all Image proportions for Organization Logo

### ISSUE THREAD

**Issue by ximex** [Admidio/admidio#151]
http://admidio.org/forum/viewtopic.php?f=4&t=6567

**Comment by ximex** [comment]
i think a little bigger restructering of the header will be needed

**Comment by Fasse** [comment]
Maybe this is something for 3.2?

**Comment by ximex** [comment]
if i found time i would do it. maybe in beta 2.

**Comment by Fasse** [comment]
This is now irrelevant because we have a new theme.
