### ISSUE TITLE
Running docker version admidio:latest with postgresql fails

### ISSUE THREAD

**Issue by johnsonbrothers** [Admidio/admidio#1518]
**Describe the bug**
Installing admidio:latest with postgresql as database dont save the admin-users as it would do.

I get an error in postgres log when the installation fills all database tables.

2023-11-07 18:46:02.251 UTC [48] STATEMENT:  INSERT INTO adm_user_fields
                       (usf_cat_id, usf_uuid, usf_type, usf_name_intern, usf_name, usf_description, usf_description_inline, usf_value_list, usf_system, usf_disabled, usf_mandatory, usf_registration, usf_sequence, usf_usr_id_create, usf_timestamp_create)
                VALUES (1, '82ba5238-061a-44e9-bf83-a7b5b520fdc3', 'TEXT',         'LAST_NAME',  'SYS_LASTNAME',  NULL, false, NULL, true, true, true, true, 1,  1, '2023-11-07 19:46:01')
                     , (1, '3598457a-5aef-415e-a110-094277984976', 'TEXT',         'FIRST_NAME', 'SYS_FIRSTNAME', NULL, false, NULL, true, true, true, true, 2,  1, '2023-11-07 19:46:01')
                     , (1, '2c12b111-1b3e-41bc-89fa-2548c1b47ba8', 'TEXT',         'STREET',     'SYS_STREET',    NULL, false, NULL, false, false, false, false, 3,  1, '2023-11-07 19:46:01')
                     , (1, 'd8f93d9c-8940-4877-af6f-e8e6be94ad23', 'TEXT',         'POSTCODE',   'SYS_POSTCODE',  NULL, false, NULL, false, false, false, false, 4,  1, '2023-11-07 19:46:01')
                     , (1, '485a9cbf-a2c8-41cc-a8fb-4ba31046833b', 'TEXT',         'CITY',       'SYS_CITY',      NULL, false, NULL, false, false, false, false, 5,  1, '2023-11-07 19:46:01')
                     , (1, 'b8d1fb87-13d3-4a17-9a1b-46debd6192be', 'TEXT',         'COUNTRY',    'SYS_COUNTRY',   NULL, false, NULL, false, false, false, false, 6,  1, '2023-11-07 19:46:01')
                     , (1, '7f76f685-5279-4746-b5da-57a26fa46e94', 'PHONE',        'PHONE',      'SYS_PHONE',     NULL, false, NULL, false, false, false, false, 7,  1, '2023-11-07 19:46:01')
                     , (1, '45bb05a3-419b-4c88-9065-bf2b18c8cdc1', 'PHONE',        'MOBILE',     'SYS_MOBILE',    NULL, false, NULL, false, false, false, false, 8,  1, '2023-11-07 19:46:01')
                     , (1, 'fb6b8355-2804-4e17-af29-e95fb3a629bf', 'PHONE',        'FAX',        'SYS_FAX',       NULL, false, NULL, false, false, false, false, 9,  1, '2023-11-07 19:46:01')
                     , (1, '7c242446-8f87-4920-ab49-f8cfc18cc748', 'DATE',         'BIRTHDAY',   'SYS_BIRTHDAY',  NULL, false, NULL, false, false, false, false, 10, 1, '2023-11-07 19:46:01')
                     , (1, '145a52eb-5ce4-4f56-bbf1-c68018717c03', 'RADIO_BUTTON', 'GENDER',     'SYS_GENDER',    NULL, false, 'fa-mars|SYS_MALE
        fa-venus|SYS_FEMALE
        fa-mars-stroke-v|SYS_DIVERSE', 0, 0, 0, 0, 11, 1, '2023-11-07 19:46:01')
                     , (1, '4daec173-bfc6-4b2c-986a-d4e7b52b96b1', 'EMAIL',        'EMAIL',      'SYS_EMAIL',     NULL, false, NULL, true, false, true, true, 12, 1, '2023-11-07 19:46:01')
                     , (1, '816e5868-c9b6-4057-b430-a91709ddca68', 'URL',          'WEBSITE',    'SYS_WEBSITE',   NULL, false, NULL, false, false, false, false, 13, 1, '2023-11-07 19:46:01')
                     , (3, 'b8e25858-f7e2-40a1-b056-6f252f350f05', 'CHECKBOX', 'DATA_PROTECTION_PERMISSION', 'SYS_DATA_PROTECTION_PERMISSION', 'Jag har läst informationen från organisationen. I den mån de personuppgifter som jag tillhandahållit inte är nödvändiga uppgifter för att uppfylla kontraktet, förklarar jag mitt samtycke till behandlingen av dessa uppgifter. Mina uppgifter kommer att lagras uteslutande för organisationens ändamål och behandlas konfidentiellt.', true, NULL, false, false, true, true, 14, 1, '2023-11-07 19:46:01')
2023-11-07 18:46:03.119 UTC [48] ERROR:  column "cat_default" is of type boolean but expression is of type integer at character 242
2023-11-07 18:46:03.119 UTC [48] HINT:  You will need to rewrite or cast the expression.

**To Reproduce**

I create file directorys for postgres data files and admidio files

mkdir /some/path/postgres
mkdir /some/path/admidio/files
mkdir /some/path/admidio/themes
mkdir /some/path/admidio/plugins

I run podman as container environment.
So I create a POD to run postgres and admidio together and just exposing web-port.
podman pod create --name admidio --publish 8080:8080

install postgresql
podman run -dt --pod admidio -e POSTGRES_PASSWORD=kalle12 -v "/some/path/postgres:/var/lob/postgresql/data:Z"

install admidio
podman run --pod=admidio -v "/some/path/admidio/files:/opt/app-root/src/adm_my_files:Z" -v "/some/path/admidio/themes:/opt/app-root/src/adm_themes:Z" -v "/some/path/admidio/plugins:/opt/app-root/src/adm_plugins:Z" -d admidio/admidio:latest

When containers up and running, I connect to postgres and creates a database for admidio

Run my web browser to localhost:8080 and start install admidio. Choose postgres as database, creates an admin user and finish installation. I log in to admidio as last step.

When I list all users, my user is not listed.

After reinstalling for three times, I see the error in the postgres container:
ERROR:  column "cat_default" is of type boolean but expression is of type integer at character 242

select * from adm_users; lists the system-user and my user created during installation.

Trying to create a member or user fails.

**Expected behavior**
I expect the admin user, created during installation to be saved.

**Screenshots**

**System (please complete the following information):**
 - Admidio-Version 4.1.19
 - PHP unknown - using container :latest
 - Database PostgreSQL
 - Browser Firefox
 - Browser-Version 119

**Additional context**

**Comment by Fasse** [comment]
Could you please use this tag [v4.2.13](https://hub.docker.com/layers/admidio/admidio/v4.2.13/images/sha256-50e399429157f1c120d6eebe89ffe1189fc6977a16a327d2db9e77b1b145caa0?context=explore)

That's the current released version. The Latest is not the latest :(

**Comment by johnsonbrothers** [comment]
I have tested with tag v4.2.13 and my installation runs and it looks like its working.
Please remove :latest or update it to v4.2.13.

**Comment by schast** [comment]
The :latest tag still pointed to version v4.1.19, which is not compatible with v4.2 and could not be updated automatically.
I have therefore deleted the :latest tag.

**Comment by relikd** [comment]
So its a recent change ... The Docker Readme is not up to date anymore. Cant pull the :latest image with docker-compose. Would be nice to have tags for automatic version update, eg. v4
