### ISSUE TITLE
Database error creating and installing database

### ISSUE THREAD

**Issue by johnsonbrothers** [Admidio/admidio#1530]
**Describe the bug**
When installing admidio for the first time, the last step "Now the database has to be created and filled with your data." will create an error using postgres as database engine

2023-11-27 10:55:29.761 UTC [205] ERROR:  column "cat_sequence" is of type smallint but expression is of type boolean at character 248
2023-11-27 10:55:29.761 UTC [205] HINT:  You will need to rewrite or cast the expression.
2023-11-27 10:55:29.761 UTC [205] STATEMENT:  INSERT INTO adm_categories
                               (cat_org_id, cat_uuid, cat_type, cat_name_intern, cat_name, cat_default, cat_sequence, cat_usr_id_create, cat_timestamp_create)
                        VALUES ($1, $2, 'ROL', 'COMMON', 'SYS_COMMON', true, true, $3, $4)

**To Reproduce**

1. start postgres container
2. create database in postgres
3. start admidio container
4. go to start webbpage to start configure admidio
5. go through all steps, connecting to database, creating administrator to the final step, filling database with default values
6. See error in postgres log

**Expected behavior**

**Screenshots**
![bild](https://github.com/Admidio/admidio/assets/8428546/fac81843-955d-47dc-882f-ed7a41093ecb)

**System (please complete the following information):**
- Admidio-Version container Admidio tag latest i.e. 4.2.14
- PHP n/a, using container
- Database PostgreSQL
- Browser firefox
- Browser-Version 119.0.1

**Additional context**

**Comment by johnsonbrothers** [comment]
The installation continues and I can log in to Admidio, but I dont know if Im missing functionality or if the system is misconfigured

**Comment by Fasse** [comment]
That was a regression of a previous fix. I will create a new version 4.2.15 today because it's not that good to have such a wrong SQL statement within the installation.
