### ISSUE TITLE
Cannot set end date for Role Leader, with two leaders

### ISSUE THREAD

**Issue by Rvice** [Admidio/admidio#1542]
**Describe the bug**
We have a change in officers and the structure we have is that the Vice President is the Leader of the other Role (Board in this case). When we had our elections in December 2023, I added the new Vice President starting 1/1/2024 and then attempted to set the 2023 Vice President "Board" role to terminate 12/31/2023.

What's happening now though, is that I cannot set an end date to the outgoing vice president (2023) or remove the "leader" role from the user as well. Note, now that it is 2024, the 2023 vice-president no longer has vice president as an active role (it's now former).

**To Reproduce**
1. I'll need to play around in playground to see if I can replicate this.

**Expected behavior**

**Screenshots**
Showing board role only for 2023 vice president
![image](https://github.com/Admidio/admidio/assets/1831523/a17c5e49-97a6-4c56-8ffe-a2c09ab86dd8)

Showing history of 2023 vice president
![image](https://github.com/Admidio/admidio/assets/1831523/561422e0-e2b9-49ca-9ea2-af159ab49f25)

2024 Vice President and former
![image](https://github.com/Admidio/admidio/assets/1831523/e07661a3-fc16-4ab7-b659-de1299186b37)

Observe in the 2024 vice president, the "Associations Board" is not listed twice as it is on the 2023 vice president.

**System (please complete the following information):**
 - Admidio-Version 4.2.13
 - PHP 7.4.10
 - Database MySQL
 - Browser Chrome
 - Browser-Version

**Additional context**

**Comment by Fasse** [comment]
Could you please have a look in the playground and if this behavior is still available with Admidio 4.3 ?
I made some changes to the logic how roles will be assigned.

The old behavior in 4.2 will delete former role assignments if you assign the same role again :(

**Comment by Rvice** [comment]
It's not "broken" but the behavior is a little weird.

The user that is becoming "Leader" gets removed from the role (Associations Board) but becomes leader on the last day. I was sort of expecting the person to continue being within the role and not going to "former"

i.e. being Leader is also a member of the Role.

**Comment by Fasse** [comment]
Could you please explain me step by step what you have done., so I could reproduce the problem.
