### ISSUE TITLE
Autoload function not accessable for Admidio classes if 3rd party libary with own autoloader is used

### ISSUE THREAD

**Issue by thomas-rcv** [Admidio/admidio#156]
Including common.php in folder adm_plugins the autoload function doesn´t match the root for the Admidio classes and a fatal error will occur (not found).
At this time classes have to be included manually.
Should be fixed. Could be done with:

https://github.com/Admidio/admidio/issues/146

**Comment by Fasse** [comment]
I don't understand the problem. We build the path for the include not relative. We build it absolute. So it should also work with plugins. 

Do you have an example were it doesn't work?

**Comment by thomas-rcv** [comment]
It doesn´t work in written communications functions. It seems that the including path is relative to the executing script and the classes are in admprogram/System/classes.

**Comment by Fasse** [comment]
All includes are absolute:
https://github.com/Admidio/admidio/blob/master/adm_program/system/function.php#L18
https://github.com/Admidio/admidio/blob/master/adm_program/system/common.php#L43

Does other functions from functions.php work?

**Comment by thomas-rcv** [comment]
All constants and functions are loaded. Also admFuncVariableIsValid is working fine.

**Comment by thomas-rcv** [comment]
Ok, I found the problem.
It is definitly the php function __ autoload. By the way, I read that the autoload function may be deprecated in the future. It is recommended only to use the spl_autoload function, because it is more flexible and also allows several instances while php __ autoload  can only be unique.

In the plugin written communications I´m working with the php libary phpword. 
Now the Facts:
PhpWord has it´s own autoloader for the classes and further more there also is a Namespace ( php 5.3) defined!  The autoloader is using the spl_autoload_register for the own classes.
Regarding the php manual,... If spl_autoload_register is used,... the php __ autoload is automatically disabled! This is the simply answer why I run in trouble within the plugin.
However, I would name this issue as bug, but it automatically would be fixed if we change our autoload function to spl_autolad as well.
At this time we would have probably further problems using scripts with namespaces. 
The autoloader will always work in the current namespace. We didn´t  defined a namespace for Admidio core for so far. This means our root is in the global scope and we would need to define exactly the global scope to read our classes.
Instead of:
$a = new class();
we would need to define the global scope exactly ( maybe the namespace has changed in a script)
$a = \new class();

**Comment by Fasse** [comment]
Then we should fix #146 und this issue can be closed.

**Comment by Fasse** [comment]
#146 is fixed in v3.0 branch. Please try your plugin with this branch.

**Comment by thomas-rcv** [comment]
Please have a look to my comment in the last commit.
Issue can be closed.
It´s working fine now
