### ISSUE TITLE
SQL Error in List Configuration when multiple Roles selected

### ISSUE THREAD

**Issue by ttytrekker** [Admidio/admidio#1586]
**Describe the bug**
S Q L - E R R O R
CODE: HY000
3065
Expression #1 of ORDER BY clause is not in SELECT list, references column 'admidio43.mem.mem_leader' which is not in SELECT list; this is incompatible with DISTINCT

B A C K T R A C E
FILE: adm_program/system/classes/Database.php
LINE: 797

CALL: Database->showError()
FILE: adm_program/system/classes/ListData.php
LINE: 213
CALL: Database->queryPrepared()

FILE: adm_program/system/classes/ListData.php
LINE: 198
CALL: ListData->setDataBySql()

FILE: adm_program/modules/groups-roles/lists_show.php
LINE: 230
CALL: ListData->setDataByConfiguration()

**To Reproduce**
1. Go to List Configuration and select any list.
2. From Select Members add two or more Roles.
3. Click Display List to generate error.

**Expected behavior**
List is displayed based on selection criteria.

**Screenshots**
<img width="1000" alt="Screenshot 2024-02-13 at 12 38 16 PM" src="https://github.com/Admidio/admidio/assets/80766704/897398a7-0436-481b-9d48-8cbb2ee37a0f">

<img width="1001" alt="Screenshot 2024-02-13 at 12 42 06 PM" src="https://github.com/Admidio/admidio/assets/80766704/f11f855e-f3f6-48c5-813a-211abe48f041">

**System (please complete the following information):**
 - Admidio-Version 4.3.3
 - PHP v8.1.27 (cli) (built: Dec 19 2023 20:35:55) (NTS gcc x86_64)
 - Database MySQL v8.0.32
 - Browser Safari
 - Browser-Version v17.3.1

**Additional context**
None.

**Comment by Fasse** [comment]
Thanks for the detailed error report. This is fixed within the next version.

**Comment by ttytrekker** [comment]
Like your app and happy to help.
