### ISSUE TITLE
Missing 'ca-certificates' pkg in Docker container

### ISSUE THREAD

**Issue by br0uQ** [Admidio/admidio#1597]
**Describe the bug**
I'm using the Docker version of admidio, but was unable to get mail sending over smtp working.
Sending the test email always returned a certificate verification failure.

After some testing with the help of this toubleshooting page:
https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#certificate-verification-failure
It seemed there weren't any certificates in the container.

After installing 'ca-certificates' pkg in the docker container everything worked fine.

Did I miss something? Is there anonther possibility to get the ca-certificates into the container. If yes maybe this should be documented.

Else I guess that package should be included in the Dockerfile.
If desired I could create a PR.

**To Reproduce**
1. Create docker container using [README-Docker.md](https://github.com/Admidio/admidio/blob/master/README-Docker.md)
2. Run and Setup admidio
3. Configure sending mail using smtp
4. Send test email

**Expected behavior**
Working CA-Certificates using the docker container and therefor working smtp mail

**System (please complete the following information):**
 - Admidio-Version 4.2.5
 - PHP 8.1.2-1ubuntu2.14
 - Database MariaDB
 - Browser: Brave
 - Browser-Version 1.62.165 Chromium: 121.0.6167.184

**Comment by schast** [comment]
Is fixed with `v4.3.6` release and currently in `admidio/admidio:branch_v4.3`
