### ISSUE TITLE
User is not checked when send the mail to him

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#16]
If we send a mail to selected users then this users where not checked if we have the right to do this. Therefore we should check if the current user has the right to view the profile only then he should be able to send a mail to this user.

So the check in ecard module ecard_send.php line 64ff

**Comment by sirnone** [comment]
Hello Fasse,

this check is in the Version 3.0 (messages_send.php line 130 to 148)
please inform me if you can see there a problem?

**Comment by Fasse** [comment]
Hi Stefan,
I saw this, but that checks only if the current user is allowed to send the mail to the role. You don't check if the user is allowed to send a mail to a single user that is added in the "to" field. See line 225ff

**Comment by sirnone** [comment]
fixed with a short if statement.
