### ISSUE TITLE
Exporting from Groups to CSV results in failed to delete buffer and "No." column missing

### ISSUE THREAD

**Issue by Rvice** [Admidio/admidio#1607]
**Describe the bug**
Exporting "former members" to CSV results in failed to delete buffer and "No." (index) column missing in export

**To Reproduce**
1. Go to Groups & Roles
2. Click on Former Members from one of the roles
3. Click Export to CSV
4. See error in CSV output:
`
<br />
<b>Notice</b>:  ob_clean(): failed to delete buffer. No buffer to delete in <b>/admidio/adm_program/system/classes/ListData.php</b> on line <b>266</b><br />
`
**Expected behavior**
Expect to see the index column and no error message at the top of the export

**Screenshots**
-None-

**System (please complete the following information):**
 - Admidio-Version: 4.3.3 and 4.3.5
 - PHP: 7.4.10
 - Database MySQL
 - Browser: Chrome
 - Browser-Version: N/A

**Additional context**
This was working prior to the big changes to 4.3

**Comment by Fasse** [comment]
I could not reproduce this at our demo space. Does this occur at any role? 
Does this only occurs at csv export? Work the export to excel?

**Comment by Rvice** [comment]
Export to XML is even worse
`
Fatal error: Uncaught Error: Class 'XMLWriter' not found in /admidio/adm_program/libs/server/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Shared/XMLWriter.php:5 Stack trace: #0 /admidio/adm_program/libs/server/composer/ClassLoader.php(578): include() #1 /admidio/adm_program/libs/server/composer/ClassLoader.php(432): Composer\Autoload\ClassLoader::Composer\Autoload\{closure}('/admidio/adm_pr...') #2 [internal function]: Composer\Autoload\ClassLoader->loadClass('PhpOffice\\PhpSp...') #3 /admidio/adm_program/libs/server/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Writer/Xlsx/ContentTypes.php(27): spl_autoload_call('PhpOffice\\PhpSp...') #4 /admidio/adm_program/libs/server/phpoffice/phpspreadsheet/src/PhpSpreadsh in /admidio/adm_program/libs/server/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Shared/XMLWriter.php on line 5
`

Did memory requirements maybe go up? I know the server we're on is somewhat constrained.

**Comment by Rvice** [comment]
Note, the export from roles in Playground no longer has the "No." column, but the category report does.
[DEMO-Category_report-General_role_assignment (1).csv](https://github.com/Admidio/admidio/files/14530623/DEMO-Category_report-General_role_assignment.1.csv)
[DEMO-Member-Address_list.csv](https://github.com/Admidio/admidio/files/14530624/DEMO-Member-Address_list.csv)

Not sure why I'm seeing the error, maybe I had a dirty install. I'll re-upload the files and report back.

**Comment by Fasse** [comment]
It looks like your PHP installation needs php-xml
https://stackoverflow.com/questions/41121477/class-xmlwriter-not-found-error-in-php-php55w-xml-5-5-24-1-w6-x86-64-rpm-i

Than this function should work.

**Comment by Rvice** [comment]
@Fasse what about the No. column missing from the Group exports?

**Comment by Rvice** [comment]
Got php-xml installed, that sorta resolved the .xlsx export, but that has the same issue as the normal export with this showing at the top of the .xlsx without being able to open it in Excel.

`html
<br />
<b>Notice</b>:  ob_clean(): failed to delete buffer. No buffer to delete in <b>/hermes/bosnacweb04/bosnacweb04cb/b1177/ipg.robertviceipage45214/admidio/adm_program/system/classes/ListData.php</b> on line <b>266</b><br />
`

**Comment by Rvice** [comment]
Adding the following to ListData.php resolved the error:
        if(ob_get_length() > 0) {
            ob_clean();
        }

**Comment by Rvice** [comment]
https://github.com/Admidio/admidio/pull/1612

**Comment by Fasse** [comment]
Ok, I will reopen it, because the problem with the buffer was still there in your system. I thougth this error belongs to the missing xml part of PHP.

I removed the `No` from export because that doesn't belongs to an export. Excel and Co have their own system to list elements.

**Comment by Rvice** [comment]
Futher note, I observed in the Playground that the "No." column is actually printed in the CSV export. I think this might be the issue related to https://github.com/Admidio/admidio/pull/1612, i.e. something is out of whack in my instance.
