### ISSUE TITLE
Display failure with quotes in event location name

### ISSUE THREAD

**Issue by andrewagner86** [Admidio/admidio#1635]
**Describe the bug**
If I use quotes in the event location name field, the location name is buggy for ical export and google maps link.

**To Reproduce**
Set a location name with quotes

**Expected behavior**
Location name is displayed correctly for google maps link and in ical export

**System (please complete the following information):**
 - Admidio 4.3.5
 - PHP 8.1.2
 - MySQL
 - Chrome / Android

**Screenshots**
![WhatsApp Image 2024-04-22 at 12 45 17 (1)](https://github.com/Admidio/admidio/assets/120205545/b383febf-1308-4f94-9061-4a8c0d2aa1ec)

![WhatsApp Image 2024-04-22 at 12 45 17 (2)](https://github.com/Admidio/admidio/assets/120205545/3f436671-f867-4c34-b85b-c3d49b11555b)

![WhatsApp Image 2024-04-22 at 12 45 17](https://github.com/Admidio/admidio/assets/120205545/c944fd94-9b96-4b70-9683-2190647cf22e)

**Comment by andrewagner86** [comment]
i made a pull request for ical issue #1636

**Comment by Fasse** [comment]
Thanks for the fix, I have merged the pull requests.
