### ISSUE TITLE
pictures in an event dont scale correct

### ISSUE THREAD

**Issue by dkers** [Admidio/admidio#1649]
When I create an event with a wide picture, this picture is not scaled/trunated correct in both website and mobile view.,

**To Reproduce**
1. Create an event
2. Add an image to the event layout
3. go to any page which shows events 
4. The image is warping over the event block

**Expected behavior**
correctly truncated or scaled image
**Screenshots**
![afbeelding](https://github.com/Admidio/admidio/assets/56264554/0104946d-a2e6-41f8-9840-10b8fde258c5)

**System (please complete the following information):**
 - Admidio-Version 4.3.7
 - PHP [e.g. PHP 8.2.17]
 - Database [MySQL]
 - Browser [firefox125.0.3 /edge/ firefox mobile 125.3.0]
 -

**Additional context**

**Comment by Fasse** [comment]
please add the following code to the admidio.css in your template:
`.admidio-blog img, .admidio-card img {
    max-width: 100%;
    height: auto;
}`
