### ISSUE TITLE
SQL Error on Docker

### ISSUE THREAD

**Issue by Niemand112233** [Admidio/admidio#1671]
Hi, 

when using the docker image I get this error on the webpage:

SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for admidio-mariadb failed: Name or service not known

**Comment by schast** [comment]
The hostname of Mariadb Container must equal to the hostname of ADMIDIO_DB_HOST like described in the [README-Docker.md](https://github.com/Admidio/admidio/blob/master/README-Docker.md#start-a-mariadb-server-instance-optional). And both Container must in the same Docker Network.

```
docker run --detach -it --name "Admidio-MariaDB" \
  --hostname "admidio-mariadb" \
  -p 3306:3306 \
  --restart="unless-stopped" \
  -v "Admidio-MariaDB-confd:/etc/mysql/conf.d" \
  -v "Admidio-MariaDB-data:/var/lib/mysql" \
  -e MYSQL_DATABASE="admidio" \
  -e MYSQL_ROOT_PASSWORD="my_VerySecureRootPassword.01" \
  -e MYSQL_USER="admidio" \
  -e MYSQL_PASSWORD="my_VerySecureAdmidioUserPassword.01" \
  mariadb:latest
```

```
docker run --detach -it --name "Admidio" \
  -p 8080:8080 \
  --restart="unless-stopped" \
  -v "Admidio-files:/opt/app-root/src/adm_my_files" \
  -v "Admidio-themes:/opt/app-root/src/adm_themes" \
  -v "Admidio-plugins:/opt/app-root/src/adm_plugins" \
  -e ADMIDIO_DB_HOST="admidio-mariadb:3306" \
  -e ADMIDIO_DB_NAME="admidio" \
  -e ADMIDIO_DB_USER="admidio" \
  -e ADMIDIO_DB_PASSWORD="my_VerySecureAdmidioUserPassword.01" \
  -e ADMIDIO_ROOT_PATH="https://www.mydomain.at/admidio" \
  admidio/admidio:latest
```

Can you post your Admidio Docker Config?

**Comment by Fasse** [comment]
@Niemand112233  Is this issue still open?

**Comment by IKyriazis** [comment]
i had this same problem, I didn't realize I had to add both docker containers to the same network. I executed the following command to create the network:
docker network create admidio-network

and I added the following flag to both of the container execution commands:
--network admidio-network

**Comment by Fasse** [comment]
@schast Maybe that should be described more prominent in the docker md.

**Comment by schast** [comment]
Was added to the `README-Docker.md` in the pull request (#1711 ).
