### ISSUE TITLE
adm_members table export to .csv

### ISSUE THREAD

**Issue by niko-todorov** [Admidio/admidio#1672]
Admidio backs up the whole DB schema in a db_backup.{date}.{id}.sql.gz file, where all SQL transactions are present to sequentially recreate the whole schema. 

Here is a simple use-case. Would be super useful if only the latest committed state of the adm_members table could be exported in .csv.

Let me know if this is doable (or already done). 

Thanks in advance!
Niko Grisel Todorov
ntodorov@baces.org

**Comment by Fasse** [comment]
A special export for the latest adm_members entries is not useful. You can export groups through the lists.

Could you explain your use case more detailled. Maybe you need another feature.
