### ISSUE TITLE
Enhanced password character limit to 100 in preferences SMTP Password

### ISSUE THREAD

**Issue by beenbiishop** [Admidio/admidio#1679]
**Describe the bug**
The SMTP password field in the Email delivery preferences has a max length of 50 characters, but Sendgrid uses 69 character API keys. This makes Sendgrid an incompatible SMTP provider for Admidio.

**To Reproduce**
1. Go to Preferences
2. Click on the 'Email Delivery' section
3. Scroll down to the 'SMTP Password' field
4. Try pasting in a Sendgrid API key (69 characters)
5. The `maxlength="50"` parameter on the input field causes the key to cut off

**Expected behavior**
The value column in adm_preferences supports values up to 255 characters, so this input field should support at least 69 characters or more.

**Screenshots**
N/A

**System (please complete the following information):**
 - Admidio-Version 4.3.10
 - PHP 8.0
 - Database MySQL
 - Browser chrome
 - Browser-Version 127.0.6533.100

**Additional context**
N/A

**Comment by Fasse** [comment]
Thanks for the hint. The maxlength will now be 100.
