### ISSUE TITLE
Email link to message modul with user id wont work

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#183]
If you are in the list module and have the email as a column than you can click on an email address and the message_write script will be open. The user id is one of the parameters. But in the current master code the user is not preset in the formular.

**Comment by Fasse** [comment]
@sirnone why did you fix it in the 3.0 branch. This problem was only in the current master.

**Comment by sirnone** [comment]
was a mistake in the Git-client... i was in the wrong Branch (should i remove it from here?)

**Comment by ximex** [comment]
this is why i only work with the terminal version of git ;-)
i think the best is a normal revert of the last commit (`git revert HEAD`)
