### ISSUE TITLE
Today-Button not shown in profile date fields

### ISSUE THREAD

**Issue by Bullnados** [Admidio/admidio#187]
see....
http://forum.admidio.org/viewtopic.php?f=2&t=6684

**Comment by Fasse** [comment]
Within the profile the datepicker has the wrong format for date fields. It always show the birthday mode.

**Comment by Bullnados** [comment]
That was fast.
But will this happen again if u change  somethin in event date files f.e. yesterday button?

**Comment by Fasse** [comment]
no because we only have 1 special date field and that is birthday. All other date fields have the same behaviour.
And birthday has now an own datepicker object.
