### ISSUE TITLE
Database communication should be done with PDO

### ISSUE THREAD

**Issue by ximex** [Admidio/admidio#19]
If we use PDO SQL instructions we didn't have to write code for different DBs.
I only don't know if the providers allow this commands.
PDO is available in PHP 5.1 and above.
https://php.net/manual/de/book.pdo.php

**Comment by Fasse** [comment]
We should implement this in the next major release because used mysql function are marked as deprecated.

**Comment by ximex** [comment]
Here a list of available DB that are supported by PDO:
- Cubrid
- FreeTDS / Microsoft SQL Server / Sybase
- Firebird
- IBM DB2
- IBM Informix Dynamic Server
- **MySQL 3.x/4.x/5.x**
- Oracle Call Interface
- ODBC v3 (IBM DB2, unixODBC und win32 ODBC)
- **PostgreSQL**
- SQLite 3 und SQLite 2
- Microsoft SQL Server / SQL Azure
- 4D

**Comment by ximex** [comment]
If we rewrite the DB code we should also switch to **[Prepared Statements](https://secure.php.net/manual/de/pdo.prepared-statements.php)**.

There are two major improvements with this:
- faster SQL transactions because of pre analyzed querys
- save SQL transactions because SQL Injections are no longer possible

**Comment by ximex** [comment]
Currently we have 4 DB Files:
- `database.php` (switch between mysql and postgres)
- `dbcommon.php` (base class)
- `dbmysql.php` (mysql child class)
- `dbpostgres.php` (postgres child class)

If think we could merge all of this files into one. (`database.php`?)

**Comment by ximex** [comment]
Here some Overview:

## DBCommon
### Properties
- `public $dbType`
- `public $user`
- `public $password`
- `public $dbName`
- `public $server`
- `protected $name`
- `protected $version`
- `protected $minVersion`
- `protected $connectId`
- `protected $queryResult`
- `protected $sql`
- `protected $transactions`
- `protected $dbStructure`

### Functions
- `public function db_error()`
- `public function endTransaction()`
- `public function getName()`
- `public function getMinVersion()`
- `public function getVersion()`
- `public function rollback()`
- `public function startTransaction()`
- `protected function getBacktrace()`

## DBMySQL / DBPostgreSQL
### Functions
- `public function connect()`
- `public function data_seek()`
- `public function db_error()` -> `parent::db_error()`
- `public function escape_string()`
- `public function fetch_assoc()`
- `public function fetch_array()`
- `public function fetch_object()`
- `public function field_name()`
- `public function free_result()`
- `public function insert_id()`
- `public function num_fields()`
- `public function num_rows()`
- `public function query()`
- `public function select_db()`
- `public function server_info()`
- `public function setCurrentDB()`
- `public function setDBSpecificAdmidioProperties()`
- `public function showColumns()`

**Comment by ximex** [comment]
my first "prove of concept":

```php
<?php

/**
 * Class DB
 */
class DB
{
    private $engine;
    private $host;
    private $port;
    private $dbName;
    private $username;
    private $password;
    private $options;
    private $dsn;
    private $pdo;

    /**
     * @param string $engine
     * @param string $host
     * @param int    $port
     * @param string $dbName
     * @param string $username
     * @param string $password
     * @param array  $options
     */
    public function __construct($engine, $host, $port = null, $dbName, $username = null, $password = null, $options = array())
    {
        $this->engine   = $engine;
        $this->host     = $host;
        $this->port     = $port;
        $this->dbName   = $dbName;
        $this->username = $username;
        $this->password = $password;
        $this->options  = $options;

        try
        {
            if (!$this->engine || !$this->host || !$this->dbName) {
                throw new Exception('Engine, Host and DB-Name are required Parameters');
            }
        }
        catch (Exception $e)
        {
            print "Error .. Details :<br /> {$e->getMessage()}";
            exit();
        }

        try
        {
            if (empty(PDO::getAvailableDrivers()))
            {
                throw new PDOException('PDO does not support any drivers');
            }
            if (!in_array($this->engine, PDO::getAvailableDrivers(), true))
            {
                throw new PDOException('The requested PDO driver is not supported');
            }
        }
        catch (PDOException $e)
        {
            print "PDO Driver Error .. Details :<br /> {$e->getMessage()}";
            exit();
        }

        $this->buildDSNString();

        // needed to avoid leaking username, password,... if a PDOException is thrown
        try
        {
            $this->pdo = new PDO($this->dsn, $this->username, $this->password, $this->options);
        }
        catch (PDOException $e)
        {
            print "Error!: " . $e->getMessage() . "<br/>";
            exit();
        }
    }

    /**
     *
     */
    public function __destruct()
    {
        $this->pdo = null;
    }

    /**
     *
     */
    private function buildDSNString()
    {
        try
        {
            switch ($this->engine)
            {
                case 'mysql':
                    if (!$this->port)
                    {
                        $this->port = 3307;
                    }

                    $this->dsn = 'mysql:host='.$this->host.';port='.$this->port.';dbname='.$this->dbName;
                    break;
                case 'pgsql':
                    if (!$this->port)
                    {
                        $this->port = 5432;
                    }

                    $this->dsn = 'pgsql:host='.$this->host.';port='.$this->port.';dbname='.$this->dbName;
                    break;
                default:
                    throw new Exception('Engine is not supported by Admidio');
            }
        }
        catch (Exception $e)
        {
            print "Error!: " . $e->getMessage() . "<br/>";
            exit();
        }
    }

    /**
     * @return array
     */
    public static function getAvailableDBs()
    {
        return PDO::getAvailableDrivers();
    }
}

?>
```

**Comment by Fasse** [comment]
First I try to create a full backwards compatible database class, so there should be not much changes to all of our scripts. 
In the next step I try to integrate some new modern methods and mark the old ones as deprecated.

With this we have time to migrate some of our db code to the new methods.

**Comment by ximex** [comment]
isn't there a `require_once('database2.php')` somewhere missing?

**Comment by Fasse** [comment]
No we use autoload.

**Comment by ximex** [comment]
"autoload"? Plesse explain. Don't know this feature

**Comment by ximex** [comment]
merged: https://github.com/Admidio/admidio/pull/155
