### ISSUE TITLE
Add relationships between users

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#195]
We should add relationships between different users. Therefore we need to configure possible relationships and their link to each other. 
Possible relationships roles: 
* mother 
* father
* son
* daughter
* sister
* brother
* ...

Possible links: 
* father - daughter
* father - son
* sister - brother
* sister - sister
* ...

Within the profile you can add relationships to the current user. Therefore you must define his role e.g. **father** and then the user you want to define the relationship and than you can choose the possible relationships roles for this user e.g. **daughter** or **son**. If we consider the gender and this data is mantained in the database we could direkt save the right role e.g. **daughter**.

A link should only defined ones. E.g. the link **father - daughter** could also be **daughter - father** but we should only save one combination. If you choose the role of the current user then we must look for possible links on both assigned roles to links.

**Comment by ximex** [comment]
i think this could be a lot easier.
don't look on the sex (brother/sister). use only "sibling" and "parent" or "ancestor". the sex we get out of the sex property of the user (if defined)
maybe we should also add "boss" or something to add structures in companies etc

**Comment by Bullnados** [comment]
Wohoooo :+1: 
Is the relationship just in same organisation or also between different/more organisations?

**Comment by ximex** [comment]
I don't think that it would get into 3.1
But feel free to implement it @Bullnados ;-)

**Comment by Bullnados** [comment]
I'm in search of somebody which can do that, I can't php. But before starting this big thing, we/you specify the requirements.

**Comment by thomas-rcv** [comment]
Hi all,

I also thought about this issue several times.
I think to have an relationship between members is a specific situation we only have in family memberships, or let´s say I have no have further idea where we could need it.
But in a family role it definitely would make sense.
I´m not sure if it makes sense to delineate the complete structure with son, daughter, etc.

Like Ximex mentioned a parent sibling relationship would also be a good practice for me.
We could think about a hidden role, like we do for participation of events. The leader of the role, or several leaders are the “head” of the role ( Father and Mother )

From sight of the user, or having the right to edit user profiles, I could imaging to have an checkbox in the profile to assign myself as a family Master. Doing like that additional content will fade in for creating/editing further members, like children.
This could be a link to create a new profile. Linking to a new profile the hidden family role with User Id is created first.

In the new profile we would need to think about the profile fields that of course should be optional different. For children we often do not use a own Email address or account information or a login, etc.
Generally this example may only be a problem if the profile fields are defined as mandatory. 
In my opinion this would be the issue to figure out the system functionality for profile fields.

Regards,
Thomas

**Comment by ximex** [comment]
first we need a n:m splitting table (n and m are users) with about these fields:

id | self_id | to_id   |   type
--- | ------ | ------ | --------
 1 |     3   |    5    | parent

**Comment by thomas-rcv** [comment]
Hmm, I don´t think so.
Of course you´re right it would be a clear way and good practice to define exactly relationship within a table.
But , have a look at table roles, how we define a participation for dates. It is like a relationship as well. For sure, this way is a work around, but the question is how many ways we want to go in future? As descripted in my comment, we could go the same way and group a family in a role (hidden), or we can define it exactely as mentined by you, but then I would like to recommend to think about the actual stuff, regarding the participation of dates and also refactor it like you described with a table ....
For me it would be interesting what Fasse is thinking ....

**Comment by Bullnados** [comment]
I think all profile fields should be optional not only mail. We have bank account datas, which have to shown only for adults and some childspecific profile fields.  Would role specific profile fields an solution? F.e. u have the role
- members: adults and children are here, if u are a member of this role u have just two profile fields forename and lastname
- "member which pay": all members here have the profile fields bank account data
- "members which dont pay": honorary member, mebers >70 etc.
- "children": for us f.e. booking period
- etc....

Relationship between role and profile fields should be fully customizable of course.

**Comment by Fasse** [comment]
Ich wechsel jetzt mal die Sprache, da es hier doch jetzt weiterführende Gedanken gibt und wir in deutsch da besser vorankommen und es weniger Missverständnisse geben wird.

Für mich sind die Beziehungen zwischen Mitgliedern was anderes als Rollenmitgliedschaften. Aus diesem Grund bin ich sehr dafür, dass so abzubilden, wie @ximex das beschrieben hat, was auch meiner ursprünglichen Idee entsprach. Allerdings hatte ich da keine Zeit noch die Tabellenstruktur nieder zu schreiben. Mir war auch nicht bewusst, dass dieser Issue direkt so eine rege Teilnahme erzeugt, was ich aber gut finde :) 

Bei einer Rolle geht es darum, dass hier die Teilnahme an einer Rolle dokumentiert werden soll und auch Eintritt und Austritt. Hier geht es auch immer nur um 1 Benutzer, der 1 Rolle zugeordnet werden soll.
Bei den Beziehungen geht es immer um 2 Benutzer, die dann noch die Beziehungsrolle zugewiesen bekommen. Hier kommen wir mit unserer Members-Tabelle nicht weiter, da diese nicht für Beziehungen zwischen 2 Benutzern ausgelegt ist. 

Da es aus meiner Sicht somit inhaltlich 2 verschiedene Dinge sind, sollte das auch so im Datenmodell abgebildet werden. Es macht da keinen Sinn, die Members jetzt so umzubiegen, dass diese auch Beziehungen kann. Dadurch wird das Datenmodell nur komplizierter und schwer verständlich.

Bei den Terminen sieht es aus meiner Sicht wieder anders aus. Hier haben wir die klassische Zuordnung von 1 Benutzer zu 1 Termin und somit passt dort das vorhandene Datenmodell für Rollen auch.

@Bullnados Ich würde auch die Beziehungen nicht für Profilfeldfreigaben nutzen. Hier sollten wir zukünftig weiterhin die Rollen nutzen. Es ist auch fraglich, ob dein Szenario so Sinn macht. Der Grundgedanke ist mir schon klar, Eltern sollen andere Felder sehen, als Kinder, aber wenn du Beziehungen komplett pflegst und dein Vater ist auch noch im Verein, dann hättest du auch die Beziehung **Sohn** und falls du noch keine Kinder hast, wärst du nicht in der Beziehungsrolle **Eltern** und könntest somit die Felder nicht sehen. Somit ist aus meiner Sicht hier das Rollenmodell besser, bei dem du eine Rolle **Minderjährige** oder ähnlich anlegst und diese Rolle würde man dann Felder nicht sichtbar machen.

Soweit erst mal von mir zu diesem Thema. 
Ach ja, das Geschlecht aus bei der Konfiguration der Beziehungen bei den Benutzern rausnehmen, macht Sinn, aber diese Beziehungsrollen sollten trotzdem in der DB hinterlegt sein, so dass wir dann bei einem männlichen Benutzer, der dann die Beziehung **Eltern von** bekommt, automatisch **Vater von xyz** sichtbar hinterlegt bekommt.

**Comment by Bullnados** [comment]
Yeah deutsch, dass is gut :+1: 
Ich glaub wir reden etwas an einadner vorbei. Nicht die Beziehung legt die Profilfeldansicht fest, sondern zu welcher Rolle man gehört. Eine Möglichkeit, wie ich sie bei uns im Verein im Moment umsetze,ist die Unterteilung in zwei verschiedene Organisationen. Einmal für Eltern/Mitglieder und eine für Kinder.
Kinder:
![2015_10_20_19_40_05_kinder_profilfelder](https://cloud.githubusercontent.com/assets/11041576/10617597/a23d9552-776b-11e5-8b17-05cc7b5255e7.png)

Da ja Profilfelder innerhalb einer Organisation für alle Mitglieder/Kinder sichtbar wären hätte man so sehr lange Profile. Durch die Unterteilung in zwei Orgas konnte ich das Problem umschiffen. Nachteil ist, dass man beim Anlegen neuer Mitgleider erst die Eltern anlegt, sich ausloggen muss, in Kinderorag einloggen und dann Kind anlegen. Das ganze schaut bei uns jetzt so aus:



Eltern:

![2015_10_20_19_42_50_mitglieder_eltern_profilfelder](https://cloud.githubusercontent.com/assets/11041576/10617589/9acc78f6-776b-11e5-89b2-9031f4424eb8.png)


Nun gibt es imo 2 Möglichkeiten um nicht alle Felder bei Eltern oder Kind zu zeigen. Entweder man muss die zwei Orgas getrennt lassen und den Ansatz von Thomas ausm Forum umsetzen. Oder man führt zwei Arten von Profilfeldern ein.
- Globale Profilfelder, welche für alle Mitglieder gleich sind: Vorname und Nachname und/oder Geschlecht und/oder Wohnort. Diese werden der Rolle Mitglieder zugeordnet
- Profilfelder welche nur für bestimmte Rollen angezeigt werden. Bei der Rolle Eltern werden Kontodaten angezeigt bei der Rolle Kinder nicht und vice versa.

Auch das Problem Großvater-Vater-Sohn kann man so abbilden. Die Beziehung zwischen den Mitgliedern sollte ja nichts mit den sichtbaren Profilfeldner zu tun haben.

**Comment by Fasse** [comment]
Jetzt schweifen wir vom Thema dieses Issues ab. Profilfelder rollenabhängig sichtbar machen ist ein anderes Thema und ein eigener Issue. Dabei könnte man auch überlegen, ob man diese Rollenabhängigkeit nicht an eine Kategorie hängt um die Konfiguration zu erleichtern. 
Ich werde dazu mal einen Issue machen und dann verschieben wir deinen Post dorthin, damit hier nur die Beziehungen drin bleiben und man später nicht von all den Posts erschlagen wird ,wenn es dann zur Umsetzung kommt.

**Comment by Bullnados** [comment]
Jetzt wo du es sagst stimmt, aber diese zwei Dinge sind doch sehr eng verzahnt. Vielleicht seh ich das aber auch zu sehr aus der Sicht unseres Vereins.

**Comment by Fasse** [comment]
Es sind definitiv 2 unterschiedliche Funktionen, die aus meiner Sicht erst einmal wenig miteinander zu tun haben. Jeder Issue sollte nur 1 Thema (Funktion) behandeln, damit dies dann auch später schneller umgesetzt und auch besser spezifiziert werden kann. Je mehr Funktionen in einen Issue kommen, desto höher ist die Wahrscheinlichkeit, dass es nicht umgesetzt wird, da viel Arbeit. Lieber mehrere "kleinere" Issues und eine schnellere Umsetzung von kleinen Funktionen.

**Comment by thomas-rcv** [comment]
Jupp, bitte die Inhalte getrennt behandeln. Geb ich Fasse recht, man verliert den Überblick.
Was ich angemerkt habe bezieht sich auf die technische Sichtweise. Hier sind die Unterschiede eher marginal.
Eine Familie ist z.B. aus meiner Sicht ebenfalls eine Rolle. Richtig, es wird immer 1 Mitglied zu 1 Rolle zugeordnet. Zusammen haben Sie dennoch innerhalb der Rolle die Beziehung zueinander, da sie alle der Rolle angehören. Das eine Rollenmitgliedschaft ebenfalls ein Enddatum haben kann, finde ich innerhalb einer Familie auch nicht uninterssant. Eine Familienmitgliedschaft ist bei uns z.B. für Kinder bis 18 Jahre. Danach ist es eine Einzelmitgliedschaft. 
Sicherlich ist die Abbildung über eine Beziehungstabelle wohl der Beste Weg.
Es würde aber auch über eine Rolle funktionieren, die als versteckte Systemrolle angelegt wird.
DIese heisst dann z.B. family_38, wobei 38 dann die ID des Users ist, auf den die Rolle referenziert.
Wenn dann Mutter/Frau und zwei Kinder der Rolle zugeordnet sind, dann wäre das auch auf diesem Weg möglich. Die Frage ist, ob man die Konkreten Beziehungen zueinander Bruder-> Schwester, Vater -> Tocher , usw. explizit darstellen will und muss. Dann zweifellos mit Beziehungstabelle.

**Comment by Fasse** [comment]
Ich hätte jetzt gedacht, dass gerade die Art der Beziehung interessant ist. Bei Rollenzuordnungen fehlt dies Komplett, da weiß ich nur, dass sie in 1 Familie sind und andere Beziehungen kann ich nur über Geschlecht und Geburtstag herleiten. 
Beziehungen haben für mich einen Informativen Charakter. Ich will ein Profil aufmachen und direkt sehen, wer Bruder, Schwester, Vater oder Mutter ist. Diese User sind dann direkt auch verlinkt und ich kann so schnell zu ihnen kommen. Mehr muss am Anfang erst einmal garnicht möglich sein.
Natürlich kann man dann später diese Beziehungen noch weiter ausbauen. Z.B. dürfen Eltern die Profile ihrer Kinder editieren oder Eltern untereinander die Profile editieren. Aber sowas dann alles später.

**Comment by thomas-rcv** [comment]
Hab ich verstanden, Fasse.
Absolut d'accord.
An dieser Stelle vielleicht der Ansatz, diese Frage in unser Forum zu platzieren. Wie wird es gebraucht ... ? Macht diese konkrete Darstellung der Beziehung SInn oder nicht. Ich tue mich da gedanklich und ideenlos zugleich etwas schwer grad. Das hat aber nichts zu heissen ... :-D
Ich habe immer  auch die Plugins etwas im Hinterkopf, inwieweit die es dann betrifft.
Mitgliedsbeitrag ist z.B. vom Rollensystem abhängig ... wäre dann eher schade "rmb" einen Strich durch die Rechnung zu machen, wenn wir was an der Systemstruktur/Datenbankstruktur ändern, wenn es nicht zwingend gebraucht wird ...

**Comment by wilddom** [comment]
Ich habe mir einfach mal erlaubt, das kurz zu implementieren:
https://github.com/wilddom/admidio/tree/userrelations

Die Zuweisung und die Darstellung kann ist optisch noch verbesserungswürdig. Beziehungstypen können aus der Benutzerverwaltung angelegt werden und Beziehungen werden dann aus einem Profil heraus erstellt.

Vielleicht kann sich das mal jemand ansehen...

**Comment by Fasse** [comment]
@Wilddom: das werde ich mir auf jeden Fall mal anschauen, da ich diese Funktion sehr nützlich finde! 

"Kurz eingebaut" glaub ich nicht so ganz :D

**Comment by Fasse** [comment]
Ich habe mir jetzt mal den branch heruntergeladen. Beim Einrichten ist mir aufgefallen, dass du die Datenbankänderungen nur bei einer Installation durchführst und nicht bei einem Update. Das müsste man noch ergänzen.
Testen könntest du das mit [unseren Demodaten](http://admidio.org/dokuwiki/doku.php?id=en:entwickler:testumgebung_einrichten#upload_test_data). 
Eine Installation konnte ich gerade auf die Schnelle noch nicht machen, deshalb hab ich noch nicht weiter reingeschaut.

**Comment by wilddom** [comment]
Ja, richtig. Ich wusste nicht, welche Version ich benutzen sollte... so habe ich das mal auf später verschoben.

**Comment by Fasse** [comment]
Soweit ich das gesehen hatte, ist das im aktuellen Master eingebaut, dann kannst du die 3.2 nutzen.

**Comment by wilddom** [comment]
Okay, ich habe die Update-Steps eingebaut.

**Comment by Fasse** [comment]
Ich hab mir das jetzt mal angeschaut. Es sieht schon mal nicht schlecht aus. Von der Bedienung und der Darstellung ist es schon so, wie ich es mir vorgestellt habe.

Allerdings passt das Datenmodell aus meiner Sicht nicht. Ich habe jetzt versucht die klassischen Familienbeziehungen (Vater-Sohn, Mutter-Sohn usw.) darzustellen. Dies hat nachher dazu geführt, dass Sohn mehrfach auftauchte. Auch konnte ich dann nicht einstellen, wenn ich Sohn zugeordnet habe, welche Rolle (Vater oder Mutter) der aktuelle User bekam. Es fehlt die einfache Konfiguration, die Ximex im 2. Post beschrieben hat. 

Meiner Meinung nach brauchen wir 3 Tabellen:
**Beziehungsrollen**
Rolle: Elternteil     Männlich: Vater  Weiblich: Mutter
Rolle: Kind            Männlich: Sohn Weiblich: Tochter
Rolle: Ehepartner       Männlich: Ehemann Weiblich: Ehefrau
Rolle: Partner          Männlich: Freund  Weiblich: Freundin

**Beziehungskonfiguration**
Beziehung:  Elternteil   zu Kind
Beziehung:  Ehepartner zu Ehepartner
Beziehung:  Partner zu Partner

**Beziehungen**
User: Heinz Mustermann Beziehung: Kind  Beziehungsuser:  Paul Mustermann
User: Paula Mustermann   Beziehung: Elternteil  Beziehungsuser: Heinz Mustermann
User: Susanne Mustermann Beziehung: Ehepartner Beziehungsuser: Heinz Mustermann

**Profil von Heinz Mustermann**
Sohn Paul Mustermann
Tochter Paula Mustermann
Ehefrau Susanne Mustermann

So sähe dann eine Beispielkonfiguration aus. Wir definieren Beziehungsrollen, welche dann für Geschlechter die spezifische Beschreibung beinhalten. Ist die Geschlechterbeschreibung nicht gefüllt, dann würde nur der normale Beziehungsrollenname angezeigt.

In der Beziehungskonfiguration werden nur die allgemeinen Beziehungsrollen zusammengefügt, zu denen es Beziehungen geben kann.

Bei der eigentlichen Beziehungszuordnung ordnet man dann nur noch die Beziehungsrollen zu, zu denen es Konfigurationen gibt. Bei der Darstellung im Profil ist das Programm dann so intelligtent, dass es anhand des Geschlechts die richtige Zuordnung findet, dabei muss das Programm den User auf beiden Seiten der Beziehungszuordnung suchen. Fehlen bei Usern die Geschlechtzuordnung, dann wird einfach der allgemeine Beziehungsrollenname angezeigt. Also anstelle von **Sohn** steht dann dort **Kind**.

Aus meiner Sicht bräuchte man auch nicht die Beschreibung zwischen Einzahl und Mehrzahl. Wir brauchen eigentlich nur die Einzahl.

So ist das Beziehungsmodell aus meiner Sicht einfacher und flexibler. Mit deinem Datenmodell ist die Familienbeziehung doch komplizierter geworden. 

Was meinst du dazu?

**Comment by wilddom** [comment]
Eigentlich würde ich persönlich nicht zwischen Vater/Mutter unterscheiden, sondern eine neutrale Beziehung Elternteil-Kind erstellen. In meinem Fall hätte die Beziehungsbezeichnung somit eigentlich unique sein sollen. Aber okay, das könnte man auch bei der Zuordnung der Beziehung anders darstellen, das habe ich bisher ehrlich gesagt einfach nicht bedacht.

Das Geschlecht kann man grundsätzlich durchaus noch in den Beziehungstyp einbauen, wenn es das braucht. Eine weitere Tabelle ist dazu nicht nötig, oder?

Den Plural brauche ich im Profil, um z.B. mehrere Kinder unter einer Überschrift aufzulisten.

**Comment by ximex** [comment]
Also ich stimme @wilddom zu dass wir eine neutrale Bezeichnung für den Beziehungstyp in der DB speichern. Ob die SQL query dann mittels Logik mittels Geschlechtsangabe diese richtig darstellt ist mir egal.
@Fasse verstehe nicht warum wir 3 Tabellen brauchen? Sollte doch mit einer möglich sein (siehe 2. Post)

Das was für mich noch zu Diskussion steht ist:
Max <Kind von> => Franz <Ehepartner von> => Heidi
brauch ich dann auch eine Beziehung Max <Kind von> => Heidi ?
Oder wird das automatisch ermittelt oder automatisch erstellt?
Was passiert wenn ich habe:
Max <Kind von> => Franz
Franz <Eltern von> => Max

Also die frage ist haben wir einen gerichteten Graphen oder gehen die Beziehungen automatisch in beide Richtungen. Wenn in beide Richtungen: Sperren wir die Möglichkeit die 2 Beziehung aus der anderen Richtung zu erstellen oder filtern wir die 2 Beziehung in der Darstellung raus?

**Comment by wilddom** [comment]
> Also ich stimme @wilddom zu dass wir eine neutrale Bezeichnung für den Beziehungstyp in der DB speichern. Ob die SQL query dann mittels Logik mittels Geschlechtsangabe diese richtig darstellt ist mir egal.

Nachteil ist, dass die Benutzer verleitet werden könnten, mehrere Beziehungstypen für Mutter/Vater ↔ Sohn/Tochter zu erstellen.

> Das was für mich noch zu Diskussion steht ist:
Max => Franz => Heidi
brauch ich dann auch eine Beziehung Max => Heidi ?

Das kann man nicht allgemein beantworten, das hängt davon ab, was für Abfragen gemacht werden können sollen. Wenn du zum Beispiel Abfragen nach Grosseltern oder Urgrosseltern machen willst, wird es irgendwann komplex, die Beziehungen zu traversieren.

> Also die frage ist haben wir einen gerichteten Graphen oder gehen die Beziehungen automatisch in beide Richtungen. Wenn in beide Richtungen: Sperren wir die Möglichkeit die 2 Beziehung aus der anderen Richtung zu erstellen oder filtern wir die 2 Beziehung in der Darstellung raus?

Momentan wird die Beziehung immer in beiden Richtungen angelegt (A Kind von B, B Elternteil von A), das erleichtert vieles enorm. Mir ist einfach kein Fall in den Sinn gekommen, in der eine Beziehung in nur eine Richtung viel Sinn ergibt. Aber vielleicht hat jemand ein gutes Beispiel... Wobei eigentlich ist es über einen Trick schon umgesetzt, denn ein leerer Beziehungsname wird nicht angezeigt, das Feld wird bei der Eingabe aber noch als required angegeben.

> Was passiert wenn ich habe:
Max => Franz
Franz => Max

Momentan ist es möglich, dass Max das Kind von Franz und Franz das Kind von Max ist. Aber wenn das einer definiert, ist er meiner Meinung nach selber schuld ;)

**Comment by ximex** [comment]
@wilddom ups hab gemeint:
Max <Kind von> => Franz
Franz <Eltern von> => Max
Dadurch wäre eine beziehung auf einmal doppelt vorhanden

**Comment by ximex** [comment]
@wilddom github hat mir was von meinem text verschluckt. habs jetzt mit () anstatt <> gemacht

Das was für mich noch zu Diskussion steht ist:
Max (Kind von) => Franz (Ehepartner von) => Heidi
brauch ich dann auch eine Beziehung Max (Kind von) => Heidi ?
Oder wird das automatisch ermittelt oder automatisch erstellt?
Was passiert wenn ich habe:
Max (Kind von) => Franz
Franz (Eltern von) => Max

**Comment by Fasse** [comment]
@Ximex: ich denke, dass man das dann auch manuell definieren muss. Automatisch würde die Konfiguration komplexer.

**Comment by wilddom** [comment]
> Das was für mich noch zu Diskussion steht ist:
> Max (Kind von) => Franz (Ehepartner von) => Heidi
> brauch ich dann auch eine Beziehung Max (Kind von) => Heidi ?
> Oder wird das automatisch ermittelt oder automatisch erstellt?

Bei den heutigen Familienstrukturen kann man kaum mehr automatisch von Ehepartner auf Kind schliessen, oder? ;)

> Was passiert wenn ich habe:
> Max (Kind von) => Franz
> Franz (Eltern von) => Max

Eigentlich passiert nicht viel, es werden einfach in beiden Profile beide Links (Eltern, Kind zur gleichen Person angezeigt). Natürlich könnte man das verhindern, aber wenn das einer so definieren will...

**Comment by wilddom** [comment]
Ich werde die geschlechtsabhängigen Bezeichnungen einführen. Aber wenn ich dafür jetzt an der Datenbank Änderungen machen will, was soll ich mit meinen bereits erstellen Update-Steps machen, die ich ändern müsste? Soll ich vom Master ausgehen oder von meinen bereits erstellen Änderungen?

**Comment by ximex** [comment]
ändere die update steps einfach. Sie müssen nur passen für einen wechsel von 3.1 auf 3.2.

**Comment by wilddom** [comment]
Gibt es eine zuverlässige Methode, das Geschlecht zu bestimmen? Das ist ja eigentlich ein frei definierbares Feld und ich kann mich deshalb nicht wirklich auf die Reihenfolge verlassen. Oder sehe ich das falsch?

**Comment by Fasse** [comment]
@Widdom: Schön, dass du es anpassen willst, aber es ist jetzt nicht zwingend erforderlich , wir hätten es auch mit der nicht geschlechtsspezifischen Konfiguration aufgenommen. Ich finde aber die Möglichkeit der geschlechtsspezifischen Konfig super :) Aber überdenk bitte noch mal den Plural, der ist m.M. überflüssig, da man dies einfach bei der Ausgabe anders darstellen könnte.

**Comment by wilddom** [comment]
@Fasse Ja, den Plural lasse ich weg, wird sonst zu kompliziert. Nur... siehe meine vorherige Frage, wie kriege ich das Geschlecht?

**Comment by Fasse** [comment]
@wilddom Entweder über die User-Klasse `$user->getValue('GENDER')` oder über SQL mit einem JOIN `     LEFT JOIN '.TBL_USER_DATA.' AS gender
            ON last_name.usd_usr_id = usr_id
           AND last_name.usd_usf_id = '.$gProfileFields->getProperty('GENDER', 'usf_id').'`

**Comment by wilddom** [comment]
Okay, habe das geändert. Die Erstellung einer Beziehung zwischen zwei Benutzern ist aus meiner Sicht noch immer nicht ideal, weil nicht ganz klar wird, aus welcher Sicht die Beziehung erstellt wird, aber ich finde irgendwie einfach keine passenden Texte.
https://github.com/wilddom/admidio/tree/feature-userrelations

**Comment by Fasse** [comment]
Ich kann es leider gerade nicht testen, da mit PHP 5.3 das Login nicht funktioniert.
https://github.com/Admidio/admidio/issues/377

Ich hab zwar gedacht alles bei mir umgangen zu haben, aber Login funktioniert immer noch nicht :(

**Comment by Bullnados** [comment]
Schön das es hier vorangeht.

**Comment by Fasse** [comment]
@wilddom jetzt konnte ich es mir mal anschauen. Die Anpassungen finde ich sehr gut. Elternteil - Kind Konfiguration hat jetzt auf Anhieb so funktioniert, wie ich es mir vorgestellt habe.

Probleme habe ich jetzt bei Geschwister oder Partner. Hier sind die Vorwärts-Rückwärts-Kombinationen identisch, was aktuell zu einem SQL-Fehler führt.

Auch gefällt mir Vorwärts/Rückwärts als Bezeichnung noch nicht so gut.

Und ein Letztes noch, wir sollten diese Funktion über eine Einstellung abschaltbar machen. Also in der Profilkonfig eine Schaltfläche **Beziehnungen pflegen**, welche im Standard aktiv ist.

**Comment by wilddom** [comment]
Stimmt, Beziehungen, die in beiden Richtungen gleich sind, also die gleichen Bezeichnungen verwenden, habe ich nicht bedacht. Schau ich mir an.

Für Vorwärts/Rückwärts nehme ich gerne Vorschläge entgegen ;)

Eigentlich habe ich doch in den Preferences 'profile_show_user_relations' eingeführt. Oder fehlt da noch was?

**Comment by Fasse** [comment]
Ich muss ganz ehrlich sagen, dass ich da garnicht reingeschaut habe :( Die Idee kam mir beim Schreiben des Posts oben. Jetzt sehe ich ihn auch. Vielleicht sollte man das noch umbenennen in **Beziehungen pflegen und anzeigen** und wenn der Haken nicht gesetzt ist, auch die Menüpunkte entfernen und auch in den Scripten die Ausgabe verhindern.

Vorwärts/Rückwärts könnte man auch in der Betaphase mit allen _Testern_ dann diskutieren. So direkt fällt mir nämlich auch nichts Gutes ein.

**Comment by wilddom** [comment]
So, jetzt gibt es symmetrische (z.B. für Geschwister) und unidirektionale Beziehungen (vielleicht braucht es jemand). Bestehende Beziehungstypen können aber nicht umgewandelt werden.

**Comment by wilddom** [comment]
Noch eine Frage: Was für ein Verhalten erwartet ihr, wenn ein bestehender Beziehungstyp gelöscht werden soll, von dem Beziehungen in der Datenbank existieren? Sollen die bestehenden Beziehungen gelöscht werden oder soll das Löschen verhindert werden? Was ist üblich resp. was ist sich der Benutzer von Admidio gewohnt?

**Comment by Fasse** [comment]
In der Regel löschen wir die abhängigen Datensätze mit. 

Einzig bei den Kategorien muss diese vorher leer sein, damit diese gelöscht werden kann, da hier das Risiko zu Hoch ist, dass jemand mal eben eine Kategorie löscht und dabei dann x-Termine oder x-Ankündigungen.

Bei den Beziehungen würde ich es dir überlassen, auch hier könnte man sagen, dass man nur Beziehungstypen löschen kann, zu denen es keine Einträge gibt. Das musst du aber abwägen, ist ja auch etwas umständlicher einzubauen.

**Comment by Fasse** [comment]
So ich habe jetzt noch mal Zeit gefunden mir die Funktion anzuschauen. Ich finde sie jetzt wirklich gelungen und gut bedienbar. Wenn du noch die paar Kleinigkeiten behoben hast, kannst du gerne einen Pull-Request stellen. Dann würde ich mir auch noch mal den Code anschauen.

Ein paar Kleinigkeiten sind mir noch aufgefallen:
- sind keine Beziehungstypen definiert, kann ich dennoch im Profil den Dialog aufrufen. Hier sollte im Dialog ein Hinweis kommen, dass ich erst Beziehungstypen definieren muss.
- im Hinweis vor dem Löschen wird noch ein Slash angezeigt
- vielleicht sollte man noch einen Erklärungstext bei der Beziehungstypauswahl hinzufügen, der die 3 Einstellungen jeweils kurz in einem Satz erklärt.
- ich kann den Haken in den Profileinstellungen nicht entfernen, dass keine Beziehungen mehr gepflegt werden sollen. Wahrscheinlich hast du in der preferences_function.php dort die neue checkbox id nicht mit aufgelistet, so dass die initialisiert wird
- in der eigenen Liste gehst du noch irgendwo fix auf das adm Präfix der Tabellen. Ich habe ein anderes Präfix und bekomme dann folgenden Fehler: `Table 'admidio_test.adm_user_relations' doesn't exist`

**Comment by wilddom** [comment]
Danke fürs Feedack, sollte jetzt alles korrigiert sein.

**Comment by ximex** [comment]
@wilddom könntest du über deine änderungen noch mit dem PHP-CS-fixer drübergehen?
```bash
wget http://get.sensiolabs.org/php-cs-fixer.phar -O php-cs-fixer.phar
php php-cs-fixer.phar fix --config-file=".php_cs" --verbose
```

**Comment by Fasse** [comment]
Ich habe jetzt noch mal getestet, dabei sind mir folgende Dinge aufgefallen:
- Funktion deaktiviert, Links usw. waren weg, allerdings konnte ich die Scripte zur Pflege von Beziehungen trotzdem direkt aufrufen. Hier sollte dann ein Hinweis erscheinen, von mir aus ein allgemeiner, dass der Aufruf ungültig ist.
- wir sollten ein paar Beziehungen im Standard mit ausliefern. Diese sollten immer bei einer Neuinstallation angelegt werden, sowie beim Update auf Version 3.2 . Beziehungen, die man ausliefern sollte wären m.M.: Elternteil - Kind; Partner; Ehepartner; Freund

**Comment by ximex** [comment]
Dann würd ich noch Vorgesetzter und Geschwister mit aufnehmen

**Comment by wilddom** [comment]
Als Beispiel für die Verwendung wären Standardbeziehungen sicher sinnvoll. Aber diese müssten ja dann auch in allen Varianten (neutral/männlich/weiblich) übersetzt werden, oder? Wollt ihr das wirklich?

**Comment by Fasse** [comment]
Warum denn nicht? Ich finde das sehr sinnvoll, außerdem hat dann schon jeder Vorlagen, wie das mit den Beziehungen funktioniert.

**Comment by wilddom** [comment]
Okay. Andere Frage: Momentan sind sie Beziehungenstypen global. Ist das okay oder sollten sie zu einer Organisation gehören?

**Comment by Fasse** [comment]
hab ich auch mal drüber nachgedacht, aber ich fand es jetzt global garnicht mal so schlecht. eigentlich sind beziehungen ja meistens allgemeingültig und so auch für mehrere Orgas brauchbar und es muss nicht jeder z.B. die Familienbeziehungen konfigurieren.

**Comment by wilddom** [comment]
Wo gehören denn diese Standarddaten hin im Fall von Installation und Update?

**Comment by ximex** [comment]
Warum braucht man die Geschlechter Varianten? Neutral ala Eltern/Kinder anstatt Vater/Sohn sollte doch reichen

**Comment by Fasse** [comment]
Weil wir eine fertige Konfiguration ausliefern wollen. Du baust doch auch kein Auto ohne Sitze :)

Es gibt jetzt 2 möglichkeiten dies einzubauen:
- Nur die Übersetzungstring einsetzen, sowie bei den Kategorien
- den übsetzten Text selber einsetzen, sowie bei den Profilfeldern

Ich persönlich finde die Variante bei den Kategorien besser da dann die Texte auch beim Wechsel der Sprache angezeigt werden und wenn wir zukünftig die Sprache auch benutzerabhängig machen wollen, dann sowieso.

Bei der Installation würdest du es hier einbauen: https://github.com/Admidio/admidio/blob/master/adm_program/installation/installation.php#L687

Beim Update würdest du es bei der Kategorievariante einfach als INSERT-Statement im Updatescript einbauen. Bei der anderen Variante müsstest eine Funktion aufrufen, damit du die Texte mit $gL10n übersetzen kannst.

Bei der Kategorievariante müsstest du dann natürlich die Texte vor der Anzeige immer übersetzen, falls ein Übersetzungsstring drin steht.

**Comment by wilddom** [comment]
Ich wollte es zuerst analog den Kategorien machen, aber der Unterschied ist, dass Kategorien eine einstellbare Reihenfolge haben. Hingegen gebe ich die Beziehungstypen jeweils alphabetisch sortiert aus, was mit den Übersetzungsstrings in der Datenbank halt nicht mehr funktionieren würde.
