### ISSUE TITLE
Replace DateTimeExtended with DateTime

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#196]
Since we have problems with special date or time formats we should only use DateTimeExtended if we want to use the special methods of DateTimeExtended. Otherwise we should use PHP class DateTime.

**Comment by ximex** [comment]
The DateTimeExtended Class is already refactored in v3.1.
This problem is only in v3.0.
Look here: https://github.com/Admidio/admidio/blob/master/adm_program/system/classes/datetimeextended.php
We already use this method to create a date: DateTime::createFromFormat($format, $date);

**Comment by Fasse** [comment]
Ok, you're Right.
