### ISSUE TITLE
Possibility to configure time zone for current installation

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#198]
We should add the possibility to set the time zone of the current organization and save this in the config.php.  

Now it's only possible to edit code in the constant.php if you want another time zone than our default **Europe**.

Within the installation prozess we should add a dropdown field at the organization dialog where you can choose one of [these time zones](http://de2.php.net/manual/en/timezones.php) of the organization. This information should be stored in the config.php als new optional parameter.

With this we are backward compatible and if the parameter is not set than we still use **Europe** as default.

**Comment by ximex** [comment]
:+1:
