### ISSUE TITLE
PSR-4 Autoloading

### ISSUE THREAD

**Issue by ximex** [Admidio/admidio#208]
Switch to the PSR-4 Autoloading Standard
http://www.php-fig.org/psr/psr-4/

**Comment by ximex** [comment]
requires #209 first

**Comment by ximex** [comment]
Example: https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-4-autoloader-examples.md

**Comment by ximex** [comment]
requires #644 first

**Comment by Fasse** [comment]
#1716
