### ISSUE TITLE
Using Namespaces

### ISSUE THREAD

**Issue by ximex** [Admidio/admidio#209]
To avoid conflicts with classnames of other libs and better logical structure we should use namespaces.
https://secure.php.net/manual/en/language.namespaces.php

**Comment by thomas-rcv** [comment]
If we finished the API we should definitly use it to avoid trouble shooting.
At the moment in my opinion it is not important. The only thing would be an issue if Admidio is implementet in a modern CMS, but we removed the classic theme ... so it is not really useful

**Comment by Fasse** [comment]
A possible structure for namespaces:
classes\Core\Session. ...\Component  ...\AdmException. ..\Navigation. ...\Message. ...\Language
classes\Html\HtmlPage ...\HtmlTable. ...\HtmlForm. ...\Menu
classes\Modules\Modules. ...\ModuleDates
classes\Utils\StringUtils.  ...\FileSystemUtils
classes\Users\User. ...\UserImport.  ...\TableUserField

Where to add classes like Tablephotos , TableCategory or ListConfiguration?

After use of namespaces should we rename classes? e.g. `AdmException` to only `Exception`?

**Comment by ximex** [comment]
i think we should but all classes that extends `TableAccess` in the same directory.
And to Exceptions. I think we should use more of the already defined exceptions: https://www.php.net/manual/en/class.exception.php
