### ISSUE TITLE
Rename folder db_scripts

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#21]
We should rename the folder db_scripts. When I create that folder it should contain several scripts for admidio. But now its only use is to set a Admidio enviroment with test data.

My favorite names are:
test_data
demo_data
example_data

What did you think?

**Comment by ximex** [comment]
in issue #13 i wrote about a testing framwork. i think this belongs together. If we have tests we need testdata too.
Other projects mostly have a `test` folder where this test cases are stored.

**Comment by Fasse** [comment]
Ok, but our folder only contains a set of data for Admidio to show a demo version. So it would be better we call it demo_data or example_data.

For test cases we could create a new folder.

**Comment by ximex** [comment]
ok in this case i also prefer `demo_data`

**Comment by Fasse** [comment]
I changed it to demo_data

**Comment by ximex** [comment]
there are no images any more in the folder. is this right?
i asked about this in #18

**Comment by Fasse** [comment]
Thanks for the hint. This was because of an incorrect syntax in .gitignore
Now its there.
