### ISSUE TITLE
Translate README.md to english

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#22]
Since the focus of this project should be more international we should translate the readme.md to english. Also the credits list should be updated.
@ximex

**Comment by ximex** [comment]
sry don't know only one person could be assigned to a issue ;-)
i will help to fix this

**Comment by Fasse** [comment]
First version is online. Need to write a chapter about contribution.
Maybe @ximex and @sirnone you can have a look at the readme now.
If you have ideas to improve it, just write me.
