### ISSUE TITLE
White Page creating/editing events

### ISSUE THREAD

**Issue by thomas-rcv** [Admidio/admidio#220]
Saving dates occurs White page.
In case of that several roles for a date are also created for example.

**Comment by Fasse** [comment]
I could not reproduce this in demo.

**Comment by thomas-rcv** [comment]
Try with IE under Windows. Problem can be reproduced in the demo.

**Comment by Fasse** [comment]
found the problem. But this should be within 3.0 since the beginning. Maybe a new IE patch make the problem. Now it's solved also for IE.
