### ISSUE TITLE
Captcha not checked if user wants to get a new password

### ISSUE THREAD

**Issue by thomas-rcv** [Admidio/admidio#221]
See Forum:
http://admidio.org/forum/viewtopic.php?f=3&t=6718

 Captcha input is not checked and the email will always be send to the user.

**Comment by Fasse** [comment]
@thomas-rcv  ups sorry don't see that you was assigned. Now it's fixed.

**Comment by thomas-rcv** [comment]
No Problem at all. I just forgot to commit yesterday evening :D
