### ISSUE TITLE
Prevent session hijacking by IP validation

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#227]
In addition to your cookie check at every script execution we should also check if the session id of the cookie belong to the same remote ip address.
Therefore we can use $_SERVER['REMOTE_ADDR']. The ip address is already stored in the session table and could be validated. 

With this enhancement session hijacking is not as easy as now.

**Comment by Fasse** [comment]
This should be an optional feature. Default should be activated.

**Comment by ximex** [comment]
per user or per organization? i prefer per organization

**Comment by Fasse** [comment]
Yep, Organisation.

**Comment by Fasse** [comment]
The preference will be a config.php parameter because we have the session handling before we load data from database.

**Comment by Fasse** [comment]
Still need to document the parameter here:
http://www.admidio.org/dokuwiki/doku.php?id=de:2.0:konfigurationsdatei_config.php

**Comment by Fasse** [comment]
done
