### ISSUE TITLE
Remove v2.x install/update/fallback code

### ISSUE THREAD

**Issue by ximex** [Admidio/admidio#231]
Remove all Code that is only necessary for v2.x installation or updating or fallback.
There are many update scripts to cleanup.

To Update from 2.x to 4.x: 2.x -> 3.x -> 4.x

**Comment by Fasse** [comment]
Wie should talk about this before wie Remote update possibilities from version 2. It depents on the release Time of version 4. in we release version 4 in 2017 it is to early to Remove it.

**Comment by ximex** [comment]
Why is it to early? e.g Firefox does the same. Mostly you couldn't update from a very old firefox to the newest. If someone stays sooo long on a so old version he/she could also do the update in two steps.
I hate this update refusenik ;-) they make the life of us (programmer/sys admins/...) harder...

**Comment by ximex** [comment]
Now we have 2018 ;-) And the release will be earliest in 2018Q3. Could we drop the code?
v3.3 is a LTS release. So if someone still hast a v2.x => update to v3.3 and than update to v4.x

**Comment by ximex** [comment]
Most of the v2.x code should be removed now. I will search again if i found some remaining code

**Comment by ximex** [comment]
couldn't found any more
