### ISSUE TITLE
Add field for "gestorben am"/died

### ISSUE THREAD

**Issue by sistlind** [Admidio/admidio#248]
Often a member of a society quit his membership not until his death. Therefore, admidio should have a fixed (SYSTEM)-Variable, which keep this information.

This is a crucial Information for the core system and also plugins (e.g. statistic, birthday, mitgliedsbeitrag).

Best regards,
Stefan

**Comment by Fasse** [comment]
I don't know why this should be a default field. I think most of the orgas will end the membership and don't want to maintain such a field.

**Comment by sistlind** [comment]
Just a few useful examples:
 1. The birthday plugin shows in the standard configuration also dead people, if no role-filter is applied.
 2. It could be, that a member could only leave the organisation at the end of a year
 3. At the annual general meeting there should be a statistic of former members divided by dead and withdrawn members.

This can be all be done by a self declared field in the database, nevertheless, i think that this field is crucial enough to define it as a standard field, becaue only in that way plugins can handle that.
In this way it could also be auto-linked to auto-end the membership at the same date or at the end of the current year.

Up to now i have to check often the database, if the data of dead people is correctly entered(filling day of death and quit membership).

I could also prepare a pull request for this topic.

Best regards, 
Stefan

**Comment by Fasse** [comment]
We will not add this field to the default configuration. 

As mentioned above you can finish membership assignment or remove user from your organization. 

Also it's possible to add such a field for your own organization.
