### ISSUE TITLE
Default name of Admin(Webmaster) group

### ISSUE THREAD

**Issue by sistlind** [Admidio/admidio#249]
Hi,
the webmaster(taking care about the homepage) of an organization is often not the same Person, which is responsible for the member management.

Therefore, i suggest to rename the default admin role webmaster to "Admin", "Admidio-Admin", root, or sometinge else.

Best regards,
Stefan

**Comment by Fasse** [comment]
:+1:  good idea. Maybe we should use **Administrator** and not a shortcut

**Comment by sirnone** [comment]
I think we should splitt the "webmaster" and the "members_admin"!
for an admin it is better to use the short name, because in other languages the administrator ist written different (french: administrateur)

**Comment by thomas-rcv** [comment]
I would also agree. The webmaster is doing the Installation while Administrators can do the Settings, like in the phpbb.
Therfor I would eg split the function download database backup to the webmaster role and not for Administrator Group. Also some organization settings like the page forwarding for the landing pages. Maybe there would be some more issues.

**Comment by Fasse** [comment]
Do wie really Need two roles "Webmaster" and "Admin"? This Will made the whole Thing more complicated.

**Comment by thomas-rcv** [comment]
That's right :)
You know me ... just brainstorming.
But at this time it also would be ok just rename it

**Comment by ximex** [comment]
Admin :+1:

**Comment by Fasse** [comment]
What do you think should be the new role name:
**Administrator** or **Administrators**

**Comment by ximex** [comment]
**Administrator**

**Comment by Fasse** [comment]
Remember that the other roles addresses multiple persons e.g. **members** or **Association's board**

**Comment by ximex** [comment]
if you look at demo.admidio.org:
- Webmaster and not Webmaster**s**
- Vorstand and not Vorstände

only:
- Mitglied**er** and not Mitglied
