### ISSUE TITLE
No check of valid sender email when not logged in 

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#254]
http://forum.admidio.org/viewtopic.php?f=3&t=6767

**Comment by sirnone** [comment]
why you don't use the input type email? then there is a check in the browser directly before the send.

**Comment by Fasse** [comment]
We always need a server check of input data. Only this check can garantee a defined status. Browser checks are also useful, but depends on browser and if someone want to hack us than only server checks protect the database.
