### ISSUE TITLE
SQL Error - Show List

### ISSUE THREAD

**Issue by ximex** [Admidio/admidio#258]
Infos:
- Admidio-Version: 3.0.6
- Letzter Update-Schritt: 610
- PHP-Version: 5.5.9-1ubuntu4.14
- MySQL-Version: 10.0.20-MariaDB-1~trusty-log

URL: `https://www.example.org/adm_program/modules/lists/lists_show.php?lst_id=6&mode=html&show_members=0`
```
S Q L - E R R O R

CODE: 1064
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') AND rol_cat_id = cat_id AND ( cat_org' at line 3

B A C K T R A C E

FILE: adm_program/system/classes/dbmysql.php
LINE: 67
CALL: DBCommon->db_error()

FILE: adm_program/system/classes/dbmysql.php
LINE: 202
CALL: DBMySQL->db_error()

FILE: adm_program/modules/lists/lists_show.php
LINE: 135
CALL: DBMySQL->query()
```

If go back and create the same list it works again. I think this happens if i refresh the open tab after long time again. Maybe a session problem? Didn't look into the code in detail yet

**Comment by ximex** [comment]
lists_show.php L135
`$mainSql` String:
```sql
SELECT mem_leader, usr_id, row1id1.usd_value, row2id2.usd_value, row3id44.usd_value
FROM adm_roles, adm_categories, adm_members, adm_users
LEFT JOIN adm_user_data row1id1
ON row1id1.usd_usr_id = usr_id
AND row1id1.usd_usf_id = 1
LEFT JOIN adm_user_data row2id2
ON row2id2.usd_usr_id = usr_id
AND row2id2.usd_usf_id = 2
LEFT JOIN adm_user_data row3id44
ON row3id44.usd_usr_id = usr_id
AND row3id44.usd_usf_id = 44
WHERE rol_id IN ()
AND rol_cat_id = cat_id
AND ( cat_org_id = 1 OR cat_org_id IS NULL )
AND mem_rol_id = rol_id
AND mem_begin <= '2015-12-22'
AND mem_end >= '2015-12-22'
AND mem_usr_id = usr_id
AND usr_valid = 1
ORDER BY mem_leader DESC , row1id1.usd_value ASC
```

**Comment by ximex** [comment]
The problem is here:
```php
// lists_show.php L37-45

if($getRoleId > 0)
{
    $role_ids[] = $getRoleId;
}
else
{
    $role_ids = $_SESSION['role_ids'];
    $getRoleId = $role_ids[0];
}
```

`$getRoleId` isn't set and `$_SESSION['role_ids']` is `NULL`

**Comment by Fasse** [comment]
but why do you call the list module and don't set any role?

You must set the parameter rol_id or within the session.

**Comment by ximex** [comment]
Ok i found where we miss to set the `rol_id`.
```javascript
// modules/list/mylist.php L468
document.getElementById("mylist_configuration_form").action  = gRootPath + "/adm_program/modules/lists/mylist_function.php?mode=2";
```
We have to add the selected `rol_id`
```javascript
// modules/list/mylist.php L468
var roleId = document.getElementById("role_id").value;
document.getElementById("mylist_configuration_form").action  = gRootPath + "/adm_program/modules/lists/mylist_function.php?mode=2&role_id=" + roleId;
```

**Comment by Fasse** [comment]
no this should not be done because within mylist_configuration we set the role ids from the selectbox.
Please describe the scenario were you get the error.

Do you get the error in 3.1 or in 3.0.6 or in both?

**Comment by ximex** [comment]
After a skype talk we found the problem:
```php
// modules/lists/mylist_function.php L109-113
// save all roles in a session parameter for later use
$_SESSION['role_ids'] = $_POST['sel_roles_ids'];

// weiterleiten zur allgemeinen Listeseite
header('Location: '.$g_root_path.'/adm_program/modules/lists/lists_show.php?lst_id='.$list->getValue('lst_id').'&mode=html&show_members='. $_POST['sel_show_members']);
```
```php
// modules/lists/lists_show.php L60-68
if($getRoleId > 0)
{
    $rolesIds[] = $getRoleId;
}
else
{
    $rolesIds = $_SESSION['role_ids'];
    $getRoleId = $rolesIds[0];
}

// And following "$getRoleId"

**Comment by ximex** [comment]
only change/fix this in 3.1

**Comment by ximex** [comment]
did i see this right? a `roleId` is always required.
-> `getRoleIds` should never be "" ("1", "2,4", ...)

**Comment by ximex** [comment]
@Fasse please check if all is correct

**Comment by Fasse** [comment]
* There are some more places where lists_show.php is called.
* `$_SESSION['role_ids']`could be removed

I will add a message later...

**Comment by ximex** [comment]
@Fasse found 3 more

**Comment by Fasse** [comment]
also have a look at variable `$roleIdLink` in lists_show.php 
I think this variable isn't need anymore if we use the new parameter.

**Comment by ximex** [comment]
some more work for `$roleIdLink` and the missing error message in **lists_show.php L61** has to be done

**Comment by Fasse** [comment]
done
