### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by ximex** [Admidio/admidio#26]
So we could move most of the infos from (http://admidio.org/dokuwiki/doku.php?id=de:entwickler:index) directly in this repository.

Example: https://github.com/openlayers/ol3/blob/master/CONTRIBUTING.md

**Comment by Fasse** [comment]
I'm not shure if a separate contributing file is necessary. I want to include a short chapter in the readme and this should to it. All other informations should be written in the wiki.
