### ISSUE TITLE
Validate email check won't work correct

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#264]
The following email will be validated as incorrect email through the new check methods:
adjsfhjdasfhlaksjfhjksvbnjkdsnknsdjknsfhasjfhsdjnasfhadjksfhjashfjkdsahfkjasdfhjksahf@test.de

**Comment by ximex** [comment]
it's from the `filter_var(trim($string), FILTER_VALIDATE_EMAIL)` part.  The FILTER_VALIDATE_EMAIL uses a strange regex...
https://github.com/php/php-src/blob/71c19800258ee3a9548af9a5e64ab0a62d1b1d8e/ext/filter/logical_filters.c#L601
don't know what we should do. remove the new check?

**Comment by Fasse** [comment]
if it won't work as expected than we should remove the check. But we have also our regex. that will check the email.

**Comment by ximex** [comment]
i did some more tests. It doesn't work if (x@y.z):
- the string before the @ sign is longer than 64 chars (x)
- the string between the @ sign and the . is more than 63 chars (y)
- the string after the . is more than 63 chars (z)

this means with this filter the max string length is 64+1+63+1+63=192 chars.

Wikipedia Länge der E-Mail-Adresse
> Im RFC 5322 
gibt es keine eigene Längenbegrenzung für E-Mail-Adressen, nur die allgemeine Begrenzung von Zeilen auf eine maximale Länge von 998 Zeichen. Allerdings werden im RFC 5321 
, der das SMTP-Protokoll definiert, die maximale Länge des Local-Parts mit 64 und die maximale Länge des Domainnamens mit 255 Oktetten angegeben (ein Oktett ist auf den meisten Computern identisch mit einem Byte). Zusammen mit dem @-Zeichen ergäbe sich daraus die maximale Länge einer E-Mail-Adresse von 320 Oktetten. Allerdings ist im RFC 5321 
auch die maximale Länge des „Path“-Elements definiert, das die Elemente „FROM“ und „RCPT TO“ im Envelope bestimmt und die maximale Länge von 256 Oktetten einschließlich der Separatoren „<“ und „>“ hat. Daraus ergibt sich eine maximale Länge der E-Mail-Adresse von 254 Oktetten einschließlich des „@“. Eine längere Adresse kann über RFC-konforme SMTP-Server weder E-Mails versenden noch empfangen.

this means the validation of the x part is correct.

to get the full length of 254 chars it is possible to add an email address in format x@y.z.a
x=64
y=64
z=64
a=62

i think the validation is correct an no change is required!

**Comment by ximex** [comment]
waiting for @Fasse input ;-)

**Comment by Fasse** [comment]
ok, if my example is not a valid email address, than the check if ok. I didn't know the fact with the 64 chars.

Is this check `preg_match('/^[^@]+@[^@]+\.[^@]{2,}$/', trim($string))` already done by the function than we can remove it.

**Comment by ximex** [comment]
the other check is stricter than this check ;-)
