### ISSUE TITLE
Wrong column adjustment if profilefields not visible for members

### ISSUE THREAD

**Issue by thomas-rcv** [Admidio/admidio#271]
If a list configuration contains profilefileds with property "only visible for users with rights", the column adjustment doesn´t fit in the datatable. There we have problems with the cellspacing to the headline. 
In case of the profile field "lastname" the problem extends also to the own list configuration. 
The first line would be empty and this would throw an error message.

See Forum:
http://www.admidio.org/forum/viewtopic.php?f=3&t=6788

![demo-organisation - liste - mitglieder - mozilla firefox_2016-01-03_22-06-09](https://cloud.githubusercontent.com/assets/10371197/12080809/cbee4db0-b267-11e5-850d-6a56562c9cf3.png)

![demo-organisation - eigene liste - konfiguration - mozilla firefox_2016-01-03_22-06-42](https://cloud.githubusercontent.com/assets/10371197/12080816/e01cd068-b267-11e5-95ee-39f730e90215.png)

![demo-organisation - hinweis - mozilla firefox_2016-01-03_22-07-11](https://cloud.githubusercontent.com/assets/10371197/12080817/e9dcf36c-b267-11e5-9a44-db59c5d0838e.png)

**Comment by thomas-rcv** [comment]
@ Ximex
Please have a look if the cs-fixer is working correctly within this commit.

I don´t understand why it set a dot point in the remark field at the beginning of the script.
Do we cancel the brackets within a require_once statement?

**Comment by ximex** [comment]
@thomas-rcv this looks strange. it looks like you have ALL fixes enabled or something else.

**Comment by thomas-rcv** [comment]
I used the config file as recommended by you.
It is the config file out of the branch 3.1

Hmm don´t know where the Problem is. 

This was my command:

php php-cs-fixer.phar fix --config-file="C:\xampp_1.8.3\htdocs\Admidio-Branches\admidio.php_cs" --verbose --dry-run C:\xampp_1.8.3\htdocs\Admidio-Branches\admidio\adm_program\modules\lists\lists_show.php

**Comment by ximex** [comment]
should be: `php php-cs-fixer.phar fix --config-file="C:\xampp_1.8.3\htdocs\Admidio-Branches\admidio\.php_cs" --verbose --dry-run C:\xampp_1.8.3\htdocs\Admidio-Branches\admidio\adm_program\modules\lists\lists_show.php`

look at the \ between admdio and .php_cs

**Comment by thomas-rcv** [comment]
ok, i see.
how to repair now?

**Comment by ximex** [comment]
best is a revert of this commit and do the changes again

**Comment by Fasse** [comment]
yes revert will be good.

**Comment by thomas-rcv** [comment]
ok, will try later.

Do a check again before the commit?

**Comment by Fasse** [comment]
maybe first commit only your changes than do the check and have a look at the changed lines if there are always so many lines than you should be skeptical and not commit again.

**Comment by thomas-rcv** [comment]
Yes, of course.
Will do it later. I´m off now ;)
