### ISSUE TITLE
Update Readme.txt in Plugins

### ISSUE THREAD

**Issue by ximex** [Admidio/admidio#276]
We should update the Readme.txt from the Plugins.
Best is to also convert them into Markdown files and translate them into english

**Comment by ximex** [comment]
content update and translation to english done: 4b3528397f3db98398a4c9bbf1fd36541a503773
@Fasse Convert to Markdown?

**Comment by Fasse** [comment]
Oh I dont know this issue :)

I think we do not need markdown. Everyone knows a txt but not everyone knows a md file.
