### ISSUE TITLE
$g_tbl_praefix -> $gTablePrefix

### ISSUE THREAD

**Issue by ximex** [Admidio/admidio#278]
i think this is back from german variable names.
Change: `$g_tbl_praefix` into `$g_tbl_prefix`

**Comment by Fasse** [comment]
If we really want to change this, than we should use **$gTablePrefix**

**Comment by ximex** [comment]
We already added a const TABLE_PREFIX
https://github.com/Admidio/admidio/commit/c7a82503eb90a66d431e708c240859d402ea3c67
