### ISSUE TITLE
To-field will not be preassigned on back navigation

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#284]
If you will forget to fill one field in the message dialog and than Admidio (not the browser) will prompt to fill that field. If you navigate back this field is not filled. The other fields are all preassigned.
##

**Comment by ximex** [comment]
@Fasse found the bug.
https://github.com/Admidio/admidio/blob/v3.2/adm_program/modules/messages/messages_write.php#L458
`$preloadData` should be `$form_values['msg_to']`
Have to look in detail what is about the `$preloadData`
