### ISSUE TITLE
Do not show users from invisible roles

### ISSUE THREAD

**Issue by sistlind** [Admidio/admidio#292]
Hi,
currently at the user overview all users with active roles are shown. This should be changed to show only user, which are in visible roles. Sometimes people are no longer member of the organization, but are still for example in one of the hidden roles of "mitgliedsbeitrag".

This has led to a lot of confusion at our organization, because there were members shown, which were in no role.

Just add 'AND rol_visible = 1' three times(around line 58,80,93) to https://github.com/Admidio/admidio/blob/master/adm_program/modules/members/members.php to solve this issue.

Best regards,
Stefan

**Comment by Fasse** [comment]
Wie should add a flag in the preferences that hidden roles should not be considered in the user management. Only of You select to view all members.

**Comment by Fasse** [comment]
Since we havn't invisible roles in version 3.3 we can close this issue.
