### ISSUE TITLE
Skype icon doesn't work anymore

### ISSUE THREAD

**Issue by silverches** [Admidio/admidio#293]
https://github.com/Admidio/admidio/blob/master/adm_program/modules/profile/profile.php#L80

The mystatus.skype.com has been shutdown at and of May 2015. [source](https://support.skype.com/en/faq/FA605/how-do-i-set-up-the-skype-button-to-show-my-status-on-the-web-in-skype-for-windows-desktop)

I think its best to change it to a static image. Or you could potentially use [this.](https://www.skype.com/en/create-contactme-buttons/)

**Comment by Fasse** [comment]
Wie should set a static icon. Also For icq.

**Comment by Fasse** [comment]
ICQ also removed
