### ISSUE TITLE
Add new language norwegian

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#296]
see topic
##

**Comment by ximex** [comment]
https://www.transifex.com/admidio/admidio/language/nb/

**Comment by ximex** [comment]
or delay to v3.2?

**Comment by Fasse** [comment]
Why? Of it is ready wie integrate it in Admidio 3.1

**Comment by ximex** [comment]
I'm a fan oft semver and this is a new feature so this means to increase the minor version  ;-)

**Comment by Fasse** [comment]
Yes but new languages are only xml files. And if someone does the work to translate 1600 strings then we should add them quickly.
