### ISSUE TITLE
External icon link not possible anymore

### ISSUE THREAD

**Issue by Silicon1602** [Admidio/admidio#306]
In the past it was possible to use a link to an external icon in the profile field section (http://demo.admidio.org/adm_program/modules/preferences/fields_new.php). This isn't possible anymore because the only allowed characters are: 

> Erlaubt sind nur Buchstaben und Umlaute, Zahlen 0-9 und die Sonderzeichen $!?._+-()& .

and not /. Is this a conscious choise?

**Comment by Fasse** [comment]
This was a bug. Links to icons should still be allowed.
