### ISSUE TITLE
Bootstrap tooltip is not shown in every case within a table

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#311]
Within the user management table the tooltip is not shown at the "user" and the "gender" icons but it is shown in the same row for the "edit" and "delete" icons.

Some tests show that it's not the wrong syntax at the icons. Also if they where converted to popovers it won't work.

Same problem will be in the role assignement list. There we have the "map" icon with the address that won't work.

Maybe it's a bootstrap problem and we must search for an alternative solution.

**Comment by ximex** [comment]
Maybe same problem?
https://github.com/Admidio/admidio/issues/325

**Comment by Fasse** [comment]
This will be fixed with #362
