### ISSUE TITLE
Create Docker Image

### ISSUE THREAD

**Issue by ximex** [Admidio/admidio#323]
https://www.docker.com/
Should be a separate git repository

**Comment by ximex** [comment]
https://www.admidio.org/forum/viewtopic.php?f=4&t=7492

**Comment by Fasse** [comment]
I have created a docker organization **Admidio**

**Comment by Brawn1** [comment]
Hy,
i update / create all versions today new.

**Comment by ximex** [comment]
@Brawn1 if v3.3 docker version is released i will close this issue
