### ISSUE TITLE
Session IP Check Bug

### ISSUE THREAD

**Issue by ximex** [Admidio/admidio#327]
https://github.com/Admidio/admidio/issues/324

http://admidio.org/forum/viewtopic.php?f=3&t=6980

**Comment by Fasse** [comment]
Duplicate https://github.com/Admidio/admidio/issues/324

**Comment by Fasse** [comment]
My mistake the Problem is still there.

**Comment by Fasse** [comment]
#348

**Comment by Fasse** [comment]
With the newer version of Admidio 3.2 and 3.3 this bug doesn't came up.
