### ISSUE TITLE
Drop lib phpass

### ISSUE THREAD

**Issue by ximex** [Admidio/admidio#328]
Remove old password hashing lib.
Problem: Old passwords (hashes) won't work anymore.
Solution: For every old hash generate new password and send by mail
Bonus: Only secure hashes in the database

**Comment by Fasse** [comment]
Why do old password hashes not work anymore?

**Comment by ximex** [comment]
After this change this could be removed.
https://github.com/Admidio/admidio/blob/master/adm_program/system/classes/passwordhashing.php#L71-L79
Then we only support the hashes that are generated by bcrypt etc (from the php intern hashing functions)

**Comment by Fasse** [comment]
We should bot Remove this. We migrate passwords at login and therefore wie Need it. I'm also not a friend of new automated passwords. This will be confusing for a lot of people. The current solution works good.

**Comment by ximex** [comment]
This will only affect the user they never logged in since Admidio 3.1.
So, Admidio 4.0 is about 1 year away -> less people the get an email with a new password

**Comment by PeterTheOne** [comment]
+1

(btw. sending passwords via email is also not a good idea.)

**Comment by ximex** [comment]
@PeterTheOne they are autogenerated and should get changed.

**Comment by PeterTheOne** [comment]
@ximex http://security.stackexchange.com/a/17981/67030

**Comment by Fasse** [comment]
If a Webmaster will update to Admidio 4 and had Used Admidio 3.0 or less then ALL Users will get a new password. That will be very confusing for some end users.

**Comment by ximex** [comment]
i would only allow the update from the latest 3.x version to 4.0. So we could remove most of the legacy code.
And yes it could be that:
Current version 3.0 - wants to update to 4.0 - see he need to update to 3.x first - did the update - only his password gets rehashed - updates to 4.0 - all other users got new passwords
But between release of 3.1 and 4.0 will be more than 1,5 years.
In German: "Man kanns nicht allen recht machen."

**Comment by Fasse** [comment]
Ich sehe aber weiterhin keinen Sinn in dieser Änderung. Dadurch machen wir es nur vielen Leuten schwer. Einfach mal so alle Passwörter ändern, kann dazu führen, dass einige Nutzer dann Admidio nicht mehr nutzen können, da sie die Email mit dem neuen Passwort nicht mehr finden, sich 3 mal falsch einloggen usw.  Ich denke nur daran, wenn sowas mit einem Login meiner Eltern gemacht würde ...

Nur um eine alte Lib zu entfernen finde ich die Nachteile überwiegend. 1,5 Jahre finde ich keine lange Zeit. Wir haben jetzt noch Leute, die von Admidio-Versionen 1.x oder 2.2 updaten und da sind es schon 4 oder 5 Jahre.

**Comment by ximex** [comment]
ok dann verschieben wir das auf später. Ich wollte mit 4.0 einen harten bruch machen und alles alte ausmisten und mit einem sauberen code ohne viele "if" für diverse unterschiede weitermachen

**Comment by Fasse** [comment]
I think we can remove this for version 4.1.
Also I think we do not need to send a new password. The user can request a new password by himself through the new request process.
