### ISSUE TITLE
include plugin at extra file

### ISSUE THREAD

**Issue by sistlind** [Admidio/admidio#337]
At each update(which are quite frequent in the last months) i have to re-add my plugins.

Therefore, there should be an extra file, which contains the menu-part and this file should go to adm_my_files.

**Comment by Fasse** [comment]
The menu should be configurable.

We talked about this in the forum a few weeks ago. Now I created the issue #339 .

Does this fit your needs?

**Comment by Fasse** [comment]
We will solve this with issue #339
