### ISSUE TITLE
Absender E-Mail festlegen

### ISSUE THREAD

**Issue by rickyweb** [Admidio/admidio#344]
Wegen der DMARC Initiative (https://support.google.com/mail/answer/2451690 ) funktioniert das Mailen nicht mehr. Wenn ich bei gmail bin und ein Mitglied bei Yahoo anschreibe, sagt mir yahoo, dass ich über einen Mailserver schicke, der nicht zu Yahoo gehört.

Daher muss ich irgendwo eintragen können, dass meine Absender E-Mail Adresse _immer_ no-reply@example.com ist und meinen E-Mail Server example.com verwende. Solch ein Feld, und die entsprechende Option fehlt noch in den Einstellungen.

Dies sollte relativ rasch umgesetzt werden, da ich stark vermute, dass bei vielen Leuten E-Mail deswegen nicht mehr funktioniert.

**Comment by Fasse** [comment]
Du kannst in den Einstellungen > Nachrichten doch eine feste Absenderadresse pflegen. Muss man den Server auch noch explizit setzen. Ich dachte der würde automatisch mit übertragen.

**Comment by rickyweb** [comment]
Hallo Fasse,
Komisch, ich finde deinen Eintrag in der 3.1.0 nicht. Ich habe Einstellungen > E-Mail versand sowie Einstellungen > Systembenachrichtigungen. Beim letzteren kann ich zwar eine Absender-Adresse hinterlegen, das gilt aber nur für eben "Systembenachrichtigungen". Ich habe das Problem aber beim E-Mail Versand, von Mitgliedern an andere Mitglieder oder Rollen.

**Comment by Fasse** [comment]
Einstellungen > Module > Nachrichten

**Comment by rickyweb** [comment]
Hallo Fasse,
Danke, das hat funktioniert.
