### ISSUE TITLE
Request: new role permission to allow conversation among each other users

### ISSUE THREAD

**Issue by papierkorb27** [Admidio/admidio#355]
Regarding to the discussion about http://www.admidio.org/forum/viewtopic.php?f=7&t=7072&p=24240#p24240

It would be nice to have a new role right that allows to contact users from another role via e-mail or private message directly, without having the the right to see the profile data of them.

This feature would support the communication significant inside an organization.

**Comment by Fasse** [comment]
There is already the right **Emails zusenden** within the roles configuration. 
Why doesnot this fit your requirements?

**Comment by papierkorb27** [comment]
Hi fasse,

have you already read the answer about your question why the right **Emails zusenden** doesnt fit? Because you have to allow the right "Rollenmitgliedschaft sehen" für "Alle angemeldeten Benutzer" at the other role. Then you can see the profile data from the other user but you shoud just send a message to them...

**Comment by papierkorb27** [comment]
Addition: setting the right "Emails zusenden" without the right "Rollenmitgliedschaft sehen" just allows to send a message to the role. Maybe it would a option to allow to contact every single user of the this role if you set this right without getting access to the profiles..

**Comment by Fasse** [comment]
This feature could be realized with the existing configuration of version 4.3 . 
You can now set a preference in each role that users are not allowed to view the profile but they are allowed to view the membership. All users of roles who you are allowed to view the membership will be listet in the messages module.
