### ISSUE TITLE
Write mail to lists [$80]

### ISSUE THREAD

**Issue by papierkorb27** [Admidio/admidio#363]
Regarding to http://admidio.org/forum/viewtopic.php?f=2&t=6836

Maybe there is a possibilty to extend the existing function to write a message to a role to write a mail to a list.

Example: user 1 want to sent a message to all users which have their birthday in the next 40 days. Now he can generate an own list with a condition in the birthday field but he have to export the mail adresses from the result to an external mail client formatted as csv for example. He can not use the well working internal mail function like writing to a role.

Example 2: the user has a field "subscribe newsletter" in his profile. If the mail to list function would be exist, the management could easily generate a list with all users which subscibed and write a newsletter with the internal mail function. If you use a own role for the newsletter recipients, the user can't unsubscribe by himself from the list.
##

**Comment by Fasse** [comment]
This feature should be implemented for the configured and saved own list. The feature should not be implemented for the filtered users within a list view because this filter is not saved in database so there is no easy way to get the filtered users within the mail module.

**Comment by wilddom** [comment]
It's already possible to send one user id in a get request to the mail module, so how about just allow submitting multiple user ids? This would allow to easily prefill the users in the mail module even from dynamic lists.

**Comment by Fasse** [comment]
Wie kann hier eine mögliche Lösung aussehen?

- man würde alle Parameter der lists_show.php in die messages_write.php übernehmen um dort dann eine Liste aller Benutzer erzeugen zu können. Dies sind aber ca. 5 weitere Parameter (lst_id wegen der Bedingungen, urt_id wegen der Beziehungen ...) und machen die Logik in der messages_write.php nicht gerade einfacher.
- man erstellt einen neuen Parameter wie @wilddom vorgeschlagen hat, an den man alle user_ids hängt, was aber bei einer großen Organisation bei der Mitgliederrolle sehr viele sein könnten und so die Länge bei GET sprengen könnte.
- ???

@rmbinder würde dies gerne umsetzen, wenn wir eine gescheite Lösung finden.

**Comment by wilddom** [comment]
@Fasse Eine Alternative wäre es doch, dass die user_ids per POST übermittelt werden müssten.

**Comment by Fasse** [comment]
Ok, man könnte die Übertragung mit POST machen. Dann sollte man aber auch vorsehen, dass sowohl Rollen als auch User übertragen werden.

`$recipientsIds = 'user:1,user:45,user:43,user:78,role:2,role:5';`

um die Übergabe kürzer zu machen könnte man auch diese Syntax nutzen:
`$recipientsIds = '1,45,43,78,role:2,role:5';`

In messages_write müsste man das dann für die selectBox transformieren. Außerdem müsste man dort dann das Auswahllimit ignorieren, wenn der Parameter $recipientsIds gesetzt ist.

**Comment by rmbinder** [comment]
Warum Rollen und User übertragen?
Wenn man über Listen in der Ansicht "Übersicht der aktiven Rollen" ist, kann man über den Button "E-Mail an Mitglieder" auch nur an eine (einzige) Rolle die Mail senden. Hinzufügen von Einzelpersonen ist bei mir nicht möglich.

Wenn ich eine sehr komplexe Liste erstelle, basierend auf mehreren Rollen, mit Beziehungen und gefiltert (Zeitraum) möchte ich doch genau an die Personen des Ergebnisses meine Mail schreiben und nicht an weitere Rollen oder Einzelpersonen. Es würde somit reichen, nur die user_ids der angezeigten Liste zu übertragen.

**Comment by papierkorb27** [comment]
Ohne jetzt tief technisch in der Materie zu stecken: rmbinders Kommentar leuchtet mir ein, ich wähle ja bei der Generierung der eigenen Liste neben den Bedingungen schon eine oder mehrere Rollen aus, die User aus dem Ergebnis dieser Abfrage sollten dann ja direkt angeschrieben werden können. Es sei denn, man schreibt das Ergebnis bzw. die User nach der Abfrage in eine "temporäre Rolle" in die Datenbank und dann an diese Rolle an eine Mail? Aber ob das so Sinn macht, wisst ihr sicher besser.

**Comment by Fasse** [comment]
Ich sehe es jetzt auch so wir Rainer, ist dann auch logischer und verständlicher.
