### ISSUE TITLE
master - can't login to new installation

### ISSUE THREAD

**Issue by sirnone** [Admidio/admidio#380]
Hello,
I just updated to the new master. The Installation works without problem, but the Password of the admin ist stored without hash.
after installation, I can't login, because the PW check don't work.

**Comment by ximex** [comment]
https://github.com/Admidio/admidio/pull/378/commits/d3f925ef39e1e6f1adc4167b60df0550ad635c9d ?

**Comment by sirnone** [comment]
this will fix the problem. So i will close this bug
