### ISSUE TITLE
Wrong display of end dates within all days events 

### ISSUE THREAD

**Issue by thomas-rcv** [Admidio/admidio#394]
End dates in all day events are only shown correctly in the standard "detailled" view. In other views we have the 1 second problem again. 
Need to Change the code from the date time object to the already fixed internal solution reading the recordsets, because this causes a 1 day Offset for the end date.

**Comment by ximex** [comment]
@thomas-rcv where is the fix?

**Comment by thomas-rcv** [comment]
See it ... commit was not done. Somthing crashed on my Desktop ... Really love this ...
Will check next days ...

**Comment by thomas-rcv** [comment]
Please review to close issue

**Comment by Fasse** [comment]
@thomas you only need to fix 3.1 , master will always been merged from 3.1.

**Comment by thomas-rcv** [comment]
Ok, will take in mind in future.
Did'nt know ...
Thanks
