### ISSUE TITLE
User registration input validation issues

### ISSUE THREAD

**Issue by PeterTheOne** [Admidio/admidio#4]
Last year I had the opportunity to help about 10 people register a new user account, that's when I noticed that many of them struggled with the input validation.

Let me give you an example:
1. They fill in everything and send the form, but something like the password minimum length is not correct.
2. Then they go back and correct that but then then something else is wrong, for example they missed a field.
3. Then they go back and correct that, but they didn't notice that the password field was reset.
4. So they go back and fill in the password field, but they didn't notice that the captcha was also reset.
5. So they go back and fill in the password and captcha and everything works.

Here are 3 suggestions how to fix this:
1. Show the user a list things that are not correct, not only one thing at a time. Like this: "Field Username is empty. Password has to include at least 6 characters."
2. Trust the user after they filled in one correct captcha. You can trust them after one, you don't need to make them fill out one more. Or alternatively, show them the same captcha.
3. Validate input with javascript. This way you can show an icon next to every field that show if the input is correct and you can let them know with an alert/popup message if there is something wrong with their input before they submit. This way it is not necessary to retype the password and captcha.

I hope you consider my suggestions. :)

**Comment by PeterTheOne** [comment]
(I also posted this in the forum: http://forum.admidio.org/viewtopic.php?f=2&t=6085&sid=9ff5fed64b46b3f41c20439f666e2b30&p=20833 )

**Comment by Fasse** [comment]
In our next version 3.0 we use html 5 to check necessary fields so I hope this will help poeple to work with our formulars. In future versions I try to check and save form data with ajax. The first steps you will see in version 3.0 in the preferences. This concept should the prototype for all other forms in future versions. So if we have fully implement this then I think your issue could be closed.

**Comment by ximex** [comment]
#46 
d7169ec7eada1ef9f667ab5bc81c00f38d7af70a

**Comment by PeterTheOne** [comment]
nice

**Comment by ximex** [comment]
@PeterTheOne could you test it?
http://spielwiese.admidio.org/
so far i know it's only checked by html5.

maybe we should use jquery.validate or something similar

maybe we should change the input style with the css `:valid` selector (border in green, ...)

**Comment by ximex** [comment]
ok i see there are some more improvements possible on the other input fields

**Comment by Fasse** [comment]
We should not check password for minlength because historically there should be Users with shorter Passworts.

**Comment by ximex** [comment]
ok than we should check it only on password change or user registration

**Comment by ximex** [comment]
password minlength from login removed

**Comment by Fasse** [comment]
That Sounds good :)

**Comment by ximex** [comment]
also added minlength to password change (new password and confirm)

**Comment by ximex** [comment]
more checks will be implemented in v3.1 (maybe it is in time for v3.0)

**Comment by PeterTheOne** [comment]
http://spielwiese.admidio.org/ captcha doesn't load.

Also "Mitgliedsnummer" and Username will need a database check I guess? So if that goes wrong, you still would need to retype your password an captcha, right?

**Comment by Bullnados** [comment]
Captcha is a setting-->captcha problem with differnt(to small) font sizes. Font size should 20 subtitle font size 13.
Now u should see a captcha.
