### ISSUE TITLE
add an Add-On to show the online status of an User

### ISSUE THREAD

**Issue by sirnone** [Admidio/admidio#40]
a little Add-On to show an overview about the actual status of online Users in the Plattform.

**Comment by Fasse** [comment]
What's about this?
http://forum.admidio.org/viewtopic.php?f=9&t=474
Admidio Forum • Thema anzeigen - Sidebar Online 1.4.2
http://forum.admidio.org/viewtopic.php?f=9&t=474

**Comment by sirnone** [comment]
thank you Fasse, I was not aware of this!
