### ISSUE TITLE
Installation won't work after port enhancement

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#406]
Since the merge of the port enhancement the installation won't work. 

There are several errors.

- comparision of config data and session data won't work
- db object not created

**Comment by ximex** [comment]
do you mean this line?
https://github.com/Admidio/admidio/pull/401/commits/64f79b19b868d05ae634293073f012d071a14e85#diff-feba005541b0a4ca823d1881d6f5016fR608

**Comment by ximex** [comment]
@Fasse please confirm. A installation test works (PHP 5.6)

**Comment by Fasse** [comment]
Works for me. (PHP 5.3)
