### ISSUE TITLE
Change colors to new Homepage colors

### ISSUE THREAD

**Issue by ximex** [Admidio/admidio#413]
**Colors:**
- White: #FFFFFF
- Grey: #DFE3E3 -> change to E3E3E3?
- Green: #99CC33
- Turquoise: #349AAA
- Dark-Blue: #263340

![bildschirmfoto von 2016-10-09 18-37-25](https://cloud.githubusercontent.com/assets/1078640/19222033/79ae8758-8e4f-11e6-89b1-e5436048f6b4.png)
##

**Comment by ximex** [comment]
https://www.admidio.org/forum/viewtopic.php?f=4&t=7590
https://gist.github.com/cmellwig/403ecc040e0c981bf8020cd088ab59a6

**Comment by Fasse** [comment]
Done with the new theme.
