### ISSUE TITLE
Presentation view in photo module does not show pictures

### ISSUE THREAD

**Issue by jochen-ac** [Admidio/admidio#435]
In the presentation view of the poto module, the pictures are not shown. 

https://www.admidio.org/demo error:
Warning: Division by zero in /www/htdocs/admlogin/demo/adm_program/modules/photos/photo_show.php on line 135

My local installation error:
Fatal error: Call to undefined function imagecreatefromjpeg() in /Applications/AMPPS/www/messdiener/spielwiese/admidio/adm_program/system/classes/image.php on line 108

**Comment by Fasse** [comment]
This was a problem of the demo data because a preference was not set. But I enhanced also the code to avoid this problem if parameter not set.

**Comment by jochen-ac** [comment]
OK, my local installation had another problem. GD lib for PHP was missing.
