### ISSUE TITLE
Make templating easier

### ISSUE THREAD

**Issue by deadda7a** [Admidio/admidio#447]
Hi!
At the Moment I am trying to adapt the Admidio default theme to my needs and I found that this is rather hard to do because of the structure the themes have.
I would suggest to use something like Twig to interact with user data and don't spread everything over multiple files.
This would have the advantage that you could easily modify the structure of the page, classes set on elements and so on without modifying Admidio's core. Also I would like to have the possibility to modify the whole template, for example at the moment it is not possible to remove the default Bootstrap CSS and JavaScript files that are included in the page header. It would even be possible to remove all the icons that are used at the moment and replace them with some icon font like font awesome like suggested in issue #53  😄

Grav implements these things in a really nice way: https://learn.getgrav.org/themes/theme-tutorial#step-4-base-template

All the best 
Sebastian

**Comment by ximex** [comment]
Hi @deadda7a,
I'm looking at http://platesphp.com/
It's a templating framework without the need to compile the files like Twig. But you have not as much features and the auto escaping like in Twig. But i will look at that in v4.0 or v5.0.
With v5.0 we want to sperate the logic behind (Rest API) and the GUI.

**Comment by deadda7a** [comment]
Looks great! I will see if i can contribute something to the code.
I don't think everything available in Twig would be necessary, it would just be nice to have a way to control the whole rendered page, the classes things get, the order of elements etc.

**Comment by Fasse** [comment]
We have now integrate Smarty in the new theme of version 4.
