### ISSUE TITLE
Provide new list configuration for event participation

### ISSUE THREAD

**Issue by thomas-rcv** [Admidio/admidio#451]
When installing or updating Admidio, we also should define a list configuartion for particpients of Events and set this list as default for events in preferences

**Comment by thomas-rcv** [comment]
*Pending*

Will do this as soon as Master is raised to 3.3.
Update steps required!

**Comment by Fasse** [comment]
master is now 3.3

**Comment by thomas-rcv** [comment]
Ok great. Thanks
