### ISSUE TITLE
Delete organization

### ISSUE THREAD

**Issue by ximex** [Admidio/admidio#454]
It should be possible to delete an organization (if there are more than one)

https://www.admidio.org/forum/viewtopic.php?f=2&t=5477
https://www.admidio.org/forum/viewtopic.php?f=4&t=7168

We have to change to foreign key constraints. We restricted all deletions except this one:
```sql
alter table %PREFIX%_organizations add constraint %PREFIX%_FK_ORG_ORG_PARENT foreign key (org_org_id_parent)
      references %PREFIX%_organizations (org_id) on delete set null on update restrict;
```

**Comment by Fasse** [comment]
To delete an organization is something big. We should therefore ask for an administrator password before we delete an organization. Maybe we should only allow to delete an organization with no memberships except the administrator. Maybe we could set an organization to disabled if there are already a lot of members, events ...

**Comment by ximex** [comment]
https://www.admidio.org/forum/viewtopic.php?f=7&t=7689

**Comment by Fasse** [comment]
view #62
