### ISSUE TITLE
ADMIDIO_URL has the wrong path if main script is not within Admidio folder

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#464]
If you integrate a plugin in your homepage and into a script that is not within the default admidio folder, than the constant ADMIDIO_URL has the wrong path. It creates the path from the script where the plugin is integrated. 

It should be better if it could get the path from constant.php itself if its possible.

example:
Admidio installed in _https://www.admidio.org/intern_
Plugin sidebar announcements integrated in _https://www.admidio.org/includes/sidebar_announcements_iframe.php_

`ADMIDIO_URL = https://www.admidio.org/includes`

it should be:
`ADMIDIO_URL = https://www.admidio.org/intern`

**Comment by Fasse** [comment]
If the solution is more complicated than we should provide a function that determines the correct folder. This function could than be called by the plugins to get the right path. 

In my opinion this is a plugin problem because all other scripts are called within the admidio folder.

**Comment by ximex** [comment]
I think i could fix it for situations like:
`https://www.example.com/subfolder/admidio/...`
`https://www.example.com/weneedadmidiohere/`
but not for:
`https://www.example.com/subfolder/admidio/...`
`https://weneedadmidiohere.example.com/`

and if there are more complicated nginx/apache configs for the different folders there could be more problems.

Solution would be to get the diff of the paths.
For the example above:
`../subfolder/admidio/` and than resolve this with `realpath(...)`

**Comment by Fasse** [comment]
As a first fix a replace ADMIDIO_URL with $g_root_path so plugins could still be used in other pages.

**Comment by ximex** [comment]
https://www.admidio.org/forum/viewtopic.php?f=10&t=7351

**Comment by Fasse** [comment]
A possible solution could be that we store the ADMIDIO_URL in addition within the preference array and database table `$gPreferences['admidio_url']`. This preference could be filled with the update/installation script and should be checked at administrator login if it's still the same than the constant `ADMIDIO_URL`.

Then we can use at the special places where we now use `$g_root_path` this preference instead.

**Comment by ximex** [comment]
I did the "path diff" solution.
The problem with other subdomains shouldn't happen, because it shouldn't be possible (in my opinion) that you include a file from another origin/host.

My solution: (please test if it works not only on my server)
```php
// constants.php

// BASIC STUFF
// https://secure.php.net/manual/en/reserved.variables.server.php => $_SERVER['HTTPS']
define('SECURE_PROXY', !empty($gSecureProxy)); // true | false
define('HTTPS', SECURE_PROXY || (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off')); // true | false
define('PORT', SECURE_PROXY ? 443 : (int) $_SERVER['SERVER_PORT']); // 443 | 80

$port = ((!HTTPS && PORT === 80) || (HTTPS && PORT === 443)) ? '' : ':' . PORT; // :1234
$host = isset($_SERVER['HTTP_HOST']) ? $_SERVER['HTTP_HOST'] : $_SERVER['SERVER_NAME'] . $port; // www.example.org:1234

define('HOST', SECURE_PROXY ? $gSecureProxy : $host); // www.example.org:1234 | www.myproxy.com:1234
define('DOMAIN', strstr(HOST, ':', true)); // www.example.org | www.myproxy.com

$execFilePath = $_SERVER['SCRIPT_FILENAME'];
// 33 is string length of: '/adm_program/system/constants.php'
$admidioPath = substr(__FILE__, 0, -33); // /var/www/subfolder
$pos = strspn($execFilePath ^ $admidioPath, "\0");
$execFilePath = str_replace(DIRECTORY_SEPARATOR, '/', substr($execFilePath, $pos));

define('ADMIDIO_SUBFOLDER', substr($_SERVER['SCRIPT_NAME'], 0, strlen($execFilePath) * -1) . $admidioPath); // /subfolder
define('ADMIDIO_SUB_URL', SECURE_PROXY ? '/' . $host . ADMIDIO_SUBFOLDER : ADMIDIO_SUBFOLDER); // /subfolder | /www.example.com/subfolder

// URLS
define('SERVER_URL',  (HTTPS ? 'https://' : 'http://') . HOST); // https://www.example.org:1234 | https://www.myproxy.com:1234
define('ADMIDIO_URL', SERVER_URL . ADMIDIO_SUB_URL); // https://www.example.org:1234/subfolder | https://www.myproxy.com:1234/www.example.com/subfolder
define('FILE_URL',    ADMIDIO_URL . substr($_SERVER['SCRIPT_NAME'], strlen(ADMIDIO_SUBFOLDER))); // https://www.example.org:1234/subfolder/adm_program/index.php
define('CURRENT_URL', ADMIDIO_URL . substr($_SERVER['REQUEST_URI'], strlen(ADMIDIO_SUBFOLDER))); // https://www.example.org:1234/subfolder/adm_program/index.php?param=value

// PATHS
define('WWW_PATH',     realpath($_SERVER['DOCUMENT_ROOT'])); // /var/www    Will get "SERVER_PATH" in v4.0
define('ADMIDIO_PATH', $admidioPath); // /var/www/subfolder
define('CURRENT_PATH', realpath($_SERVER['SCRIPT_FILENAME'])); // /var/www/subfolder/adm_program/index.php
```

**Comment by ximex** [comment]
Found a little bug in my DOMAIN changes. I fixed it in my comment above

**Comment by ximex** [comment]
Soooo... Found also a working version if path root isn't url root:
```php

$maxEqualPos = strspn(CURRENT_PATH ^ ADMIDIO_PATH, "\0");
$urlPathRemove = str_replace(DIRECTORY_SEPARATOR, '/', substr(dirname(CURRENT_PATH), $maxEqualPos));
$urlPathAppend = str_replace(DIRECTORY_SEPARATOR, '/', substr(ADMIDIO_PATH, $maxEqualPos));
$urlBase = $_SERVER['SCRIPT_NAME'];
if (substr($urlBase, -4) === '.php')
{
    $urlBase = dirname($urlBase);
}
if (substr($urlBase, -1) === '/')
{
    $urlBase = substr($urlBase, 0, -1);
}
define('ADMIDIO_SUBFOLDER', (($urlPathRemove === '') ? $urlBase : substr($urlBase, 0, -strlen($urlPathRemove))) . $urlPathAppend);
```

**Comment by Fasse** [comment]
sry I dont want to assign @rmbinder

**Comment by ximex** [comment]
Because of no feedback i commit it and wait for bug reports if it doesn't work...
