### ISSUE TITLE
get language for first install page by script

### ISSUE THREAD

**Issue by sirnone** [Admidio/admidio#47]
we can try to get the language for the first page based on the browser language.

e.g.:
<script type="text/javascript">
 var userLang = navigator.language || navigator.userLanguage; 
 alert ("The language is: " + userLang);
 </script>

**Comment by Fasse** [comment]
First we should determine the browser language and try to load that language. If we do not support that language than we show the language that was set in the system preferences.

**Comment by Fasse** [comment]
What do you think should we do with our language preference. If we use the browser language for users then we only use the language preference if the user has a browser language that we do not support. In all other cases we ignore the language preference and use the browser language.

Should I implement this logic?

**Comment by ximex** [comment]
@Fasse yes

**Comment by sirnone** [comment]
I think we should always use the language from the settings and if we have no language setting (install process) we use the browser language.
in the other way you can get a problem when you are in a hotel and the setting of the browser is not your language.

**Comment by Fasse** [comment]
I implement the logic only for install process.
