### ISSUE TITLE
Lock events for participation at a defined date

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#476]
When You are the event-owner, You possibly have a deadline for booking seats or other things.
This deadline is some days before the event(s) will take place.
On that day, You have to know the exact number of participants. From ( after ) this day it should not be possible to participate or cancel. The event should be locked.
If someone will not participate the event, then he has to contact the admin and tell him of his problem - or find another participant - or pay for the participation he had done and not canceled in time. If he had the possibility to cancel after the deadline, then the admin/event-owner does not know who to bill for some tickets that was not used.

**Comment by Fasse** [comment]
https://www.admidio.org/forum/viewtopic.php?f=20&t=7312

**Comment by thomas-rcv** [comment]
#211

**Comment by thomas-rcv** [comment]
Leave a comment
