### ISSUE TITLE
Password strength indicators: zxcvbn & zxcvbn-php calc different strength

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#487]
Password strength is set to 1. Now enter new passwort **meinTest** .

Indicator shows **orange** and should be ok. But then the following error occurs: 

> Das Passwort ist nicht sicher genug.

View also forum https://www.admidio.org/forum/viewtopic.php?f=3&t=7298#p25451

**Comment by ximex** [comment]
Will drop the javascript lib and add a REST API to check the password strength with ajax

**Comment by Fasse** [comment]
We should do this "big" change in next major version.

**Comment by ximex** [comment]
Update zxcvbn-php to v1.0.0 should fix this problem. But this version only supports PHP 7.1+ (So we need https://github.com/Admidio/admidio/issues/844)
https://github.com/bjeavons/zxcvbn-php/releases/tag/1.0.0

**Comment by Fasse** [comment]
zxcvbn-php version 1.2 is now integrated.
