### ISSUE TITLE
Error in creating random int for session id

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#493]
view forum https://www.admidio.org/forum/viewtopic.php?f=3&p=25474#p25463

**Comment by ximex** [comment]
now we have a security issue in v3.2.3. We need infos why this happen.

**Comment by Fasse** [comment]
In version 3.1 and before we don't have created secure random int. With version 3.2 there are problems at some installations, so in a quit fix we have a fallback, so everyone who uses 3.1 can use 3.2. Now there is time to search for a better fix.

Security is important, but security should not lead to a unusable script.

**Comment by ximex** [comment]
I need input of the users that have problems with this. I don't want to leave this security leak open forever

**Comment by ximex** [comment]
@Fasse i want to revert this changes if the users couldn't give an answer they have problems with that... Looks only one user had this problems.
It's irresponsible to let this as it is

**Comment by Fasse** [comment]
If we dont use a PHP Standard than we Need a Fallback!

**Comment by PeterTheOne** [comment]
`random_int` is new in PHP7 http://php.net/manual/en/function.random-int.php

**Comment by ximex** [comment]
and we use a polyfill for PHP 5.x support. So it should work. And if a user couldn't help to find out where the problem is, i couldn't understand why we should open an security hole...
This is like: a person often lose his car keys. Ok lets build cars without door locks so this person could drive with our cars. This makes no sense

**Comment by Fasse** [comment]
@Petertheone I know, but Our minimum PHP Version is Not PHP 7, so if People have Problems we Need a fallback and Not an error.

**Comment by ximex** [comment]
I will add a big warning message in the admin settings if it isn't possible to generate secure random numbers. With the addition that we won't support this insecure fallback in Admidio 4.0

**Comment by Fasse** [comment]
@ximex didn't we say that you only implement a warning in 3.2 and not set the exception!?!

**Comment by ximex** [comment]
@Fasse the Exception gets only thrown if you set the new parameter to true. So the default is no Exception. There is no other good possibility to check if prng is secure or not

**Comment by Fasse** [comment]
Ah sorry, I didn't notice that you call the randomInt within preferences with true. I thought it was while login.
