### ISSUE TITLE
Password complexity

### ISSUE THREAD

**Issue by ximex** [Admidio/admidio#50]
http://www.admidio.org/forum/viewtopic.php?f=2&t=6196

I think every password today should have a min of 8 characters (today minlength is 6)
there should be now password maxlength

there are 4 types of characters:
- digits (0-9)
- lower-case letters (a-z)
- upper-case latters (A-Z)
- special chars (-#,.+*=()§$...)

i think every password should contains at least digits and lower or/and upper-case letters

possible solutions:
- option for each category to make it required or not
- change to minlength (but at least 8 chars)
- ~3 different password complexity levels
  - low: 8 chars and contains digits and lower or uppercase letters
  - middle: 10 chars and contains digit and lower and uppercase letters
  - high: 12 chars and contains all 4 types

**Comment by Bullnados** [comment]
I prefer option for each category but
* min 8 chars
+
* min 1 digit or special char.
I nice feature would be a password generator btw.

**Comment by ximex** [comment]
Maybe we could use this lib:
https://github.com/hackzilla/password-generator

but i think we need a javascript based lib but i didn't found a nice one...

**Comment by ximex** [comment]
https://www.404it.no/en/blog/javascript_random_password_generator

**Comment by ximex** [comment]
Found two possible libs. I think we only have to modify them a little bit:
- https://github.com/brendanashworth/generate-password
- https://github.com/bermi/password-generator

**Comment by ximex** [comment]
now it's possible to choose chars for password generation: https://github.com/Admidio/admidio/issues/321

**Comment by PeterTheOne** [comment]
Why not use a password strength indicator like https://github.com/dropbox/zxcvbn ?
