### ISSUE TITLE
Use uft8mb4

### ISSUE THREAD

**Issue by ximex** [Admidio/admidio#501]
https://dev.mysql.com/doc/refman/5.5/en/charset-unicode-utf8mb4.html

Needs MySQL 5.5+

**Comment by Fasse** [comment]
What's the advantage for Admidio and the User if we use this?

**Comment by ximex** [comment]
Security and the possibility to use more special characters

**Comment by Fasse** [comment]
We should discuss this. In my opinion there is no real benefit to explain a higher version requirement.

**Comment by ximex** [comment]
https://mathiasbynens.be/notes/mysql-utf8mb4

**Comment by Fasse** [comment]
I don't want to discard this issue. It's a good issue and we should implement this. But not in milestone 4.0.

**Comment by ximex** [comment]
in times of thousands of emojis we should implement this feature sooner rather than later
