### ISSUE TITLE
Save status if user cancel an event participation

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#502]
If a user cancel the event participation we should also save this status in `mem_approved` . So if you create a participation list you will also view the canceled users (like in Outlook). Because of this we must rewrite the counter for participations because there we must ignore this users. If a user has canceled the participation the particiaption button should also show this status.

Maybe this could be an optional feature because some people won't view canceled users in their lists.

**Comment by Fasse** [comment]
Folgendes Vorgehen könnte ich mir vorstellen:
Moduleinstellung (Checkbox):
- Nur Zusagen oder Zusagen unter Vorbehalt in der Teilnehmerliste hinterlegen
Das wäre dann das bisherige Verhalten. Bei Installation würde ich das auf `false` setzen, beim Update auf `true`.

Ist die Checkbox nicht gesetzt, dann sollte bei einem neuen Termin alle Mitglieder der zugeordneten Rollen zu dem Termin eingetragen werden mit `mem_approved` = **Keine Rückmeldung**.

Bei einer Absage dann den Status **Nein** 

So hat man dann eine Liste ähnlich Outlook, bei der man dann sehen kann, wie der Status der einzelnen Mitglieder ist. Vor allem sind dann auch Absagen sichtbar, was ich eigentlich bei einem Termin sehr wichtig finde, kann aber verstehen, wenn man das auch nicht haben will, deshalb die Option.

**Comment by thomas-rcv** [comment]
Habe jetzt mal die Moduleinstellung dargestellt. Habe den Kommentar gerade erst gelesen. Im Endeffekt kommt es funktionell aufs Gleiche raus. Schau dir mal die text strings an. Da können wir uns sicherlich abstimmen.
