### ISSUE TITLE
Change rights management for uploading files and adding subfolder

### ISSUE THREAD

**Issue by papierkorb27** [Admidio/admidio#509]
Regarding to https://www.admidio.org/forum/viewtopic.php?f=7&t=7331

1. To be up for discussion: it is my great wish that you could add to a role upload rights to a subfolder without giving rights to add files and subfolders inside the whole root directory.

2. It would be a nice feature that if you add a role to the line "Dateien hochladen" that this role will be automatically added to the line "Sichtbar für" inside this folder.

**Comment by Fasse** [comment]
I saw your Post in the Forum and have the Same Problem within my usecase of Admidio.

I think we should show the right "Dateien hochladen" all roles that are able to view this Folder.
So if You Want to add a new role You Must First add a new role that have the right to view the folder.
Then there should be an Option to give the right For uploads recursive. (Default recursive)
The right For viewing will still be recursive.

**Comment by papierkorb27** [comment]
Hi fasse,
sounds good, this changes would be appreciated :-)

**Comment by Fasse** [comment]
I implement it the way you suggest.

- show the right "Dateien hochladen" all roles that are able to view this Folder
- if you add a role to "Dateien hochladen" this role will automatically add to the "Visible for" right

If this is merged you can have a look at our playground.
