### ISSUE TITLE
Support profile field type telephone 

### ISSUE THREAD

**Issue by ximex** [Admidio/admidio#51]
Support input `type="tel"`

improves #4

**Comment by ximex** [comment]
is there a special reason why the `COUNTRY` is type `TEXT` and not `DROPDOWN`?

**Comment by Fasse** [comment]
The field `country`is special because it get's the values from a xml file. This is an internal reason why it is text.

**Comment by ximex** [comment]
i know this special thing with the xml file. but i don't get i why we need it as TEXT and not dropdown.
in the end it gets rendered as dropdown and not text...

**Comment by Fasse** [comment]
We should add a new field type "Phone" to our Profile Field configuration and then Link These Input with `Type="tel"` and a href with `tel:`
