### ISSUE TITLE
Add new right to edit profiles of users in your relationships

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#521]
We could assign relations between users. It would be a great feature if we allow people to edit user profiles of users who are in their relationships.

Therefore we should add a new roles right **edit users of relations**. If a user has that right he could also edit all users to which he has a relationship.

This is very useful if you work with family relations. So if you have several members of a family within your organization then 1 person of the family should be able to update all profiles of the family.

**Comment by ximex** [comment]
maybe we should set the right not in the roles. instead set it in the relation. So e.g only parents could edit childrens

**Comment by Fasse** [comment]
Thats a good idea!

In addition only users who have the right to edit their own profile should be able to edit profiles of their relations.

**Comment by Fasse** [comment]
If we implement this in combination with the relationship type than we must also add a new preference who is able to add relationships to profiles.

Now everyone who can edit a profile could add relations. But if you are able to edit profiles of relations than you could add every person as a relation and edit his profile.

Therefore the existing preference to enable edit of relations should be enhanced:

Name: **Edit relationships**

Values: 
- Disabled
- Every user with the role right Edit all users
- Every user who can edit the profile

Description: There should be a warning for the 3. value that it could be possible in combination with the edit right of relations to edit every user.
