### ISSUE TITLE
Icon url check in profile fields wont work on icons from theme folder without path

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#526]
view forum https://www.admidio.org/forum/viewtopic.php?f=3&t=7355

**Comment by ximex** [comment]
Do we want to change this?

**Comment by Fasse** [comment]
We don't want to support relative path.

**Comment by Fasse** [comment]
I run into the problem that you could not update our default fields like _Facebook_ because there we use only the icon name.

The behavior should be the following. You must enter a full url (thats now possible) or you can add an icon from the theme folder. But it should not be possible to add a relative path.
