### ISSUE TITLE
Change icons to font-images library FontAwesome

### ISSUE THREAD

**Issue by ximex** [Admidio/admidio#53]
if i load the website there are MANY icon they got requested.
many requests -> bad loading performance. normally a webserver only makes 8 requests at the same time.

to improve this there are following possible solutions:
- image sprites (https://en.wikipedia.org/wiki/Sprite_%28computer_graphics%29)
- take "font-images"
  - http://fontawesome.io/
  - http://ionicons.com/
  - http://glyphicons.com/

i prefer the "font-images":
- no complex css rules
- no complex update process for new icons
- font -> vector -> scaleable

bootstrap uses `glyphicons`

**Comment by ximex** [comment]
i have now minimized the size of the images in ebf3435adb8f7c591f1ea4d1d96eeb11bcb3b355 for the first step.  (loseless compression) -> saved about 25kB

**Comment by ximex** [comment]
by the way: where did we use `adm_themes/modern/font.ttf`? I think we could remove this font.

**Comment by ximex** [comment]
i will try some tests with font-awesome
it would be nice if we make a list which icon would be mapped to which font-awesome iconclass like:

Icon-Image | Font-Awesome
---------------|--------------------
add.png | 
aim.png | 
announcements_big.png | 
announcements.png | 
application_double.png | 
application_form_edit.png | 
application_view_list.png | 
application_view_tile.png | 
arrow_down.png | 
arrow_in.png | 
arrow_out.png | 
arrow_turn_left.png | 
arrow_turn_right.png | 
arrow_up.png | 
asterisk_gray.png | 
asterisk_yellow.png | 
back.png | 
backup_big.png | 
backup.png | 
blank.gif | 
bullet_red.png | 
calendar.png | 
calendar_time.png | 
captcha.png | 
chart_organisation.png | 
chat_big.png | 
chat.png | 
checkbox_checked.gif | 
checkbox.gif | 
clock.png | 
close.png | 
comment_new.png | 
comment.png | 
database_in.png | 
database_out.png | 
database_save.png | 
dates_big.png | 
dates.png | 
delete.png | 
disk_copy.png | 
disk.png | 
door_in.png | 
download_big.png | 
download.png | 
dummy.png | 
ecard.png | 
edit.png | 
email_answer.png | 
email_big.png | 
email_key.png | 
email.png | 
email_role.png | 
error_big.png | 
error.png | 
eye_gray.png | 
eye.png | 
facebook.png | 
favicon.png | 
female.png | 
folder_create.png | 
forward.png | 
gender.png | 
google_plus.png | 
group.png | 
guestbook_big.png | 
guestbook.png | 
help.png | 
help_violett.png | 
home_big.png | home
home.png | home
icq.png | 
info.png | 
information_big.png | 
inventory.png | 
key.png | 
light_off.png | 
light_on.png | 
list_global.png | 
list_key.png | 
list.png | 
list-point.png | 
list_role.png | 
lists_big.png | 
lists.png | 
loader.gif | 
loader_inline.gif | 
lock.png | 
male.png | 
map.png | 
messages_big.png | 
messages.png | 
mylist.png | 
new_registrations_big.png | 
new_registrations.png | 
no.png | 
no_profile.png | 
ok.png | 
options_big.png | 
options.png | 
page_white_acrobat.png | 
page_white_camera.png | 
page_white_compressed.png | 
page_white_excel.png | 
page_white_film.png | 
page_white_flash.png | 
page_white_music.png | 
page_white_openoffice.png | 
page_white_powerpoint.png | 
page_white_question.png | 
page_white_text.png | 
page_white_upload.png | 
page_white_word.png | 
photo_big.png | 
photo.png | 
photo_upload.png | 
print.png | 
profile_big.png | 
profile_edit.png | 
profile.png | 
roles_big.png | 
roles_gray.png | 
roles.png | 
skype.png | 
star.png | 
system_mail.png | 
system_notification.png | 
textfield_key.png | 
textfield.png | 
triangle_close.gif | 
triangle_open.gif | 
twitter.png | 
update_link.png | 
user_administration_big.png | 
user_administration.png | 
user_key.png | 
vcard.png | 
warning.png | 
webclipicon.png | 
weblinks_big.png | 
weblinks.png | 
windows_live.png | 
world.png | 
xing.png | 
yahoo.png |

**Comment by Fasse** [comment]
The question is, which Font Library should we use. As mentioned before bootstrap use and has already integrated glyphicons. Maybe this is easier and Beter for use and already loaded.

**Comment by ximex** [comment]
we could do it with glyphicons too, but font-awesome has more icons and it's easy to let them spin or stack them together.
http://fontawesome.io/examples/#animated
http://fontawesome.io/examples/#stacked

**Comment by ximex** [comment]
ich hab jetzt mal bissl geschaut was es so an icons gibt. also bei den glyphicons (die bootstrap zur verfügung stellt) gibts nicht gerade viel auswahl. also glyphicons selbst hat schon viele icons aber bootstrap bietet nur einen teil davon an. problem ist hier aber: gratis sind hier nur die png versionen und nicht die font version.
ich werds jetzt also mit font-awesome umsetzen

**Comment by ximex** [comment]
So sieht es jetzt mal aus. Zurzeit nur die menüs auf der rechten seite (module/admin) und die module/admin übersicht in der index.php bearbeitet. weitere icons werden folgen.

https://github.com/ximex/admidio/tree/font-awesome

![admidio](https://cloud.githubusercontent.com/assets/1078640/8010469/b32a54c6-0bb0-11e5-8323-86e2053777ad.png)

**Comment by Fasse** [comment]
Das sieht gut aus. Mir gefällt auch die Wahl der Icons für die Module.

Was spricht für/gegen Glyphicons. Wie werden diese Icons geladen? Ist das eine Font Datei?

Die font.ttf wird glaube ich beim Captcha genutzt. Sobald wir das ersetzt haben, kann auch diese Datei weg.

**Comment by Bullnados** [comment]
Ja schaut sehr gut aus. Ist es möglich die Icons auch mehrfarbig zu gestallten? z.B Nachrichten eine blaue und eine orange Sprechblase?
Konnte dazu leider nix finden bei fontawesome.io/

**Comment by Fasse** [comment]
ja, das könnte man. Einfarbig kann man sie färben. Ich würde sie aber nicht unterschiedliche färben. Man könnte überlegen, ob man generell eine Farbe (blau oder so) wählt.

**Comment by sirnone** [comment]
färbig wäre eventuell für spezielle stati nicht schlecht... z.B.: Ungelesene Nachrichten bei PM's?
dann würde das noch etwas besser ersichtlich werden.

**Comment by ximex** [comment]
Zum thema glyphicons hab ich hier schon geschrieben: https://github.com/Admidio/admidio/issues/53#issuecomment-109029438
@Fasse Jetzt mit font-awesome sind die icons schriftzeichen in einer font datei die mit css an klassen zugeordnet werden.

@Bullnados mehrfarbig geht nicht direkt. nur wenn man mehrere icons übereinander lagert. siehe hier: http://fontawesome.io/examples/#stacked

@Fasse @sirnone Einfärbig färben ist überhaupt kein problem. Einfach mit `style="color: #f00;"` etc eine andere farben zuordnen

**Comment by ximex** [comment]
https://rfmtc.no-ip.org/sonstiges/admidio/adm_program/index.php
works now.
3154dcd320e62983aaa9c97844d1c0a9cb6f8db9 fixed it

**Comment by ximex** [comment]
Gefällt euch jetzt der neue Style mit den Font Icons? Dann werd ich das fortfahren und so viel wie möglich an icons ersetzen.

**Comment by Fasse** [comment]
Also mein OK hast du und die Reaktionen aus deiner Rundmail waren auch alle positiv. Ich schreibs aber noch mal an alle. Wir sollten auch schauen ob man ggf. Icons an unterschiedlichen Stellen vereinheitlichen kann z.B. das Upload-Icon bei den Downlaods und bei den Fotos. Hier wäre 1 einheitliches Upload-Icon besser, auch um den Wiedererkennungswert zu steigern.

Aber bitte, wie immer ;), erst mal nur alles in dem Branch, dann kann man dort noch mal drüber schauen.

**Comment by ximex** [comment]
Langsam wirds. Für einige Icons finde ich keine wirklich passenden font-awesome icons =(
https://rfmtc.no-ip.org/sonstiges/admidio/adm_program/index.php (self-signed certificat)

wie es aussieht muss ich da wohl auch ein paar klassen erweitern um font-awesome und normale icons zu unterstützen. zurzeit ist der code so geändert dass nur font-awesome icons unterstützt werden

**Comment by ximex** [comment]
Hier kann man sich aus verschiedenen Font Image Libs eine eigene zusammenbauen: https://icomoon.io/

**Comment by Fasse** [comment]
We should not add this to 3.1 maybe 3.2

**Comment by Fasse** [comment]
I would like to help implement this in version 4.0

**Comment by Fasse** [comment]
@ximex Is it ok for you if I will implement this in v4 and start new with the implementation?

**Comment by ximex** [comment]
yes. i had the same opinion
