### ISSUE TITLE
Expect MB in preferences where now kB is required

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#55]
We should change all preferences to MB where we now require kB. Therefore we need to check all places where we use these preferences and calculate kB if required.

**Comment by ximex** [comment]
:+1:

**Comment by ximex** [comment]
i used `KiB`, `MiB`, `GiB`, `TiB` as unit.
look here why i did this:
https://de.wikipedia.org/wiki/Bin%C3%A4rpr%C3%A4fix
