### ISSUE TITLE
Show registration time in participants list for events

### ISSUE THREAD

**Issue by martinbrylski** [Admidio/admidio#556]
Is it possible to show the registration time of participants for a given event in the participants list? I also would prefer to have the events name heading instead of "Termin 2017-05-09 18:00 …".

Actually I would want to have something like a waiting list.

Thanks

**Comment by thomas-rcv** [comment]
This is already done for the next version. It will be possible to configure the participant list and show the timestamp of user status change.

For the waiting list we also have an open issue. This Feature definitly makes sense as well.  We will see how we can proceed and it might also come with the Version 3.3
