### ISSUE TITLE
Link to edit role assignment is shown for every user within own profile

### ISSUE THREAD

**Issue by thomas-rcv** [Admidio/admidio#563]
Every user can edit and manipulate his own  role assignment within his own profile.
It is also possible to set themselves to leader of according roles

**Comment by Fasse** [comment]
I could not reproduce this. Can you describe the steps that are necessary with our demo data.

Do you have consider the leader rights?

**Comment by thomas-rcv** [comment]
Seems to be solved. I also can´t reproduce anymore. Will set as invalid then ...
Current Master Brnach is working porperly.

**Comment by thomas-rcv** [comment]
Leave a comment
