### ISSUE TITLE
Automatic allow a number of guests after a specified date

### ISSUE THREAD

**Issue by JMS-S** [Admidio/admidio#571]
Suggestion :  Instead of a checkbox for allowing guests, then it was a numeric field that could hold a value ( default should be 0 ) ?
Then when the field is 0, and a user participates and sees the popup ( if comment is allowed ), then no field for guests are shown. If the allowed number is 2, then the field is shown and values between 0 and 2 ( inclusive ) is allowed as input.

AND  in connection with a numeric field for number of guests, that You also had a field date/time ?

This field should have the actual date/time ( for the eventcreation ) if not specified.
You can pick a datetime ( like the datetime for eventstart/end) and then the number of guests is allowed from this time ?

When You put in a number of guests, then the value is checked with the number that is set as allowed AND it is checked with the datetime specified on the event. If actual ( time for trying to participate ) datetime is before the specified datetime OR the number is higher as the specified allowed guests, then the input is not accepted.

Then the eventowner could specify a number of guests allowed after a period. When there is seats awailable 10 days after the event is published, then from that day it is allowed members to bring x guests.

**Comment by thomas-rcv** [comment]
Have a look at Issue #211.
Is this the stuff you need?
This will also come with the 3.3. You will have an datefield with the deadline for participation as option.
As Default the starttime of the Event will be set, to avoid members have the Chance to manipulate the participation in the past. Leaders and Admins of course will be able to do that anyway.

**Comment by JMS-S** [comment]
Hello Thomas. No - it is not quite the same. The deadline, I myself suggested some time ago. I thought it was a new idea, but found out You had the same idea over a Year ago.
This NEW idea is something that should be used between ( or from )  he event-creation and the deadline. Example :
You create an event ( 01.06.2017 )  and to the event You write 
- **We have 30 seats for a concert on the 15.07.2017. First to participate will get the seats. If there are still free seats after the 20.06.2017 at 12:00 o'clock  it is allowed to bring one guest. You can from then edit Your participation and add one guest ( until the max of 30 is reached ).  After the 01.07.2017 We will close the event for further participations and guests.**

You should then, when You create the event set a date for guests to 20.06.2017 12:00 and in the field number of guests You should set 1.
The locked date ( 211 ) is set to 02.07.2017 ( or should it be 01.07.2017 ? )
The only thing these new fields are used for, is when someone participates, or edit his participation, then when Allow guests is checked then when the user input a value in the field in the popup, then the value for guests is checked - is it less or equal to the allowed number of guests for the event, and is the date+time for allowed guests reached. ( the actual date+time is checked against the value specified on the event )
There is in fact no automatic in the fields - they are just values that should be checked, but the effect of the fields is as if it is automatic.

The settings on the event means that before 20.06.2017 12:00 no guests are allowed and after 20.06.2017 12:00 it is allowed to bring one guest. This is just a question of checking when the user has the pop-up with the comment and guests fields.

Today ( or from 3.3 ) You have a checkbox if guests are allowed. You could decide to keep that or You could see a number of guests = 0 as not allowed/unchecked and a number greater than 0 as alowed/checked. And it should be in connection with the date+time field.

If the date+time field is not set by the user it is defaulted to the eventcreation date+time,, and in this case the field will have no extra effect. The number of guests allowed will be allowed immediately then.
About the number of guests - I think it will be a good idea that the event-creator are able to set a max for that

So : It is two new fields date + time and number of guests and these fields is only used as fields to check an input.

It is just for future use. I don't have an actual need - I only think it could be a good feature for the system

**Comment by thomas-rcv** [comment]
Ok understood. his is an own issue to have guests options for control.

**Comment by Fasse** [comment]
I think this is a VERY specific usecase and I don't know if it's useful for Admidio because it could also confuse some people creating an event. 

If this will be added than it should be protected by a system preference.

**Comment by Fasse** [comment]
I will discard this issue because it's to specific in my opinion for our program. There are a lot of other improvements to be done.
