### ISSUE TITLE
Copying events

### ISSUE THREAD

**Issue by JMS-S** [Admidio/admidio#578]
It would be nice, if You could copy an event.
Especially until there eventually will be a possibility to create recurring events.
![udklip15](https://cloud.githubusercontent.com/assets/26816904/24702073/7b375ae8-19fd-11e7-957d-85562f357d37.JPG)

I would suggest that You could have an extra button when editing an event. This button should have the texts something like this "Save as new event" ( Speichern als neu )
This way You could edit an existing event - change the dates -and then click "save as new event"
This should create a new event (copy)  with the new information.
This will be an easy way to create events that are much the same, only with different dates.

**Comment by thomas-rcv** [comment]
???

We already have the copy Icon in the dates overview for each event  for members having the right to edit dates.

**Comment by JMS-S** [comment]
Yes - I did not notice that. It was this I meant.
I think I could not see the wood because of all the trees.
If I can find out, I will now close this.
