### ISSUE TITLE
Dynamic count of translation params

### ISSUE THREAD

**Issue by ximex** [Admidio/admidio#583]
Now it is fixed to a max of 4 params.

**Comment by Fasse** [comment]
Why do you don't create a pull request?

**Comment by ximex** [comment]
My fault. Thought that this changes are small enouth that no PR is required

**Comment by ximex** [comment]
Do we want to allow if you have only one additional translation param that you could add it as string?
Examples:
```php
$gL10n->get('XXX_XXX_XXX', array('param1')); // already possible
$gL10n->get('XXX_XXX_XXX', array('param1', 'param2')); // already possible
$gL10n->get('XXX_XXX_XXX', 'param1', 'param2'); // already deprecated
$gL10n->get('XXX_XXX_XXX', 'param1'); // allow again <<<------
```
