### ISSUE TITLE
Send email with activation link

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#585]
We should add the possibility that a user can accept the registration by himself. Therefore he should get an email to the email that was entered during registration and if he click on the link than his registration will be accepted.

Therefore we should use the column usr_activation_code (maybe with more chars) and safe the activation code there.

We should also two new preferences to the tab **registration**.
- **Send email with activation code** (default set for new installation, default not set for update) If this preference is set than an email will be send to user and after the user clock this link than depending on preference two the user will be activated or the user will be visible within registration module.
- **Registrations must be manually accepted** (default set) If this is set than it's the behavior now. If it's not set than **Send email with activation code** must be set and the user will be automatically accepted after he click the email link.

**Comment by ximex** [comment]
https://www.admidio.org/forum/viewtopic.php?f=4&t=7100
https://www.admidio.org/forum/viewtopic.php?f=2&t=7635
