### ISSUE TITLE
E-mail to list not working

### ISSUE THREAD

**Issue by papierkorb27** [Admidio/admidio#599]
Regarding to https://www.admidio.org/forum/viewtopic.php?f=11&t=7446

Trying to send a mail to a list with the v3.3 (playground) leads to:

> S Q L - E R R O R
> 
> CODE: 00000
> B A C K T R A C E
> 
> FILE: adm_program/system/classes/database.php
> LINE: 581
> CALL: Database->showError()
> 
> FILE: adm_program/modules/messages/messages_write.php
> LINE: 418
> CALL: Database->queryPrepared()
>

**Comment by Fasse** [comment]
This is a problem because of the change to prepared statements.

**Comment by ximex** [comment]
I also deployed this fix on the playground

**Comment by Fasse** [comment]
There is also an SQL-Error if you click on the email address within a profile.

> S Q L - E R R O R
> 
> CODE: 00000
> 
> 
> 
> 
> B A C K T R A C E
> 
> FILE: adm_program/system/classes/database.php
> LINE: 581
> CALL: Database->showError()
> 
> FILE: adm_program/modules/messages/messages_write.php
> LINE: 418
> CALL: Database->queryPrepared()
