### ISSUE TITLE
Many different CSS Colors

### ISSUE THREAD

**Issue by ximex** [Admidio/admidio#60]
I go through the modern css colors and i found MANY different colors. I think we could shrink them to about the half.

i try porting the css to less (see #49 ) and want to use the color functions the create some brighter or darker colors from about 3-4 main colors.
http://lesscss.org/functions/#color-definition

``` less
// less code
// colors found in 'adm_themes/modern/css/admidio.css'
@color-a: #222222;
@color-b: #333333;
@color-c: #aaaaaa;
@color-d: #bbbbbb;
@color-e: #ffffff;
@color-f: #474b4c;
@color-g: #515556;
@color-h: #7d7d7d;
@color-i: #dbebee;
@color-j: #ddeff2;
@color-k: #347078;
@color-l: #387f87;
@color-m: #409099;
@color-n: #44939f;
@color-o: #449ba6;
@color-p: #55b6c5;
@color-q: #7dbec8;
@color-r: #96c4cb;
@color-s: #a0cbd9;
@color-t: #a8d9df;
@color-u: #bad8e2;
@color-v: #c1dce6;
@color-w: #ff9c00;
@color-x: #fff8a0;
```
##

**Comment by Fasse** [comment]
This should be resolved if we integrate a new theme.

**Comment by ximex** [comment]
related to #413

**Comment by Fasse** [comment]
The new theme has less colors except the special colors for icons that could now be used with Font Awesome.
