### ISSUE TITLE
Photos - link a photo to a download-entry.

### ISSUE THREAD

**Issue by JMS-S** [Admidio/admidio#601]
It would be good, if You could have a link on the photo.
This link should be to an entry in the download. Some explanation : You have a photo gallery where You want to show all Your videos or all Your 3d-creations or all Your images. You want also these 640x480 images to be available to not logged in users, so You can present all Your good creations. But You want not all to download the original material, and maybe some 3d-creations that is "behind" an image is a zip file that consists of the files needed for the shown image. You control the acces to the original material by setting the right permissions to the download-folder.
This way You can present searchable images for the whole world, but only members can download. You can also have free meterial that ALL are allowed to download.

This is just an idea. You can build Your own system to do all this, but why not use the photo-module and the download-module together - via the link.

You could also do it the other way round ( #602 )

**Comment by Fasse** [comment]
Issue is not possible because to do not save the images in database, so we could not save additional informations to a photo.
Therefore the current concept of the module must be rewritten.
