### ISSUE TITLE
Downloads - link a download entry to a Photo entry

### ISSUE THREAD

**Issue by JMS-S** [Admidio/admidio#602]
It could be a good thing if You on a download entry could link to a Photo-entry.
Then You on the line with the download entry, had a thumbnail ( You should for a download directory be able to set a max height for the thumbnails example 40 px ).
When clicking this thumbnail You should see the pop-up You see as if You had clicked the photo in the photo-module.
This way to do the linking is not as good as if it is other way round, as the entries will only be awailable if You have the rights to download.
The other way round ( see #601 ) it will be possible to show to all and only let members or those are set up for it, download.

**Comment by Fasse** [comment]
Issue is not possible because to do not save the images in database, so we could not save additional informations to a photo.
Therefore the current concept of the module must be rewritten.
