### ISSUE TITLE
Enhanced rights management for event module

### ISSUE THREAD

**Issue by papierkorb27** [Admidio/admidio#613]
Similiar to the new right management for downloads it would be very useful if you could proper define which role can set events only visible for just one specific role.

At this moment you can only set that a role can release events and if its visible for all or just some roles. We have a lot of roles with their own tasks and it would be cool if they could only use the event module for their own activities without access to the whole event management.

**Comment by thomas-rcv** [comment]
With upcoming Admidio Version 3.3 we will have a category sytem for the calendars that will manage the role view rights. Furthermore the particpation for events will be managed by configured roles allowed to assign to the event.
So, I think this issue is already implemented in 3.3
