### ISSUE TITLE
New option to delete an organization

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#62]
We should add an option in the preferences to delete the current organization. This should only available if there is more than 1 organization in the database. There must also be a separate call for username and password of a webmaster. 
If this is passed than all data of the organization should be deleted. 
Data to delete:
announcements
events
downloads
fotos
guestbook
lists
weblinks
roles
memberships
registrations
preferences

Data not delete:
users
##

**Comment by Bullnados** [comment]
I would say its just available after a Backup, preventifely

**Comment by Fasse** [comment]
#1698
