### ISSUE TITLE
Fix and improve browser accepted language detection

### ISSUE THREAD

**Issue by ximex** [Admidio/admidio#622]
Later we should use a lib like this: https://github.com/sinergi/php-browser-detector#language-detection

**Comment by Fasse** [comment]
What was the bug in the previous implementation?

**Comment by ximex** [comment]
The regex didn't support the `*;p=0.5` etc.
The other changes are only a much better implementation

**Comment by Fasse** [comment]
Can you explain it a Little Bit more. What was the bug?

**Comment by ximex** [comment]
if there is a `*` char (matches all other languages) the detection didn't work.
