### ISSUE TITLE
Check for compatibility with PHP 7.2

### ISSUE THREAD

**Issue by ximex** [Admidio/admidio#625]
https://secure.php.net/archive/2017.php#id2017-08-31-1
https://github.com/php/php-src/blob/PHP-7.2/UPGRADING

Planed release: 30.11.2017 (https://wiki.php.net/todo/php72)

**Comment by ximex** [comment]
A fast look through the changes i couldn't find anything that should make problems. Maybe we wait until there is a tool to check the code

**Comment by ximex** [comment]
@Fasse could you look at this? Couldn't find any problem. If you also couldn't find anything you can close this issue

**Comment by Fasse** [comment]
I also couldn't find anything. So closed.
