### ISSUE TITLE
Error while creating event with missing field and using back-button

### ISSUE THREAD

**Issue by papierkorb27** [Admidio/admidio#628]
Creating an event with the field "Kalender" or "Title" empty leads to the message "Das Feld Kalender/Titel ist nicht gefüllt.". Using the button "Zurück" leads to "Fatal error: Call to a member function sub() on a non-object in /www/htdocs/admlogin/demo/adm_program/system/classes/tabledate.php on line 259" in v3.2.8 and just to a white page on the current demo version.

Same problem if you did not fill the field "title" and using the back-button.

**Comment by Fasse** [comment]
I could not reproduce this bug. Could you please describe the problem in more detail.

**Comment by papierkorb27** [comment]
Your steps are ok but you have to activate the "Ganztägig"-Häkchen to reproduce the bug before saving the event and using the back button.

**Comment by ximex** [comment]
found the problem.
tabledate.php L257: `$dateTime = DateTime::createFromFormat('Y-m-d H:i:s', $this->dbColumns['dat_end']);`
it's about the date format: `'Y-m-d H:i:s'`
the date format of `$this->dbColumns['dat_end']` is `'d.m.Y H:i'` and not `'Y-m-d H:i:s'`
