### ISSUE TITLE
Editing or checking invisible events not possible for admin user

### ISSUE THREAD

**Issue by papierkorb27** [Admidio/admidio#629]
Viewing or changing content of an event should be possible for the admin user nevertheless if he is not listed in the field "Sichtbar für". The admin needs this right if the creator of the event made some mistake or is not availabe.

**Comment by Fasse** [comment]
Within version 3.3 we have changed the location of the "visible for" right from the event  to the calendar. So you can set the visibility rights per calendar. Than you should also add the Admin to every calendar and he can edit all events.

**Comment by papierkorb27** [comment]
Hi fasse,

is it already possible to try out the new function at the playground and is the edit right for the admin added by default to the calendar?

**Comment by Fasse** [comment]
We will update the playground after merge of this pull request #627 

It's the view right you will set. The admin will not be set as default. You must set him manually.

**Comment by papierkorb27** [comment]
> It's the view right you will set. The admin will not be set as default. You must set him manually.

Sorry but should not have the admin the system wide admin right for all modules? He can manage users, roles, downloads, has database accesss but is not able to correct a event date without manuell settings?
