### ISSUE TITLE
Add UUID to each user

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#631]
We should add a new unique ID to each user. 

This id could be used for export/import to identify a user.

It could also be used for links, so we dont use the user id in links only the uid for security reasons.

**Comment by ximex** [comment]
https://www.admidio.org/forum/viewtopic.php?f=20&t=7565

**Comment by Fasse** [comment]
The following steps must be done:
- create field `usr_uid` and fill it at update with `PasswordHashing->genRandomPassword()`
- implement autofill of uid if a new user is created in class `Users`
- replace all usr_id within public parameters of a script with the uid

**Comment by Fasse** [comment]
We need this because of #612 . So we will use within links and page calls only the uuid.

Therefore we can integrate https://github.com/ramsey/uuid .
