### ISSUE TITLE
Update Libs for v3.3

### ISSUE THREAD

**Issue by ximex** [Admidio/admidio#638]
Do this update list some days before the release!
- [x] bootstrap: https://github.com/twbs/bootstrap/releases
- [x] bootstrap-datepicker: https://github.com/uxsolutions/bootstrap-datepicker/releases
- [x] browser-update: https://browser-update.org/#install
- [x] ckeditor: https://github.com/ckeditor/ckeditor-dev/releases
- [x] datatables: https://github.com/DataTables/DataTables/releases
- [x] datatables-datetime-moment: https://datatables.net/plug-ins/sorting/datetime-moment
- [x] html5shiv: https://github.com/aFarkas/html5shiv/releases
- [x] htmlawed: http://www.bioinformatics.org/phplabware/internal_utilities/htmLawed/
- [x] jquery: https://github.com/jquery/jquery/releases
- [x] jquery-file-upload: https://github.com/blueimp/jQuery-File-Upload/releases
- [x] lightbox: https://github.com/ashleydw/lightbox/releases
- [x] moment: https://github.com/moment/moment/releases
- [x] monolog: https://github.com/Seldaek/monolog/releases
- [x] noblecount: https://github.com/theproductguy/NobleCount
- [x] password_compat: https://github.com/ircmaxell/password_compat/releases
- [x] phpass: https://github.com/rchouinard/phpass/releases
- [x] phpmailer: https://github.com/PHPMailer/PHPMailer/releases
- [x] psr: https://github.com/php-fig/log/releases
- [x] random_compat: https://github.com/paragonie/random_compat/releases
- [x] respond: https://github.com/scottjehl/Respond/releases
- [x] secureimage: https://github.com/dapphp/securimage/releases
- [x] select2: https://github.com/select2/select2/releases
- [x] select2-bootstrap-theme: https://github.com/select2/select2-bootstrap-theme/releases
- [x] tcpdf: https://github.com/tecnickcom/TCPDF/releases
- [x] zxcvbn: https://github.com/dropbox/zxcvbn/releases
- [x] zxcvbn-php: https://github.com/bjeavons/zxcvbn-php/releases

Note: TCPDF is EOL

**Comment by Fasse** [comment]
We should not update CKEditor because they have a new theme that does not fit to our current theme. We should update with next Admidio version.

Also we should carefully update and test each lib after update. 
Also be careful if you update major versions. We should discuss this.

**Comment by ximex** [comment]
Every lib is up2date now. Leave this issue open. I will check again in the middle of the beta tests
