### ISSUE TITLE
Create Loginusers with password on CSV import

### ISSUE THREAD

**Issue by ximex** [Admidio/admidio#640]
Today only the user data gets imported but no users with passwords get generated
https://www.admidio.org/forum/viewtopic.php?f=20&t=7574&p=26748

**Comment by davidrei** [comment]
Another option would be to extend the 'reset password' process.
Currently if a user that has no user name set, doesn't get a mail to reset the password when trying to initiate the process with the mail address saved with his profile.

Possible improvement: send a mail with a special link that not only allows to set the password but also the password. This step could even be secured by only setting the user name first, then send the 'normal' reset password mail again to the registered mail address.

**Comment by kainhofer** [comment]
When migrating from another system, you usually want to preserve the user name and passwords. Currently, the only way seems to be to directly set the username/password in the adm_users database table (fiels usr_login_name and usr_password). And of course to log a corresponding log entry in the adm_user_log table.

If you have database access, this seems to be the most straightforward way for a migration, anyway.

**Comment by karibuTW** [comment]
That would be a great way to facilitate import.
Even with firstname.lastname or some sort of setting like this.
