### ISSUE TITLE
Backup create invalid sql if name contains high comma

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#658]
If you have an announcements title like 

> This is a 'Test'

Then the backup script will create an insert like this:
`INSERT INTO ann_announcements (ann_title, ann_int_value) VALUES ('This is a \'Test\', 3452)`

After 'Test' a second high comma is missing and will occurs in an error if you want to import that script.

**Comment by Fasse** [comment]
@ximex I found the problem. We call our method escapeString in line 449 of backup_script.php within this method we do a trim on high comma `trim($this->pdo->quote($string), "'")`. So if you have a high comma at the beginning or end it will be removed.

Why we do that?

**Comment by ximex** [comment]
No i don't know the reason. But it looks like that this comes from you: https://github.com/Admidio/admidio/commit/e861a0f97f325c75dc4e9162a39c361ce05abec2#diff-3be305bddf3543563b8489da6acee9d3R153

**Comment by Fasse** [comment]
ok, than I will remove this.

High comma should already save through PDO::quote()
