### ISSUE TITLE
Error when creating backup

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#666]
If you want to create a backup than the following error occurs:

> S Q L - E R R O R
> 
> CODE: 42000
> 1064
> 
> You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?' at line 1
> 
> B A C K T R A C E
> 
> FILE: adm_program/system/classes/database.php
> LINE: 634
> CALL: Database->showError()
> 
> FILE: adm_program/modules/backup/backup_script.php
> LINE: 83
> CALL: Database->queryPrepared()
> 
> FILE: adm_program/modules/backup/backup.php
> LINE: 147
> CALL: include('sol;Users/Markus/Sites/github/admidio/adm_program/modules/backup/backup_script.php')

**Comment by ximex** [comment]
It looks like that the prepared statement with the `LIKE ?` doesn't work here. found a fix
