### ISSUE TITLE
Password strength indicator during installation won't work

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#677]
After installtion the user who is created has no password. So `$_SESSION['user_password']` may not be filled.

**Comment by ximex** [comment]
Problem commit: https://github.com/Admidio/admidio/commit/3499978a3bd547ae0507b5418f4c959f00934919
Fixes the url path for strength indicator: https://github.com/Admidio/admidio/commit/008e0f2bf66ee9ef339d7bf2f1fbe1a68dd09928

**Comment by ximex** [comment]
fixed: https://github.com/Admidio/admidio/commit/038597a028a69f0dc08e9af5eff0c8af9a42d340
