### ISSUE TITLE
Translation with Transifex

### ISSUE THREAD

**Issue by ximex** [Admidio/admidio#68]
I see we have already an account there
https://www.transifex.com/organization/Admidio

**Comment by Fasse** [comment]
I have played a little bit with transiflex and it looks like a good solution for translation.
But therefore we must change our xml file. It should be an **Android String Resource**
http://developer.android.com/guide/topics/resources/string-resource.html
This format could be handled by transiflex and is very similar to our current xml.
`<resource>
  <string name="MY_TEXT">My text</string>
</resource>`

**Comment by ximex** [comment]
Here are the possible formats: http://docs.transifex.com/formats/
Maybe use a **json** format instead of a **xml** format?
I'm looking forward to the JSON Rest-API...

**Comment by Fasse** [comment]
Hmm, I uploaded the strings in android format because this was easy to transform. Now I want to try to download in a json format but as I understand the logic of transifex now its not possible to change the format.
Is a JSON format really useful because we still use PHP intern?

**Comment by ximex** [comment]
i think **now** json hasn't any advantage against xml. But if we change it to the Rest API i think it will. But we could leave it yet as xml and change it if we really see that json is better

**Comment by Fasse** [comment]
The code has changed to a transifex format. Now we must use it. Therefore this issue should still be open until all active translators work with it.

**Comment by Fasse** [comment]
Now we have used transifex for english translation and all others know about the new service.
