### ISSUE TITLE
Use Emails as login-name

### ISSUE THREAD

**Issue by ximex** [Admidio/admidio#691]
https://www.admidio.org/forum/viewtopic.php?f=7&t=7292

Allow longer login-names (today only 35 chars) and use this for email messages.

**Comment by ian76g** [comment]
Is there any concept for multiple users sharing the same email address?
Is the user/password then compared (using password) to all users of that email?

**Comment by Fasse** [comment]
Since version 4.0 we allow login names with 254 chars. So this issue can be closed.
