### ISSUE TITLE
Endless loop at checkRolesRight

### ISSUE THREAD

**Issue by sistlind** [Admidio/admidio#70]
Hi,
i encountered and endless loop at user logine here:
https://github.com/Admidio/admidio/blob/master/adm_program/system/classes/user.php#L166

$row = $this->db->fetch_array();
while($row)
{....

should be changed to:
$row = $this->db->fetch_array();
if($row)
{....

perhaps a is_array check is a bit better...

Best regards,
stefan

**Comment by ximex** [comment]
ok i think this was my fault. i did some optimizations but i think this goes wrong. there must be some more of this bugs.
in the past this looked like:
```php
while($this->db->fetch_array())
{....
```

**Comment by sistlind** [comment]
Ok, could also be, if there are more $rows, i am not familiar with the db layout...

The same problem exists her:
https://github.com/Admidio/admidio/blob/master/adm_program/system/function.php#L689

**Comment by Fasse** [comment]
So I hope I found all places. Thanks @sistlind for the analysis.

**Comment by ximex** [comment]
@Fasse i didn't found any other
