### ISSUE TITLE
Ändern des Endes einer Rollenmitgliedschaft nicht möglich

### ISSUE THREAD

**Issue by PascalTurbo** [Admidio/admidio#706]
Ändert man bei einer Ehemaligen Rollenmitgliedschaft das Datum, so wird der XHR Request gegen "https://mydomain.com/adm_program/modules/profile/[object%20Object]" abgesetzt. 
Vollkommen zurecht erhält man darauf vom Server die Antwort

```html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /adm_program/modules/profile/[object Object] was not found on this server.</p>
</body></html>
```

Den gleichen Fehler erhalte ich auch, wenn ich versuche, die Rollenmitgliedschaft über den "Rollenmitgliedschaften ändern" Bereich anzupassen.

**Comment by ximex** [comment]
Welche Admidio Version hast du?

**Comment by PascalTurbo** [comment]
Das Problem tritt erst nach dem Update auf 3.2.14 auf. Davor war ich auf 3.1.3.

**Comment by ximex** [comment]
Entweder ich hab was falsch verstanden oder ich kann den fehler nicht nachstellen. Kannst du den Fehler auf der Demo Seite nachstellen?

**Comment by PascalTurbo** [comment]
Ich konnte das Problem nachstellen und lösen. Offenbar wurde altes JavaScript aus dem Cache geladen.

Dieses Issue kann damit geschlossen werden. Neues Issue als Feature Request erstellt (#710)
