### ISSUE TITLE
Default Line Ending in Code

### ISSUE THREAD

**Issue by sistlind** [Admidio/admidio#71]
Hi,
why is this repository using Windows-Lineendings (\r\n) ? Most webservers are using linux and therefore unix-style encoding should be the default (\n)

Just an example: The downloaded config.php at setup has also \r\n leading to a file, where each second line is empty on a Linux machine.

If the repo has unix-style endings it can be easily edited by windows and unix-user, because windows-git is handling that transparently(checkout win-style, commit unix-style).

But if there is by default the windows-ending unix users have often the problem with ^M chars at commits/diffs.

Best regards
Stefan

**Comment by ximex** [comment]
i also prefer `\n` :+1:

**Comment by Fasse** [comment]
This is/was because most of the users have windows machines and therefore the line ending was set to windows so users have no problem to edit files.

**Comment by sistlind** [comment]
Is this a problem at IIS or apache for win? If not, i see not really a problem for windows users, because nowadays every serious editor can handle \n (e.g. notepad++, eclipse or wordpad :) )

Furthermore, developers can use the "check out windows style commit unix-style" at git and the releases can released for unix & windows separately.

**Comment by ximex** [comment]
@Fasse do you know the "windows/unix checkout" function?

**Comment by ximex** [comment]
@Fasse @sirnone @thomas-rcv what is your preference?

**Comment by sirnone** [comment]
for me it makes no difference - most of the time i work on an windows system... but git can handle this by settings:
https://help.github.com/articles/dealing-with-line-endings/

**Comment by Fasse** [comment]
ok, we can change it. If there will be problems later (maybe our users have problems with it) we can change it back.

**Comment by thomas-rcv** [comment]
I only work with window system.
But I don't if there are no conflicts in future

**Comment by ximex** [comment]
done: https://github.com/Admidio/admidio/commit/878a57e0417d46f08ae8cfbddfd6072041548f06
hopefully this was correct. I did it with the instructions from: https://help.github.com/articles/dealing-with-line-endings/

**Comment by ximex** [comment]
i think all worked corret
