### ISSUE TITLE
Multiple contact emails

### ISSUE THREAD

**Issue by loup-brun** [Admidio/admidio#713]
Hi,

In my organization, some parents would like to both receive an email when the email is sent to a member.

Currently, a message is only sent to the account-single email of a user.

Can we implement this?

Thanks!

**Comment by Fasse** [comment]
We should add an option to the message preferences where you can set that we send all emails to all configured email addresses. By default this option is deactivated.

**Comment by loup-brun** [comment]
Can you pin-point where in the code I can make the tweak, therefore without the need to add option in the preferences interface?

**Comment by Fasse** [comment]
This feature was already implemented with Admidio 3.3
