### ISSUE TITLE
Backup module won't work if you use MariaDB

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#717]
I use MariaDB and I got the following message if I open the backup module:
> Das Backupmodul kann nur bei einer MySQL-Datenbank genutzt werden.

**Comment by ximex** [comment]
what have you set in the config for `$gDbType`?

**Comment by Fasse** [comment]
I also set MySQL. I will Look later to this issue.

**Comment by ximex** [comment]
`mysql` in lower case? only lower case is correct

**Comment by Fasse** [comment]
Yes, it‘s autocorrection of my handy that makes this ;-)

I copy a working config from mysql database to the place Wehre I use MariaDB

**Comment by Fasse** [comment]
Problem found. `$g_root_path` was not set properly, so connected  to wrong webspace :/
