### ISSUE TITLE
Anhänge bei versendeten Nachrichten speichern

### ISSUE THREAD

**Issue by udobes** [Admidio/admidio#737]
Wir nutzen gerne die Möglichkeit Nachrichten an Verteiler zu senden.
Leider sieht man im Journal nicht, welche Anhänge man mitgeschickt hat.
Man sollte wenigstens die Dateinamen der Anhänge im Journal der versendeten Nachrichten sehen können.

Udo

**Comment by Fasse** [comment]
Duplicate to #173
