### ISSUE TITLE
On update dialog you could not edit user or passwort if it was wrong

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#74]
see forum http://www.admidio.org/forum/viewtopic.php?f=11&t=6482

**Comment by ximex** [comment]
@Fasse any updates here?

**Comment by ximex** [comment]
I think the problem is about this two lines: https://github.com/Admidio/admidio/blob/master/adm_program/installation/update.php#L302-L303
I think it's because of the `'directOutput' => true`

**Comment by Fasse** [comment]
I test this with version 3.2.3 and now it works.

So this issue is solved
