### ISSUE TITLE
Could not determine disk-usage

### ISSUE THREAD

**Issue by ximex** [Admidio/admidio#740]
Some hosters have problems with `ADMIDIO_PATH` as checked directory

https://www.admidio.org/forum/viewtopic.php?f=11&t=7820

**Comment by Fasse** [comment]
Now something is wrong. Look at https://www.admidio.org/playground . With 3.3.0 everything works. Now we got a notice and the error message.

**Comment by ximex** [comment]
@Fasse ok, i see... i have to think how we best fix this whole problem

**Comment by Fasse** [comment]
With version 4 the function works local and at our Admidio webpage. 
So problem might be fixed.
