### ISSUE TITLE
Check if set_time_limit is not disabled

### ISSUE THREAD

**Issue by ximex** [Admidio/admidio#741]
Check if set_time_limit is not disabled in php.ini with `disable_functions`

https://www.admidio.org/forum/viewtopic.php?f=3&t=7832
https://www.admidio.org/forum/viewtopic.php?f=3&t=7845
https://www.admidio.org/forum/viewtopic.php?f=3&t=7857

**Comment by Fasse** [comment]
Problem still there.
https://www.admidio.org/forum/viewtopic.php?f=3&t=7857

Why must we throw an exception if we could not set time limit? 
Maybe everything works with the current time limit.

**Comment by Fasse** [comment]
now only log this in debug mode and don't throw an exception
