### ISSUE TITLE
sorting of date rows fails when date uses German format (v3.2.14)

### ISSUE THREAD

**Issue by ian76g** [Admidio/admidio#756]
v. 3.2.14
If you have dates (membership start / end) and display them in d-m-Y, sorting them by click on the table header fails.
Workarround:
Display dates in English format Y-m-d. Then ordering in lists works according to the intension of the user.

**Comment by Fasse** [comment]
I could not reproduce the problem. Sorting by date is possible (version 3.3).
![bildschirmfoto 2018-05-10 um 09 59 37](https://user-images.githubusercontent.com/7038017/39859128-0c9a7012-5439-11e8-915f-ff0943f2b3ac.png)

**Comment by ian76g** [comment]
confirmed - fixed in 3.3.2
