### ISSUE TITLE
Fehler bei Update auf v3.3.2

### ISSUE THREAD

**Issue by sistlind** [Admidio/admidio#762]
Hallo,
habe gerade auf v3.3.2 upgedatet und bekomme folgenden Fehler, irgendwelche Tipps dazu?
Die Datenbankaktualisierung kam noch nicht.

> Fatal error: Uncaught UnexpectedValueException: Settings name "system_cookie_note" does not exist! in /home/webtyujdk/html/admidio/adm_program/system/classes/SettingsManager.php:134 Stack trace: #0 /home/webtyujdk/html/admidio/adm_program/system/classes/HtmlPage.php(480): SettingsManager->get('system_cookie_n...') #1 /home/webtyujdk/html/admidio/adm_program/system/classes/HtmlPage.php(761): HtmlPage->getHtmlHeader() #2 /home/webtyujdk/html/admidio/adm_program/system/classes/Message.php(262): HtmlPage->show() #3 /home/webtyujdk/html/admidio/adm_program/system/common.php(249): Message->show('Die Datenbankve...', 'Admidio - Updat...') #4 /home/webtyujdk/html/admidio/index.php(43): require_once('/home/webtyujdk...') #5 {main} thrown in /home/webtyujdk/html/admidio/adm_program/system/classes/SettingsManager.php on line 134

Gruß Stefan

**Comment by ximex** [comment]
duplicate of: #755 
already fixed
as workaround open the update.php page manual
