### ISSUE TITLE
You can use an event to bypass rights management to access (forbidden) profiles

### ISSUE THREAD

**Issue by ian76g** [Admidio/admidio#765]
using v3.3.3 I can access profiles with a user that has no rights to see those profiles by using a bug in the event module.

My temporary fix was described in issue #757

current behavior (still same as in v3.3.2):
role XYZ - members userA and userB
role XYZ has no right to see members

event E - members userA
event E has option "see participants of this event" checked

result:
userA can access profile of userB because the check in User.php just checks the role rights of the role XYZ (not allowed) and the role right of event E (allowed!).

error:
the script has to join the user himself into the check to see if boths users are in the same list(s) - so only when userB joins the event E then userA can access the profile of userB

**Comment by Fasse** [comment]
I could not reproduce the bug after fix of #757 

The temporary fix won't work because we must also check roles of userB where userB is member of a roleB that has the setting that every login user could view the profile. In that case userA is not member of roleB. This won't work with your fix.

**Comment by ian76g** [comment]
can be reproduced:
login to https://www.admidio.org/demo/adm_program/index.php
User: 757a  Password: DPinsg757
then visit:
https://www.admidio.org/demo/adm_program/modules/profile/profile.php?user_id=359 (757B)

User 757B is not part of that event and shares only group/role #757 with user 757A
role #757 does not allow list of members

only event does.

**Comment by Fasse** [comment]
Demo Gas Version 3.3.2

**Comment by Fasse** [comment]
Please try to reproduce this at https://www.admidio.org/playground
There the current version of 3.3 is installed.

**Comment by Fasse** [comment]
@ian76g can you please reproduce this as https://www.admidio.org/playground 
Your example at demo page is deleted because this page will be reset every day.
