### ISSUE TITLE
you can not cancel your participation after you accepted an event including anonymous guests

### ISSUE THREAD

**Issue by ian76g** [Admidio/admidio#767]
v.3.3.3
attend an event bring 4 guests.
either you are not part of the event (you do not appear in the list of attandes)
or you cant cancel your participation.

If the administrator disalows the anonymous guest checkbox - then attending and revoking of your participation works correct. you also appear in the list of participants

**Comment by Fasse** [comment]
@ian76g Can you please describe the problem more specific.

If I create an event and than add me with 4 guests, I'm still able to cancel the participation.

**Comment by ian76g** [comment]
ummm.. its half a year since I found that bug. If it does not exist anymore mark it as "can't reproduce"

**Comment by ian76g** [comment]
ha. just could it reproduce. I attend with 3 guests and cant revoke my participation. bug still exists
