### ISSUE TITLE
Set filter on acceptable file extensions for upload

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#77]
We should use the html attribut **accept** for file uploads to preselect the valid files for the user within the file browser.

This could be implemented within
csv-files to import new members
pngs and jpgs for profile photos

Therefore the method addFileUpload should get a new option.

**Comment by ximex** [comment]
:+1:

**Comment by ximex** [comment]
finished?

**Comment by Fasse** [comment]
But not commited to the master.

**Comment by ximex** [comment]
i made a pull request. (https://github.com/Admidio/admidio/pull/104)
feel free to merge

**Comment by Fasse** [comment]
Merge feature-branch to master.

**Comment by ximex** [comment]
merged
