### ISSUE TITLE
Remove IP address from auto login table

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#783]
We store the IP address in the session table and the auto login table. But we don't need them within Admidio. So we should remove this information.

**Comment by Fasse** [comment]
Therefore we must remove the functionality to check if the IP adress is still the same at every page. But this functionality won't work and was only enabled with the preference `$gCheckIpAddress`

**Comment by ximex** [comment]
We only have to mask the last or last two block like: 123.234.xxx.xxx
This is enough to fulfill the GDPR
Matomo (Piwik) does the same

**Comment by Fasse** [comment]
But do we still need the IP?

**Comment by ximex** [comment]
as we want to keep the check ip feature yes

**Comment by ximex** [comment]
ok

**Comment by Fasse** [comment]
Ok, only remove from adm_auto_login and anonymize in adm_session #789
