### ISSUE TITLE
Add checkbox with note on data protection

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#787]
Optional we should add a checkbox at the end of the registration form that the user must set with a text like this:
> Für den Versand und die Bearbeitung Ihrer Daten müssen Sie Ihr Einverständnis zur Speicherung der Daten geben. Ihre Daten werden ausschließlich für die Zwecke der Organisation XYZ gespeichert und  vertraulich behandelt. [link]Weitere Informationen zu unserem Datenschutz[/link]. 

The following points must be considered:
- Show checkbox only if new preference is set
- new preference is set to true per default
- if user don't set the checkbox at registation a notice came up and he get back to the registration
- show link to data protection only if this is set in the preferences

**Comment by exwima** [comment]
@Fasse Danke!
Der Vorschlag für einen Standardtext klingt schon gut. Könnte man den Text dann auch editieren?
Und wird die erfolgte Zustimmung irgendwie im Datensatz des Mitgliedes gespeichert (was passiert dann mit den schon vorhandenen Datensätzen, welcher Wert wird da eingetragen?), oder ist das Häkchen nur bei der Registrierung relevant?

**Comment by Fasse** [comment]
Erst einmal hätte ich das als Standardtext gesehen.

Der Default wäre jetzt, dass dies bei der Registrierung abgefragt würde. 

Man müsste dann noch prüfen bei bereits registrierten Mitgliedern, die den Haken noch nciht gesetzt haben, dass diese den beim Login angezeigt bekommen und bestätigen müssen. Das Flag sollte dann direkt in der adm_users gespeichert werden und ist für andere nicht editierbar.

Allerdings wird das jetzt alles was aufwändiger, wenn man länger darüber nachdenkt. Von daher weiß ich noch nicht, wann es rein kommt.

**Comment by exwima** [comment]
Ein Pflichtfeld bei allen Nutzern, dass einmalig auch bei bestehenden Nutzern abgeprüft wird, wäre natürlich schön. Die Idee, den Wert "hat in Datenverarbeitung eingewilligt" unveränderbar zu speichern, klingt gut. Nach DSGVO muss man dann aber vermutlich im Benutzerprofil trotzdem einen Hinweis auf die gespeicherte Zustimmung anbringen und die Information hinterlegen, dass eine Nutzung von Admidio ohne die Einwilligung in die Datenverarbeitung nicht möglich ist und man (wenn man die Einwilligung widerrufen will) "--> hier" seinen Account löschen bzw. die Löschung beantragen kann.

Für den Anfang wäre aber vermutlich schon das Häckchen "Ich willige in die Datenverarbeitung ein" (mit Link zur Datenschutzerklärung) hilfreich, ohne dessen Aktivierung die Registrierung nicht möglich ist. Vielleicht kann man das  ja auch schrittweise umsetzen?

**Comment by frest-de** [comment]
Man könnte ja "einfach" ein Checkbox Feld im Profil erstellen (In die Datenverarbeitung eingewilligt). Sobald das Mitglied zugestimmt hat (Bei Registrierung oder Login, falls noch nicht zugestimmt) wird es da eingetragen. Wenn man als Administrator den Eintrag dann noch bearbeiten kann, könnte man die Funktion dann auch gleich für alle Vereinsmitglieder nutzen. Generell benötigen die Vereine ja die Zustimmung nicht nur für die Internetseite. Von allen anderen Mitgliedern die nicht angemeldet sind holt man sie sich dann schriftlich ein und trägt es dann manuell bei Admidio nach.

**Comment by Fasse** [comment]
> Man könnte ja "einfach" ein Checkbox Feld im Profil erstellen (In die Datenverarbeitung eingewilligt). Sobald das Mitglied zugestimmt hat (Bei Registrierung oder Login, falls noch nicht zugestimmt) wird es da eingetragen. 

So haben wir es jetzt auch im Verein gemacht. Allerdings würde ich dennoch die zwanghafte Einwilligung softwareunterstützt einbauen wollen. Dies wäre dann kein einfaches Profilfeld, sondern ein fest kodiertes Feld, welches bei Registrierung oder beim erstmaligen Login angeklickt werden muss. Es wäre auch nicht von anderen editierbar (Auch nicht vom Admin),so dass man sich sicher sein kann, dass auch wirklich der User dies bestätigt hat.

**Comment by frest-de** [comment]
Ja, automatisch, so war es auch gemeint. ;)
Wenn es nicht editierbar ist, ist es natürlich erstmal die sauberere Lösung. Praktisch wäre eine Funktion zum editieren, die entsprechenden Rechte vorausgesetzt, aber dennoch, man könnte dann schriftlich eingeholte Einwilligungen ebenfalls in Admidio verwalten. In wieweit eine nachträgliche Manipulation erfolgt ist, lässt sich ja anhand der Historie ohnehin erkennen, hier ist der Zeitstempel besonders praktisch.

**Comment by Fasse** [comment]
Es hat leider etwas gedauert, aber für die nächste größere Version ist es nun möglich so ein Feld anzulegen. Bei Neuinstallation legen wir es auch selber an. Das sieht dann so aus:
![image001](https://user-images.githubusercontent.com/7038017/127760426-4d28bb7d-f670-4f3a-8b53-986e875fa877.png)

Das Feld ist da und es ist ein Pflichtfeld. Leider gibt es noch keinen Mechanismus für bestehende MItglieder, außer wenn sie DAten am Profil ändern, dann müssen sie das Pflichtfeld auch ausfüllen.
