### ISSUE TITLE
Rename download module into files & documents

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#792]
I think we should rename our "download" module into "files & documents" because this is, what we show there. These are the files and documents of the organization which you can also download.

What do you think?

**Comment by ximex** [comment]
I would only name it `Files` because `Documents` are `Files`. Maybe `Folders & Files`

**Comment by frest-de** [comment]
"Documents" sounds good.

**Comment by Fasse** [comment]
I don't like folders because folders have nothing to do with the content. We only use folders for grouping.

Yes "Documents" are "Files" but in my opinion the user will better understand what he will find in this module because most organization has documents that they will now put into the download module for download.
