### ISSUE TITLE
Supported Browsers

### ISSUE THREAD

**Issue by ximex** [Admidio/admidio#80]
Which browser do we want to support?
- IE: 9+
- Firefox: last and last ESR
- Chrome: last 2 versions
- Opera: last 2 versions (and Opera 12.1x?)
- Safari: 7+
- Android: 4.1+

If we drop IE8 and lower wo could remove the lib `respond.js`

**Comment by Bullnados** [comment]
I would also drop IE 9. IE9 is the last IE for Vista and Vista has just ~2%.
Perhaps wie could drop IE10 also
https://www.browser-statistik.de/statistiken/versionen/

**Comment by ximex** [comment]
if we drop IE9 and 10 we lose 20% of all IE Users. And the workarounds for IE9 and 10 are easy and less compared to IE8

**Comment by Bullnados** [comment]
IE has ~20% market share. If u drop IE9&IE10 u lose in 4% market share.
The second one is, that Ms drops support. For Win7 is just IE11 supported. IE10 is supported for WinServer 2012.
http://blogs.msdn.com/b/ie/archive/2014/08/07/stay-up-to-date-with-internet-explorer.aspx

That decision is for next release 3.1, that shall come in January 2016.
I think we/you should be radical. Everyone which use old IEs can install FF, Opera or Chrome

**Comment by ximex** [comment]
maybe we could drop IE9 and 10 if we impl #81 

if prefer to drop only IE8 and less in Admidio 3.1.
In Admidio 3.2 we could drop IE9 and 10, Opera 12, Safari 7 and Android 4.1-4.3

**Comment by Fasse** [comment]
Before we drop Browser support I want to know why. Admidio should support the oldest Browser possible. Only if there are incompatibilties that we Could not solve or dont want to solve Browser Support Could be removed.

**Comment by ximex** [comment]
It's always about keep the lib/program simple, slim and fast (more files to load over the internet -> slower display of the website)

It's always a: do we need to support all that old browsers for this less people or should we make our life as programmer easier?

I'm a fan of support **ONE** old version (2.4 or 3.0) for people who need this and look forward with the new versions.
Like jQuery or Ubuntu with their LTS Releases

**Comment by sirnone** [comment]
I think the main problem here would be that many clubs don't have new hard and software. (e.g.: our organizations PC is still on WinXP, because there is no money for new hardware/software)

so from my view it is already a big step to remove support for IE8 - but it has to come in next time.

my idea:
end of 2015 -> remove IE8 support
mid of 2016 -> remove IE9 support
end of 2016 -> remove IE10 support

**Comment by ximex** [comment]
@sirnone yes this is nearly the same as i mentioned in https://github.com/Admidio/admidio/issues/80#issuecomment-119472426

**Comment by Bullnados** [comment]
@sirnone 
Yeah you are right, but u can also install new FF on old machines?

**Comment by Fasse** [comment]
Yes everyone can install new browsers, but not everyone does this. Since we use bootstrap 3, we should use their Browser support Page and they support internet explorer 8 and above. In my opinion there is no need to drop support now. Maybe later if we want to use a lib that requires a new browser. But that could be discussed later.

**Comment by ximex** [comment]
ok. but could we make a small list from the browsers with version we want to support in v3.0 or v3.1 and document this list somewhere?

**Comment by Fasse** [comment]
Yes, I make a List and post it here. Finally this List should be displayed in the Download Page.

**Comment by Fasse** [comment]
I have created a list http://www.admidio.org/index.php?page=download
These are support conditions of Bootstrap 3. 

In my opinion we should close this issue of there are no more comments to this list. If we want to implement a feature or library that have dont support all that browsers or Bootstrap change their support in future versions than we should create a new issue and could discuss if or when we switch to this library.

**Comment by ximex** [comment]
i miss a list of the Browser **Versions**!
IE8+ ... ok
but which FF, Chrome, Opera, Safari Version?
If we add some custom css we need to know exactly which versions of which browsers we have to support.
look at: http://caniuse.com/#cats=CSS to know which browser supports which css feature

**Comment by Fasse** [comment]
But we depend on Bootstrap and they also have no version List and I'm not able to manage such a list because I dont use all OS and all browsers.

**Comment by ximex** [comment]
Quote from getbootstrap.com
> Specifically, we support the latest versions of the following browsers and platforms. On Windows, we support Internet Explorer 8-11. More specific support information is provided below.

> Out of the box, Android 4.1 (and even some newer releases apparently) ship with the Browser app as the default web browser of choice (as opposed to Chrome). Unfortunately, the Browser app has lots of bugs and inconsistencies with CSS in general.

i think this means nearly the list i wrote

**Comment by ximex** [comment]
waiting for comment from @Fasse :wink:

**Comment by ximex** [comment]
Here some facts about IE:
- last version for XP: IE8
- last version for Vista: IE9
- last version for 7, 8, 8.1: IE11

- XP is already EOL
- Vista will get EOL on 11.04.2017
- Win7 EOL 2020
- Win8.1 EOL 2023

Source: http://windows.microsoft.com/de-at/windows/lifecycle

Usage of IE8, 9, 10 each is about 1% in Europe and 1-2% worldwide
Usage of Win xxx in Europe:
- XP: 7%
- Vista: 2,8%
- 7: 44,6%
- 8: 2,2%
- 8.1: 14,7%
- 10: 13,6%

Usage of Win xxx worldwide:
- XP: 8,5%
- Vista: 1,8%
- 7: 49,2%
- 8: 3,1%
- 8.1: 13,5%
- 10: 10%

Source: http://gs.statcounter.com/

### Conclusion
- Drop IE8 LATEST with 4.0 (i think we could drop it with 3.1 or 3.2)
- Drop IE9 and IE10 LATEST with 5.0
- IE11 would need support ~2020 if Win7 and Win8 users won't drop massiv

**Comment by Fasse** [comment]
As mentioned several times before we should only drop Support if there is a reason (new necessary lib or something else). Drop Support just for dropping it is no reason :)

**Comment by ximex** [comment]
There is another reason too: get easier code.
But yes i know what you mean.

This was only a summary oft the current status and my opinion.

**Comment by ximex** [comment]
I researched a bit for the xhr requests Witz JavaScript on the Rest API. IE10 is the first IE that fully supports the standard. **Maybe** we geht problems with older versions.

**Comment by Fasse** [comment]
Also Bootstrap 4 only support newer versions of IE. So if we use new api or new Bootstrap we drop support for older versions.

**Comment by ximex** [comment]
http://www.heise.de/newsticker/meldung/Internet-Explorer-Microsoft-beendet-Support-fuer-aeltere-Versionen-3022070.html

**Comment by ximex** [comment]
http://www.computerbase.de/2016-01/internet-explorer-alte-versionen-update/

**Comment by ximex** [comment]
https://www.computerbase.de/2017-04/windows-vista-support-ende/
https://www.heise.de/newsticker/meldung/Support-Ende-erreicht-Tschuess-Vista-3675983.html

**Comment by ximex** [comment]
Windows 7 Support has stopped now: https://support.microsoft.com/de-at/help/4057281

**Comment by Fasse** [comment]
We will follow Bootstrap with browser compatibility.
