### ISSUE TITLE
Optional remove Admidio header from email

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#805]
Now we add a short sentence at the top of every email with the link to the homepage of the organization and a list of all selected recipients.

We should add a new preference to handle if this sentence should be shown.

The default should be to add this sentence to the e-mail

**Comment by ximex** [comment]
Wouldn't it be better if it is possible to edit the header? So if you edit to an empty string you also could "disable" the header

**Comment by Fasse** [comment]
Yes that sounds good.

**Comment by Fasse** [comment]
I have implemented the following solution for version 4:

- remove the hard coded email header
- improve the email template system, so we deliver a simple email template that has the same result as the hard coded email header now
- if recipients are set in BCC than no user names will be displayed within the #recipiens# parameters in email templates

so now you have all options to create the email as you like.
