### ISSUE TITLE
browser-update Plugin/Setting

### ISSUE THREAD

**Issue by ximex** [Admidio/admidio#81]
Implement this update message with a plugin or to enable it with a setting
https://browser-update.org/

**Comment by Bullnados** [comment]
+1

**Comment by Fasse** [comment]
It's not the Job of Admidio to Tell users to Update their browsers.

We should not implement such a service in our programm. Everyone could implement this on His homepage if he like.

**Comment by ximex** [comment]
I think every (modern) website should say their users to update their browsers to make to life of each webdeveloper easier and make the web faster and safer.

I read some years ago: The cost to optimize the website for IE makes about 20% of the full costs. (i think this isn't this bad in this days)

**Comment by Fasse** [comment]
If someone wants to implement this, then this should be optional and protected by a preference. The default should be **off**.

**Comment by ximex** [comment]
ok than i will look at this

**Comment by ximex** [comment]
where should i put the setting?
**Allgemeines** at last point after **Farbe Javascript-Editor**?

Where is the best place to put the javascript code in?
**htmlpage.php**?

**Comment by Bullnados** [comment]
BTW in the forum I asked if it is possible to create security menu. Put all the security stuff in it. I add the link tomorow

**Comment by ximex** [comment]
i only have to add the language files.
But i have one bug. the `$gPreferences` didn't get updated if i edit a value.
if i change the caching in "organization.php -> getPreferences()" i could see the change **after** a second refresh.
Any ideas?

**Comment by ximex** [comment]
@Bullnados i don't think this is a security stuff. But a security menu is a good idea. Feel free the open an issue for that.

**Comment by Fasse** [comment]
@ximex Put it in **Allgemeines** at last point after **Farbe Javascript-Editor**.
And yes, the javascript should be set in HtmlPage if the preference is set.

Have you run the update after you have edit the new preference?

**Comment by ximex** [comment]
@Fasse which update?

**Comment by Fasse** [comment]
The admidio Update, so that your prederence is added to the database and to the session.

**Comment by ximex** [comment]
where can i find this function?
but woudn't that mean that the other settings didn't get updated after save?

**Comment by ximex** [comment]
shouldn't this get done in "adm_program/modules/preferences/preferences_function.php" L 206ff ?

**Comment by Fasse** [comment]
Sorry I misunderstood your problem. If you have a checkbox than you must add the preference to the checkbox array in line 50 in preferences_function.php

**Comment by ximex** [comment]
@Fasse i already had done this.
maybe another bug in the master branch?

**Comment by Fasse** [comment]
hmm, don't know. Do you have a branch, where I can look at  the code?

**Comment by ximex** [comment]
i'm working on this and will push a branch in some minutes

**Comment by ximex** [comment]
https://github.com/Admidio/admidio/commit/8f94bc53b2f1524f1f29287fb0147a63df573ce2

**Comment by ximex** [comment]
merged

**Comment by Fasse** [comment]
Have you Change the preference description?

**Comment by ximex** [comment]
yes. here: https://github.com/Admidio/admidio/commit/69f0c4f024c16977b22549934bf0f465d25ebb91
pull request: https://github.com/Admidio/admidio/pull/120
