### ISSUE TITLE
Don't set new password if email sending fails

### ISSUE THREAD

**Issue by ximex** [Admidio/admidio#818]
If you send a new password to a user an the mail sending fails, the new password shouldn't be saved.

What do you think @Fasse ?

**Comment by Fasse** [comment]
Yes that Sounds useful.

If the mail Sending failed, we could reset the usr_new_password

**Comment by ximex** [comment]
Isn't it possible after that to login with an empty password?

**Comment by Fasse** [comment]
now at that point only the usr_new_password is reset not the usr_password. The usr_password will only be reset if the user complete the lost_password process.
