### ISSUE TITLE
Trying to contact the dev/authors!

### ISSUE THREAD

**Issue by deehill** [Admidio/admidio#823]
Hi.

Don't have an issue but I might be willing to send you some $$$ to make some changes to the app.

I'm in need of a basic group/membership app that can be hosted on a cloud/instance (aws/digitalocean/etc..) However, I can't find a demo of your app. I also don't have an email/contact for 
any of the devs.

Basically, I'm going to need a simple (mobile/web) app to allow users to signup/register/ and then track other users that they recruit. The app will be used as part of a process for creating/running a viral/pre-launch campaign. Think launchrock+membershipBackend. As a user signs up, I want the user to then be able to see/track who else has signed up to join.

Tracking of  users and the relationships of users to users they recruit will be handled by a userTrackingID/userReferralID, so there will be some updates to the backend db, as well as some additional site mods. 

It might just be easier to "fork" to a sep app... 

If you can hit me up, and you're interested, let's discuss.

-bruce
badouglas@gmail.com

**Comment by Fasse** [comment]
We had an Android app. Unfortunally this app was removed from the app store. This app was developed by a community member and not from us. But we can't contact this member.

Now we are also searching for an app developer.

**Comment by Fasse** [comment]
Will close this because this is no issue and the dev can be contact within the forum https://www.admidio.org/forum
