### ISSUE TITLE
Optional disable status 'I may take part' for event participation

### ISSUE THREAD

**Issue by magned** [Admidio/admidio#836]
After using the new status options for event participations last months I got some feedback from the group leaders. Using the status 'I may take part' just creates confusion while planning an event, they asked me for disabling but its just possible to deactivate the complete register function. Hopefully its possible to add a option to disable this status.

**Comment by Fasse** [comment]
This option sounds useful.

**Comment by sxwid** [comment]
Supporting this - a preference entry to enable or disable the feature. A Maybe Option creates much confusion for my group! Is there already a plan?
