### ISSUE TITLE
Event could not be saved if date format is like D d.m.Y

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#84]
see forum http://forum.admidio.org/viewtopic.php?f=3&t=6546

**Comment by ximex** [comment]
looks if this is from the same bug
http://admidio.org/forum/viewtopic.php?f=4&t=6573
http://admidio.org/forum/viewtopic.php?f=3&t=6568

**Comment by Bullnados** [comment]
Perhaps also this bug.
http://forum.admidio.org/viewtopic.php?f=20&t=6682
