### ISSUE TITLE
Drop Support of PHP 5.6 & 7.0 & 7.1

### ISSUE THREAD

**Issue by ximex** [Admidio/admidio#844]
This issue is for a release in 2020.

Support of PHP 5.6 & 7.0 will end with the beginning of 2019. (2018-12-31, 2019-12-03)
Support of PHP 7.1 ends on 2019-12-01

## Changes:
- **5.6 -> 7.0:** https://secure.php.net/manual/en/migration70.php
- **7.0 -> 7.1:** https://secure.php.net/manual/en/migration71.php
- **7.1 -> 7.2:** https://secure.php.net/manual/en/migration72.php

### 5.6 -> 7.0
- Indirect access to variables, properties, and methods will now be evaluated strictly in left-to-right order, as opposed to the previous mix of special cases. The table below shows how the order of evaluation has changed.
- Scalar type declarations come in two flavours: coercive (default) and strict. The following types for parameters can now be enforced (either coercively or strictly): strings (string), integers (int), floating-point numbers (float), and booleans (bool). They augment the other types introduced in PHP 5: class names, interfaces, array and callable.
- PHP 7 adds support for return type declarations. Similarly to argument type declarations, return type declarations specify the type of the value that will be returned from a function. The same types are available for return type declarations as are available for argument type declarations.
- The null coalescing operator (??) has been added as syntactic sugar for the common case of needing to use a ternary in conjunction with isset(). It returns its first operand if it exists and is not NULL; otherwise it returns its second operand.
- The spaceship operator is used for comparing two expressions. It returns -1, 0 or 1 when $a is respectively less than, equal to, or greater than $b. Comparisons are performed according to PHP's usual type comparison rules.
- Array constants can now be defined with define(). In PHP 5.6, they could only be defined with const.
- Two new functions have been added to generate cryptographically secure integers and strings in a cross platform way: random_bytes() and random_int().
- Static calls to methods that are not declared static are deprecated, and may be removed in the future.
- The salt option for the password_hash() function has been deprecated to prevent developers from generating their own (usually insecure) salts. The function itself generates a cryptographically secure salt when no salt is provided by the developer - therefore custom salt generation should not be needed.
- dirname() now optionally takes a second parameter, depth, to get the name of the directory depth levels up from the current directory.
- substr() and iconv_substr() now return an empty string, if string is equal to start characters long.
- Exception Hierarchy: Throwable, Error, TypeError, ParseError, AssertionError, ArithmeticError, DivisionByZeroError

### 7.0 -> 7.1
- Type declarations for parameters and return values can now be marked as nullable by prefixing the type name with a question mark. This signifies that as well as the specified type, NULL can be passed as an argument, or returned as a value, respectively.
- A void return type has been introduced. Functions declared with void as their return type must either omit their return statement altogether, or use an empty return statement. NULL is not a valid return value for a void function.
- The shorthand array syntax ([]) may now be used to destructure arrays for assignments (including within foreach), as an alternative to the existing list() syntax, which is still supported.
- Support for specifying the visibility of class constants has been added.
- A new pseudo-type (similar to callable) called iterable has been introduced. It may be used in parameter and return types, where it accepts either arrays or objects that implement the Traversable interface. With respect to subtyping, parameter types of child classes may broaden a parent's declaration of array or Traversable to iterable. With return types, child classes may narrow a parent's return type of iterable to array or an object that implements Traversable.
- Multiple exceptions per catch block may now be specified using the pipe character (|). This is useful for when different exceptions from different class hierarchies are handled the same.
- You can now specify keys in list(), or its new shorthand [] syntax. This enables destructuring of arrays with non-integer or non-sequential keys.
- Support for negative string offsets has been added to the string manipulation functions accepting offsets, as well as to string indexing with [] or {}. In such cases, a negative offset is interpreted as being an offset from the end of the string.
- Functions: session_create_id(), session_gc(), is_iterable()
- Previously, a warning would be emitted for invoking user-defined functions with too few arguments. Now, this warning has been promoted to an Error exception. This change only applies to user-defined functions, not internal functions.
- session_start() now returns FALSE and no longer initializes $_SESSION when it failed to start the session.

### 7.1 -> 7.2
- A new type, object, has been introduced that can be used for (contravariant) parameter typing and (covariant) return typing of any objects.
- Abstract methods can now be overridden when an abstract class extends another abstract class.
- The modern Sodium cryptography library has now become a core extension in PHP.
- Argon2 has been added to the password hashing API.
- Constant FILEINFO_EXTENSION.
- The officially supported, minimum Windows versions are now Windows 7/Server 2008 R2.
- The __autoload() method has been deprecated because it is inferior to spl_autoload_register() (due to it not being able to chain autoloaders), and there is no interoperability between the two autoloading styles.
- The utf8_encode() and utf8_decode() functions have now been moved to the standard extension as string functions, whereas before the XML extension was required for them to be available.
- The $additional_headers parameter of mail() and mb_sendmail() now also accepts an array instead of a string.

**Comment by ximex** [comment]
@Fasse how long do you want to support PHP 5.6? It's already unsupported (no updates) for more than 1 year. Same for v7.0. v7.1 is also unsupported for more than 4 months. the step to min version v7.0 would be great for the new strict types

**Comment by Fasse** [comment]
@ximex As always the question which feature will you like to implement that needs a higher PHP version? If we have no necessary feature there is no need to drop support.

**Comment by ximex** [comment]
now i have a reason ;-) (#487)

**Comment by Fasse** [comment]
Ok, but I would like to release 4.0 with support for PHP 5.6+ . Than we could to the next step PHP 7.1+ for version 4.1

**Comment by ximex** [comment]
wouldn't it be better to make the next release v3.4 and with the breaking changes the v4.0?
or the next v4.0 and go directly to v5.0 with the breaking change
