### ISSUE TITLE
Don't list personal receiver data in email

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#870]
If we send a mail to some members we list them at the beginning of the email. That should not be done. We should only list roles and maybe a text, that other people also got that mail.

view forum https://www.admidio.org/forum/viewtopic.php?f=7&t=7702&p=29416#p29415

**Comment by ximex** [comment]
i would add the count of the additional users instead of their names

**Comment by jreimone** [comment]
It wouldd be great to leave it to the sender to send the names or role names. This should definitely be a switch or a property in the settings. Not everyone of the receivers need to no who else received a mail, neither the count of other receivers is important. Sometimes those information is also quite sensible and should not be transmitted. Maybe a solution would be that the sender gets an email which contains all that information but not the receivers.

**Comment by ComiR** [comment]
I'd even go so far to remove the line https://github.com/Admidio/admidio/blob/9eb20ce3182d88ddbc96ebb82bece970c8333c28/adm_program/modules/messages/messages_send.php#L512 (method defined [here](https://github.com/Admidio/admidio/blob/9eb20ce3182d88ddbc96ebb82bece970c8333c28/adm_program/system/classes/Email.php#L410)) completely and put the resulting line in a default template.

The less intrusive version (making this line optional through a setting) would also be fine with me.

**Comment by Fasse** [comment]
I have implemented the following solution for version 4:
- remove the hard coded email header
- improve the email template system, so we deliver a simple email template that has the same result as the hard coded email header now
- if recipients are set in BCC than no user names will be displayed within the #recipiens# parameters in email templates

so now you have all options to create the email as you like.
