### ISSUE TITLE
Admidio cant set cookies in Docker environment in combination with Traefik 

### ISSUE THREAD

**Issue by leonfilser** [Admidio/admidio#898]
Hi! I am using Admidio in a Docker environment in combination with Traefik used as a reverse proxy.
Everytime I try to login the following error appears:

> Der Login kann nicht durchgeführt werden, da Ihr Browser das Setzen von Cookies verbietet!
> 
> Damit Sie sich erfolgreich anmelden können, müssen Sie Ihren Browser so einstellen, dass dieser Cookies von 0efb778bedda akzeptiert.

English:

> The login cannot be carried out, because your browser forbids the setting of cookies!
> 
> In order to log in successfully, you must set your browser to accept cookies from 0efb778bedda.

0efb778bedda. is the ID of my Traefik Container

I did a bit of debugging and found out that in 
admidio/adm_program/system/bootstrap/constants.php there is (probably) an issue on line 55-60

```
if(isset($_SERVER['HTTP_X_FORWARDED_SERVER']) && $_SERVER['HTTP_X_FORWARDED_SERVER'] !== $_SERVER['HTTP_HOST'])
{
    // if ssl proxy is used than this proxy is the host and the cookie must be set for this
    define('HOST', $_SERVER['HTTP_X_FORWARDED_SERVER'] . $port . '/' . $_SERVER['HTTP_HOST']); // ssl.example.org/my.domain.net
    define('DOMAIN', strstr($_SERVER['HTTP_X_FORWARDED_SERVER'] . $port . ':', ':', true)); // ssl.example.org
}
```

I replaced the Code with the following and it turned out to work
```
if(isset($_SERVER['HTTP_X_FORWARDED_SERVER']) && $_SERVER['HTTP_X_FORWARDED_SERVER'] !== $_SERVER['HTTP_HOST'])
{
    // if ssl proxy is used than this proxy is the host and the cookie must be set for this
    define('HOST', $_SERVER['HTTP_X_FORWARDED_HOST'] . $port . '/' . $_SERVER['HTTP_HOST']); // ssl.example.org/my.domain.net
    define('DOMAIN', strstr($_SERVER['HTTP_X_FORWARDED_HOST'] . $port . ':', ':', true)); // ssl.example.org
}
```

If you want to I can open a pull request to fix this

**Comment by Fasse** [comment]
Hmm, I'm not sure if your change will work for proxy servers.

The difference between these two values is the following:
- X-Forwarded-Host The original host requested by the client in the Host HTTP request header.
- X-Forwarded-Server The hostname of the proxy server.

We add this to get the hostname of the proxy server, so it will work on ssl if the proxy server is different. We should test this change with someone who use a proxy server before we add this to the code.

**Comment by sumnerboy12** [comment]
Is there any progress on this? I would like to run Admidio in docker with Traefik as the reverse proxy also, and currently I can't login. Any known workarounds?

**Comment by Fasse** [comment]
@sumnerboy12 Did the workaround also work for you?

**Comment by sumnerboy12** [comment]
I didn't try it sorry @Fasse. I was in the middle of migrating a whole load of self-hosted services to docker and didn't fancy having to do manual steps. I will try and give it a go in the next week or so if I find time, and report back.

**Comment by sumnerboy12** [comment]
@Fasse I can confirm the workaround is working for me also.

**Comment by Fasse** [comment]
Ok, I will integrate this change to Admidio 4 and than we will see, if users with proxy servers have problems with this change within the beta phase.

**Comment by Fasse** [comment]
Ok, I will integrate this change to Admidio 4 and than we will see if users with proxy server have problems with this change within the beta phase.

**Comment by Fasse** [comment]
So add this fix to Admidio 4 and referenced in the sourcecode to this issue. We will see if other environments still work.

**Comment by Oberfeldwedler** [comment]
I tested leonfilser's snippet and it worked flawlessly.

My setup:
Docker
traefik as a reverse proxy
php:7.4-fpm
nginx:1.19.2

nginx.conf
```
# user  1006 1006;
pid   /tmp/nginx.pid;

events {
  worker_connections  1024;  ## Default: 1024
}



http {
  include mime.types;
  index index.php;

  client_body_temp_path /tmp/client_temp;
  proxy_temp_path       /tmp/proxy_temp_path;
  fastcgi_temp_path     /tmp/fastcgi_temp;
  uwsgi_temp_path       /tmp/uwsgi_temp;
  scgi_temp_path        /tmp/scgi_temp;



  # Upstream to abstract backend connection(s) for php
  upstream php {
    # server unix:/tmp/php-cgi.socket;
    server php:9000;
  }

  server {
    ## Your website name goes here.
    server_name admidio.samdyndns.de;
    ## Your only path reference.
    root /var/www/html/admidio;



    location = /favicon.ico {
      log_not_found off;
      access_log off;
    }

    location = /robots.txt {
      allow all;
      log_not_found off;
      access_log off;
    }

    location / {
      # This is cool because no php is touched for static content.
      # include the "?$args" part so non-default permalinks doesn't break when using query string
      try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
      #NOTE: You should have "cgi.fix_pathinfo = 0;" in php.ini
      include fastcgi_params;
      fastcgi_intercept_errors on;
      fastcgi_pass php;
      #The following parameter can be also included in fastcgi_params file
      fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
      expires max;
      log_not_found off;
    }
  }
}
```

**Comment by Fasse** [comment]
Now also changed the condition check from 
`if (isset($_SERVER['HTTP_X_FORWARDED_SERVER']) && $_SERVER['HTTP_X_FORWARDED_SERVER'] !== $_SERVER['HTTP_HOST'])`
to
`if (isset($_SERVER['HTTP_X_FORWARDED_HOST']) && $_SERVER['HTTP_X_FORWARDED_HOST'] !== $_SERVER['HTTP_HOST'])`
