### ISSUE TITLE
Check for URLs does not allow underscore (_)

### ISSUE THREAD

**Issue by kroll-git** [Admidio/admidio#902]
I believe the regex in `adm_program/system/classes/StringUtils.php` does not allow an underscore.

https://github.com/Admidio/admidio/blob/d8b3a7cbf6775f2d7aee8bdca741ccd5280ca6f0/adm_program/system/classes/StringUtils.php#L184-L186

**Comment by Fasse** [comment]
I saw that in the code but could not reproduce it within our program.

Could you reproduce this error?

**Comment by Fasse** [comment]
The underscore is not explicit listed, but it's allowed and no error is shown.
