### ISSUE TITLE
Forward link in pagination will not be disabled

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#910]
Forward link in pagination will not be disabled if you are at the last page.

**Comment by ximex** [comment]
@Fasse what was exactly the problem here? `ceil` should return a float. so why we need to cast it to an integer?

**Comment by Fasse** [comment]
@ximex The problem was the following line which don't work until the int was set: https://github.com/Admidio/admidio/blob/0964a185b9eb5caef94e58e5c46f076cd951fb55/adm_program/system/bootstrap/function.php#L255

**Comment by ximex** [comment]
ok got it. `int === float` => false
