### ISSUE TITLE
Deprecated notice in PHP 7.3 on pageload

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#923]
The following notice shows up in PHP 7.3 

> Deprecated: strpos(): Non-string needles will be interpreted as strings in
the future. Use an explicit chr() call to preserve the current behavior in
/****/adm_program/system/constants.php
on line 75

**Comment by ximex** [comment]
what type other than string has `ADMIDIO_URL_PATH`?

**Comment by Fasse** [comment]
That was a problem a user reported. And this solution fix the problem. 

I could not reproduce that problem for myself.
