### ISSUE TITLE
DB Backup for entire Database

### ISSUE THREAD

**Issue by sistlind** [Admidio/admidio#93]
Hi,
there should be at least an option to backup the entire database or all tables with the configured tableprefix. Otherwise, data from plugins can get lost (e.g. awards).

Perhaps also the "adm_my_files" folder.

Best regards,
Stefan

**Comment by ximex** [comment]
couldn't you make a db dump with *phpmyadmin* or something else?

**Comment by sistlind** [comment]
Yes, i can do it this way. As every user.. so you can drop this function completely?

I think the regular user would suspect that a admidio-backup contains the whole data :)
and it should be as easy as possible, because the data is very crucial in most installations.

**Comment by ximex** [comment]
found something: https://github.com/ifsnop/mysqldump-php

**Comment by sistlind** [comment]
I am not shure, if it is necessary to backup the whole database, perhaps it is better to select only the tables with the configured prefix. This can be done with the following small patch. It just reads the tablenames from the database and uses the only these configured in constants.php(where no plugin should do any changes)
```patch
diff --git a/adm_program/modules/backup/backup_script.php b/adm_program/modules/backup/backup_script.php
index 6733a3d..aa63fb2 100644
--- a/adm_program/modules/backup/backup_script.php
+++ b/adm_program/modules/backup/backup_script.php
@@ -75,13 +75,12 @@ $newfullfilename = $backupabsolutepath.$fullbackupfilename;
 unset($SelectedTables);
 unset($tables);
 
-// create a list with all tables out of the "table defines"
-foreach (get_defined_constants() as $key => $value)
+// create a list with all tables with configured table prefix
+$SQLquery='SHOW TABLES LIKE \''.$g_tbl_praefix.'\_%\'';
+$result = $gDb->query($SQLquery);
+while($table=$gDb->fetch_array($result))
 {
-    if (substr($key, 0, strlen('TBL_'))=='TBL_')
-    {
-        $tables[] = $value;
-    }
+	$tables[] = $table[0];
 }
 $SelectedTables[$g_adm_db] = $tables;
```

**Comment by Fasse** [comment]
:+1: 
The idea of sistlind is good. We should change this, so the backup will be done for alle tables with the specified praefix.

I backup of the whole database is not the job of a Admidio backup. Therefore the user should use other tools.

**Comment by Fasse** [comment]
I have added your changes for the next release.
Thanks for the code snippet.
