### ISSUE TITLE
Problems with undisclosed recipients when send mail to more than one recipient

### ISSUE THREAD

**Issue by Fasse** [Admidio/admidio#932]
View forum https://www.admidio.org/forum/viewtopic.php?f=3&t=8511&p=0#p0

Wir hatten / haben das Problem auch. Wir haben herausgefunden, dass die Ursache bei den beiden Zielen das TO Feld ist. Diesen wird bei Verwendung von BCC mit "To: undisclosed-recipients:;" belegt. Damit kommt weder GMX noch WEB (scheint mittlerweile ein Anbieter zu sein) zurecht. Für Rollen hat bei uns geholfen in den Einstellungen für den Mailversand den Empfänger der Antwort auf "Absender" zu stellen. Damit wird das Feld gefüllt und der Fehler tritt nicht mehr auf.

Allerdings scheint dieses Feld nicht zu greifen, wenn eine Mail an mehrere, einzeln ausgewählte Empfänger (keine Rolle!) versendet wird. Dann tritt der Fehler immer noch auf.

**Comment by wobsta** [comment]
Ich hab schon im Forum gepostet, aber vielleicht wird es übesehen, dass es dort noch eine neue Info gibt. Deshalb hier das selbe noch mal:

Wir beobachten das Problem auch seit einigen Wochen. Ich habe in den Fehlermeldungen noch weiter gesucht, und folgende Zusatzinfo: Es scheint zwei To-Felder in den E-Mails zu geben, die von Admidio ja jeweils an einen ganzen Schwung Leute geschickt werden. Einmal ist es eine leere To-Zeile:

To:

und dann in der selbe E-Mail noch diese Header-Zeile:

To: undisclosed-recipients:;

Ich habe an anderer Stelle (bei diesen selben E-Mails von Admidio gesendet) auch folgendes entdeckt:

X-Amavis-Alert: BAD HEADER SECTION, Duplicate header field: "To"

Vielleicht hilft das was weiter. Wir betreiben das aktuelle Admidio 3.3.17 ...

**Comment by Fasse** [comment]
Problem fixed and default setting changed to **Sender**.

**Comment by wobsta** [comment]
I patched our admidio 3.3.17 instance by cdf645b7332c68bdb51c5d834a6fba92f7a2750a and tried again (twice). Unfortunately this did not yet resolve the issue for us.

**Comment by Fasse** [comment]
Hmm, so you still have two "to" lines in your header?

Did you try to send without "undisclosed-recipients"?

Do you use smtp oder mail() ?

**Comment by Fasse** [comment]
@wobsta It looks like the latest release of PHPMailer (which we use for sending mails) fixed your problem:
https://github.com/PHPMailer/PHPMailer/releases/tag/v6.1.8

I have updated Admidio 4 with this version. Admidio 3 couldn't use that version because it requires a higher PHP version.
