### ISSUE TITLE
Replace master/slave, black/white

### ISSUE THREAD

**Issue by ximex** [Admidio/admidio#937]
Replace problematic words
https://www.heise.de/news/Nichtrassistische-Sprache-Abschied-von-Blacklist-und-Whitelist-4784291.html

**Comment by Fasse** [comment]
Some of the things I found:

master (Branch)  --> should be fixed if GitHub has better migration tools, beginning 2021 --> synonym **main**
blacklist --> StringUtils class --> synonym ???
whitespace --> **blank space**, **empty space**
webmaster --> **administrator**
master data --> **main data**

**Comment by ximex** [comment]
Most other projects change Blacklist to Denylist or Blocklist (Whitelist to Allowlist)
