### ISSUE TITLE
PostgreSql: View messages returns system error (http error code 500)

### ISSUE THREAD

**Issue by wobsta** [Admidio/admidio#938]
We are on the latest admidio release 3.3.17, however, with an rather old php 7.0.33 and Postgres 9.5.21. When clicking on a message listed at adm_program/modules/messages/messages.php, the system responds with an http error 500. Reason is, that the database timestamp also contains microseconds and the conversion returns `False` if the format string is not updated accordingly. Adjusting the format string accordingly resolves the issue at the moment, but we might need a conversion which is more flexible regarding the format?!

```php
wobsta@my:~/heisenberg$ diff -u admidio-3.3.17/adm_program/modules/messages/messages_write.php admidio/adm_program/modules/messages/messages_write.php
--- admidio-3.3.17/adm_program/modules/messages/messages_write.php	2020-08-15 03:30:14.000000000 +0200
+++ admidio/adm_program/modules/messages/messages_write.php	2020-10-09 21:07:36.879429527 +0200
@@ -659,7 +659,7 @@
             $receiverName = '<div class="panel-footer">'.$gL10n->get('MSG_OPPOSITE').': '.$receiverName.'</div>';
         }
 
-        $date = \DateTime::createFromFormat('Y-m-d H:i:s', $row['msc_timestamp']);
+        $date = \DateTime::createFromFormat('Y-m-d H:i:s.u', $row['msc_timestamp']);
         $page->addHtml('
         <div class="panel panel-default">
             <div class="panel-heading">
```

**Comment by Fasse** [comment]
Thanks for the detailed error description. 

I fixed this error with a different call of the DateTime constructor.
`$date = new \DateTime($row['msc_timestamp']);`

There were also some other PostgreSQL bugs within the messages environment that I also fixed. Just have a look at my commits.
