### ISSUE TITLE
Awards Categories could not be deleted

### ISSUE THREAD

**Issue by sistlind** [Admidio/admidio#94]
Hi,
in the current version, it is not possible to delete awards categories, would you pleas include the following patch?
```patch
diff --git a/adm_program/system/classes/tablecategory.php b/adm_program/system/classes/tablecategory.php
index 979249b..7d1f520 100644
--- a/adm_program/system/classes/tablecategory.php
+++ b/adm_program/system/classes/tablecategory.php
@@ -258,6 +258,11 @@ class TableCategory extends TableAccess
                 $this->elementTable = TBL_DATES;
                 $this->elementColumn = 'dat_cat_id';
             }
+            elseif($this->getValue('cat_type') == 'AWA')
+            {
+                $this->elementTable = 'adm_user_awards';
+                $this->elementColumn = 'awa_cat_id';
+            }
         }
 
         return $returnValue;
```
For a more consistent solution, TBL_AWARDS could be introduced and set https://github.com/Admidio/admidio/blob/master/adm_program/system/constants.php

Another question:
What are these $objecs for, because they are not used?
https://github.com/Admidio/admidio/blob/master/adm_program/system/classes/tablecategory.php#L73-L89

Best regards, Stefan

**Comment by ximex** [comment]
http://admidio.org/forum/viewtopic.php?f=9&t=6566

**Comment by Fasse** [comment]
I have changed your script a little. 
>            elseif($this->getValue('cat_type') == 'AWA')
>            {
>                $this->elementTable  = $g_tbl_praefix.'_user_awards';
>                $this->elementColumn = 'awa_cat_id';
>            }

Do you use the **$g_tbl_praefix** within your plugin?

The part with the **$object** was old code and I have delete that part.

**Comment by sistlind** [comment]
The patch is not working here:
    Table 'admidio.adm_user_awards' doesn't exist
I have no idea, where these "admidio." is coming from, but nevertheless it could not work in that way, because $g_tbl_praefix is not global and not accessable within this class.

Here my suggestion:
```patch
diff --git a/adm_plugins/awards b/adm_plugins/awards
index 07a7bfd..848d7e0 160000
--- a/adm_plugins/awards
+++ b/adm_plugins/awards
@@ -1 +1 @@
-Subproject commit 07a7bfdbe47cdacb9436f6186e9fb5dc9ac7a6ac
+Subproject commit 848d7e09b9d14e445876d6cda34932453c11124a
diff --git a/adm_program/system/classes/tablecategory.php b/adm_program/system/
index 8cbd100..c657847 100644
--- a/adm_program/system/classes/tablecategory.php
+++ b/adm_program/system/classes/tablecategory.php
@@ -242,7 +242,7 @@ class TableCategory extends TableAccess
             }
             elseif($this->getValue('cat_type') == 'AWA')
             {
-                $this->elementTable  = $g_tbl_praefix.'_user_awards';
+                $this->elementTable  = TBL_USER_AWARDS;
                 $this->elementColumn = 'awa_cat_id';
             }
         }
diff --git a/adm_program/system/constants.php b/adm_program/system/constants.ph
index 964a87c..438a41b 100644
--- a/adm_program/system/constants.php
+++ b/adm_program/system/constants.php
@@ -85,6 +85,8 @@ define('TBL_USERS',              $g_tbl_praefix. '_users');
 define('TBL_USER_DATA',          $g_tbl_praefix. '_user_data');
 define('TBL_USER_FIELDS',        $g_tbl_praefix. '_user_fields');
 define('TBL_USER_LOG',           $g_tbl_praefix. '_user_log');
+define('TBL_USER_AWARDS',       $g_tbl_praefix. '_user_awards');
 
 // constants for column rol_leader_rights
 define('ROLE_LEADER_NO_RIGHTS', 0);
```
BTW: It would be a good idea to declare the praefix also as a define.

Best regards,
Stefan

**Comment by Fasse** [comment]
With the last fix I made it accessable.

**Comment by sistlind** [comment]
perfect, thanks! ->closed
