### ISSUE TITLE
Rework PasswordUtils to support Argon2i(d)

### ISSUE THREAD

**Issue by ximex** [Admidio/admidio#942]
Rework PasswordUtils to support Argon2i and Argon2id hashing algorithms.
Also custom options should be possible.

Remove md5 as it is really long ago that it was supported.

**Comment by Fasse** [comment]
We used md5 in the past. If someone has his password hashed with md5, it should be possible that we could read it. I saw that you removed md5, so it isn't possible to login if you have a password with md5 hash. Is that right?

**Comment by Fasse** [comment]
@ximex The following error occured when I update from 3.3 to 4.0
`Notice: Undefined index: time in /.../admidio/adm_program/installation/update_functions.php on line 78`

I have set no user and password dialog for update.

**Comment by ximex** [comment]
@Fasse hope this fixed it. doesn't test it. but the previous impl was wrong

**Comment by ximex** [comment]
> We used md5 in the past. If someone has his password hashed with md5, it should be possible that we could read it. I saw that you removed md5, so it isn't possible to login if you have a password with md5 hash. Is that right?

i had added an update procedure that resets all md5 passwords and send an an email to that users to get rid of the md5 hashes

**Comment by Fasse** [comment]
now it works.

**Comment by Fasse** [comment]
There is still a problem with the function `costBenchmark` . The array parameter `cost` will not be set everytime.

> Notice: Undefined index: cost in /Users/Jennifer/Sites/github/admidio/adm_program/installation/update_functions.php on line 80
